# Thực nghiệm ABSA – Clean Ablation Training

Notebook này phục vụ huấn luyện và đánh giá các biến thể mô hình cho bài toán Aspect-Based Sentiment Analysis (ABSA) trên tập dữ liệu restaurant.

Mục tiêu của notebook:

1. Khởi tạo một phiên thực nghiệm có thể tái lập trên Kaggle.
2. Huấn luyện lại toàn bộ mô hình từ đầu, không sử dụng checkpoint hoặc log huấn luyện có sẵn.
3. So sánh các cấu hình ablation chính: `CLS`, `aspect_attention`, `hybrid pooling`, và `neutral class weighting`.
4. Xuất toàn bộ kết quả tuning/final evaluation thành file `.zip` để phân tích sau huấn luyện.

Yêu cầu khi chạy trên Kaggle:

- Bật **GPU**.
- Bật **Internet** nếu cần tải pretrained model lần đầu.
- Thêm file `absa_clean_ablation_fresh.zip` vào phần **Input Dataset** của notebook.

In [1]:
from pathlib import Path
import os, shutil, zipfile, json, subprocess, sys

print("Python:", sys.version)
print("Kaggle working exists:", Path("/kaggle/working").exists())
try:
    subprocess.run(["nvidia-smi"], check=False)
except FileNotFoundError:
    print("nvidia-smi not found; GPU may be disabled.")

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Kaggle working exists: True
Sat Jun 20 15:47:22 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.159.04             Driver Version: 580.159.04     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla T4                       Off |   00000000:00:05.0 Off |                    0 |
| N/A   34C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

## 1. Khởi tạo môi trường thực nghiệm và nạp mã nguồn

Bước này thiết lập thư mục làm việc, chuẩn hóa trạng thái phiên chạy và giải nén package mã nguồn từ Kaggle Input vào `/kaggle/working`.

Việc chuẩn hóa trạng thái giúp đảm bảo kết quả huấn luyện được sinh ra từ lần chạy hiện tại, không bị ảnh hưởng bởi artifact được tạo từ các lần chạy trước trong cùng phiên Kaggle.

In [2]:
WORK = Path('/kaggle/working') if Path('/kaggle/working').exists() else Path.cwd()
INPUT = Path('/kaggle/input/datasets/banhbaogachcua/nlp-melaycon')
PROJECT = WORK / 'absa_clean_ablation_fresh'

CLEAN_RUN = True
if CLEAN_RUN:
    for path in [
        PROJECT,
        WORK / 'tuning_ablation_core',
        WORK / 'outputs_ablation_core',
        WORK / 'tuning_ablation_desc',
        WORK / 'outputs_ablation_desc',
        WORK / 'absa_ablation_results_fresh.zip',
    ]:
        if path.exists():
            print('Resetting generated artifact path:', path)
            if path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink()

zip_candidates = []
if INPUT.exists():
    zip_candidates = list(INPUT.rglob('absa_clean_ablation_fresh.zip'))
    if not zip_candidates:
        zip_candidates = list(INPUT.rglob('absa_clean_ablation*.zip'))

if zip_candidates:
    zip_path = zip_candidates[0]
    print('Extracting:', zip_path)
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(WORK)
else:
    train_candidates = list(INPUT.rglob('train.py')) if INPUT.exists() else []
    if not train_candidates:
        raise FileNotFoundError('Không tìm thấy absa_clean_ablation_fresh.zip hoặc train.py trong /kaggle/input')
    src = train_candidates[0].parent
    print('Copying source folder:', src)
    shutil.copytree(src, PROJECT, dirs_exist_ok=True)

if not (PROJECT / 'train.py').exists():
    candidates = [p.parent for p in WORK.rglob('train.py') if 'absa_clean_ablation' in str(p.parent)]
    if not candidates:
        raise FileNotFoundError('Extract xong nhưng không tìm thấy train.py')
    PROJECT = candidates[0]

print('PROJECT =', PROJECT)
print('Files:', sorted([p.name for p in PROJECT.iterdir()])[:30])

Copying source folder: /kaggle/input/datasets/banhbaogachcua/nlp-melaycon/absa_clean_ablation_fresh
PROJECT = /kaggle/working/absa_clean_ablation_fresh
Files: ['CLEAN_START.md', 'KAGGLE_FRESH.md', 'PATCH_NOTES.md', 'README.md', 'absa_pipeline.py', 'dataset', 'docs', 'kaggle_ablation_fresh.ipynb', 'requirements.txt', 'run_ablation_core.sh', 'run_ablation_desc.sh', 'train.py', 'train_restaurant.sh', 'tune.py']

## 2. Cài đặt thư viện phụ thuộc

Bước này cài đặt các thư viện cần thiết được khai báo trong `requirements.txt`. Sau bước này, notebook có thể gọi trực tiếp các script huấn luyện và tuning của project.

In [3]:
os.chdir(PROJECT)
print('cwd =', Path.cwd())
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', 'pip'], check=True)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '-r', 'requirements.txt'], check=True)

cwd = /kaggle/working/absa_clean_ablation_fresh
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 23.2 MB/s eta 0:00:00

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.

CompletedProcess(args=['/usr/bin/python3', '-m', 'pip', 'install', '-q', '-r', 'requirements.txt'], returncode=0)

## 3. Xác minh trạng thái clean-start của package

Bước này kiểm tra package sau khi giải nén để xác nhận rằng mã nguồn không chứa checkpoint, thư mục kết quả, cache huấn luyện hoặc artifact lịch sử.

Đây là bước kiểm soát tính tái lập trước khi bắt đầu huấn luyện.

In [4]:
os.chdir(PROJECT)
forbidden_markers = ['tuning_', 'outputs_', 'wandb', 'runs', 'logs', '__pycache__']
forbidden_suffixes = {'.pt', '.pth', '.bin', '.safetensors'}
found = []
for p in PROJECT.rglob('*'):
    rel = str(p.relative_to(PROJECT))
    if any(part in rel for part in forbidden_markers) or p.suffix in forbidden_suffixes:
        found.append(rel)

print('Generated/history-like artifacts detected:', len(found))
for item in found[:50]:
    print('-', item)
assert not found, 'Clean-start validation failed: package contains output, checkpoint, cache, or history-like artifacts.'

print('\nDataset files:')
for p in sorted(Path('dataset/rest').glob('*')):
    print('-', p, p.stat().st_size)

print('\nSearch-space help:')
subprocess.run([sys.executable, 'tune.py', '--help'], check=False)

Generated/history-like artifacts detected: 0

Dataset files:
- dataset/rest/aspects.json 444731
- dataset/rest/test.multiple.json 1202702
- dataset/rest/train.multiple.json 4078526

Search-space help:
usage: tune.py [-h] [--dataset {lap,rest,twi}] [--model MODEL]
               [--epochs EPOCHS] [--final-epochs FINAL_EPOCHS]
               [--patience PATIENCE] [--batch-size BATCH_SIZE]
               [--gradient-accumulation-steps GRADIENT_ACCUMULATION_STEPS]
               [--weight-decay WEIGHT_DECAY] [--valid-ratio VALID_RATIO]
               [--split-seed SPLIT_SEED] [--tuning-seeds TUNING_SEEDS]
               [--validation-seed-pairs VALIDATION_SEED_PAIRS]
               [--final-seeds FINAL_SEEDS] [--output-dir OUTPUT_DIR]
               [--final-output-dir FINAL_OUTPUT_DIR] [--amp]
               [--gradient-checkpointing] [--run-final]
               [--keep-trial-checkpoints] [--resume]
               [--search-space {ablation_all,ablation_core,ablation_desc,initial,refined}]
               [--trials TRIALS]

Select ABSA hyperparameters using validation Macro-F1

options:
  -h, --help            show this help message and exit
  --dataset {lap,rest,twi}
  --model MODEL
  --epochs EPOCHS
  --final-epochs FINAL_EPOCHS
  --patience PATIENCE
  --batch-size BATCH_SIZE
  --gradient-accumulation-steps GRADIENT_ACCUMULATION_STEPS
  --weight-decay WEIGHT_DECAY
  --valid-ratio VALID_RATIO
  --split-seed SPLIT_SEED
  --tuning-seeds TUNING_SEEDS
  --validation-seed-pairs VALIDATION_SEED_PAIRS
                        Comma-separated split_seed:model_seed pairs.
  --final-seeds FINAL_SEEDS
  --output-dir OUTPUT_DIR
  --final-output-dir FINAL_OUTPUT_DIR
  --amp
  --gradient-checkpointing
  --run-final
  --keep-trial-checkpoints
  --resume
  --search-space {ablation_all,ablation_core,ablation_desc,initial,refined}
  --trials TRIALS       Comma-separated trial names or 'all'.

CompletedProcess(args=['/usr/bin/python3', 'tune.py', '--help'], returncode=0)

## 4. Huấn luyện core ablation từ đầu

Bước này chạy nhóm thí nghiệm chính (`ablation_core`) nhằm đánh giá riêng từng thay đổi quan trọng trong mô hình. Nhóm này **không sử dụng aspect description** để tránh gộp nhiều yếu tố trong cùng một trial.

Các trial chính:

- `baseline_cls`: cấu hình đối chứng dùng CLS pooling.
- `aspect_attention_term`: dùng aspect-aware attention trên input term.
- `hybrid_term`: kết hợp CLS representation và aspect-aware representation.
- `cls_neutral125`: tăng trọng số lớp neutral ở mức 1.25.
- `cls_neutral150`: tăng trọng số lớp neutral ở mức 1.50.
- `aspect_attention_neutral125`: kết hợp aspect-aware attention và neutral weighting mức 1.25.

Nếu GPU bị thiếu bộ nhớ, có thể giảm `BATCH_SIZE` xuống 4 và tăng `GRAD_ACCUM` lên 4 để giữ effective batch size gần tương đương.

In [5]:
os.chdir(PROJECT)

VALID_RATIO = 0.15
BATCH_SIZE = 8
GRAD_ACCUM = 2
EPOCHS = 12
FINAL_EPOCHS = 15
SEED_PAIRS = '2024:2024,42:42,3407:3407'
FINAL_SEEDS = '2024,42,3407'

cmd = [
    sys.executable, 'tune.py',
    '--dataset', 'rest',
    '--search-space', 'ablation_core',
    '--validation-seed-pairs', SEED_PAIRS,
    '--valid-ratio', str(VALID_RATIO),
    '--final-seeds', FINAL_SEEDS,
    '--epochs', str(EPOCHS),
    '--final-epochs', str(FINAL_EPOCHS),
    '--patience', '3',
    '--batch-size', str(BATCH_SIZE),
    '--gradient-accumulation-steps', str(GRAD_ACCUM),
    '--amp',
    '--gradient-checkpointing',
    '--run-final',
    '--output-dir', str(WORK / 'tuning_ablation_core'),
    '--final-output-dir', str(WORK / 'outputs_ablation_core'),
]
print(' '.join(cmd))
subprocess.run(cmd, check=True)

/usr/bin/python3 tune.py --dataset rest --search-space ablation_core --validation-seed-pairs 2024:2024,42:42,3407:3407 --valid-ratio 0.15 --final-seeds 2024,42,3407 --epochs 12 --final-epochs 15 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --amp --gradient-checkpointing --run-final --output-dir /kaggle/working/tuning_ablation_core --final-output-dir /kaggle/working/outputs_ablation_core
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_baseline_cls_split2024_seed2024 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 15:48:09.736778: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781970489.958742      63 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781970490.017481      63 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781970490.522587      63 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781970490.522641      63 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781970490.522647      63 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781970490.522653      63 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3070,
      "labels": {
        "negative": 686,
        "neutral": 542,
        "positive": 1842
      },
      "unique_aspects": 1069
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 537,
      "labels": {
        "negative": 121,
        "neutral": 95,
        "positive": 321
      },
      "unique_aspects": 281,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2551
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.0272 valid_loss=0.6833 valid_acc=0.7281 valid_f1=0.5234 lr=6.57e-06 time=70.2s eta=12.9m
saved best checkpoint: epoch=1 valid_f1=0.5234
epoch=2/12 train_loss=0.6278 valid_loss=0.6072 valid_acc=0.7561 valid_f1=0.6374 lr=7.42e-06 time=68.0s eta=11.3m
saved best checkpoint: epoch=2 valid_f1=0.6374
epoch=3/12 train_loss=0.5066 valid_loss=0.5662 valid_acc=0.7579 valid_f1=0.6586 lr=6.68e-06 time=67.8s eta=10.2m
saved best checkpoint: epoch=3 valid_f1=0.6586
epoch=4/12 train_loss=0.4016 valid_loss=0.5534 valid_acc=0.7896 valid_f1=0.6908 lr=5.94e-06 time=68.3s eta=9.1m
saved best checkpoint: epoch=4 valid_f1=0.6908
epoch=5/12 train_loss=0.3159 valid_loss=0.5882 valid_acc=0.8101 valid_f1=0.7481 lr=5.20e-06 time=67.7s eta=7.9m
saved best checkpoint: epoch=5 valid_f1=0.7481
epoch=6/12 train_loss=0.2535 valid_loss=0.6745 valid_acc=0.8101 valid_f1=0.7388 lr=4.46e-06 time=68.3s eta=6.8m
no improvement: 1/3
epoch=7/12 train_loss=0.2271 valid_loss=0.6751 valid_acc=0.8231 valid_f1=0.7615 lr=3.72e-06 time=69.7s eta=5.8m
saved best checkpoint: epoch=7 valid_f1=0.7615
epoch=8/12 train_loss=0.1945 valid_loss=0.7285 valid_acc=0.7989 valid_f1=0.7323 lr=2.98e-06 time=69.0s eta=4.6m
no improvement: 1/3
epoch=9/12 train_loss=0.1735 valid_loss=0.7387 valid_acc=0.8045 valid_f1=0.7389 lr=2.24e-06 time=68.4s eta=3.4m
no improvement: 2/3
epoch=10/12 train_loss=0.1524 valid_loss=0.7945 valid_acc=0.8101 valid_f1=0.7355 lr=1.50e-06 time=68.2s eta=2.3m
no improvement: 3/3
early stopping at epoch 10; best epoch was 7
calibration_temperature=1.877222
{
  "validation": {
    "accuracy": 0.8231,
    "precision_macro": 0.7604,
    "recall_macro": 0.7626,
    "macro_f1": 0.7615,
    "weighted_f1": 0.8234,
    "roc_auc_macro": 0.9133,
    "average_confidence": 0.8328,
    "expected_calibration_error": 0.0523,
    "temperature": 1.877222,
    "uncalibrated_confidence": 0.9341,
    "seen": {
      "samples": 400,
      "accuracy": 0.8125,
      "macro_f1": 0.7585
    },
    "unseen": {
      "samples": 137,
      "accuracy": 0.854,
      "macro_f1": 0.768
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_baseline_cls_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_baseline_cls_split42_seed42 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 16:02:06.238612: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781971326.256388     107 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781971326.262567     107 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781971326.278045     107 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781971326.278066     107 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781971326.278068     107 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781971326.278070     107 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3066,
      "labels": {
        "negative": 684,
        "neutral": 540,
        "positive": 1842
      },
      "unique_aspects": 1066
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 541,
      "labels": {
        "negative": 123,
        "neutral": 97,
        "positive": 321
      },
      "unique_aspects": 273,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2532
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 364,
      "unseen_aspect_ratio": 0.325
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=0.9616 valid_loss=0.7381 valid_acc=0.7098 valid_f1=0.4979 lr=6.61e-06 time=70.0s eta=12.8m
saved best checkpoint: epoch=1 valid_f1=0.4979
epoch=2/12 train_loss=0.6246 valid_loss=0.7561 valid_acc=0.7320 valid_f1=0.5985 lr=7.41e-06 time=69.3s eta=11.6m
saved best checkpoint: epoch=2 valid_f1=0.5985
epoch=3/12 train_loss=0.5101 valid_loss=0.7006 valid_acc=0.7153 valid_f1=0.6273 lr=6.67e-06 time=68.2s eta=10.2m
saved best checkpoint: epoch=3 valid_f1=0.6273
epoch=4/12 train_loss=0.4384 valid_loss=0.6813 valid_acc=0.7634 valid_f1=0.6707 lr=5.93e-06 time=68.8s eta=9.2m
saved best checkpoint: epoch=4 valid_f1=0.6707
epoch=5/12 train_loss=0.3522 valid_loss=0.7771 valid_acc=0.7782 valid_f1=0.6656 lr=5.19e-06 time=68.6s eta=8.0m
no improvement: 1/3
epoch=6/12 train_loss=0.2900 valid_loss=0.7794 valid_acc=0.7745 valid_f1=0.6812 lr=4.45e-06 time=67.9s eta=6.8m
saved best checkpoint: epoch=6 valid_f1=0.6812
epoch=7/12 train_loss=0.2594 valid_loss=0.8011 valid_acc=0.7782 valid_f1=0.6786 lr=3.71e-06 time=68.7s eta=5.7m
no improvement: 1/3
epoch=8/12 train_loss=0.2077 valid_loss=0.8623 valid_acc=0.7782 valid_f1=0.6976 lr=2.97e-06 time=68.3s eta=4.6m
saved best checkpoint: epoch=8 valid_f1=0.6976
epoch=9/12 train_loss=0.1907 valid_loss=0.9135 valid_acc=0.7782 valid_f1=0.6944 lr=2.23e-06 time=68.7s eta=3.4m
no improvement: 1/3
epoch=10/12 train_loss=0.1722 valid_loss=0.9333 valid_acc=0.7800 valid_f1=0.6954 lr=1.49e-06 time=67.7s eta=2.3m
no improvement: 2/3
epoch=11/12 train_loss=0.1656 valid_loss=0.9453 valid_acc=0.7874 valid_f1=0.7045 lr=7.52e-07 time=67.6s eta=1.1m
saved best checkpoint: epoch=11 valid_f1=0.7045
epoch=12/12 train_loss=0.1519 valid_loss=0.9530 valid_acc=0.7874 valid_f1=0.7050 lr=1.16e-08 time=68.4s eta=0.0m
no improvement: 1/3
calibration_temperature=2.318818
{
  "validation": {
    "accuracy": 0.7874,
    "precision_macro": 0.7077,
    "recall_macro": 0.7031,
    "macro_f1": 0.7045,
    "weighted_f1": 0.7843,
    "roc_auc_macro": 0.8769,
    "average_confidence": 0.8022,
    "expected_calibration_error": 0.047,
    "temperature": 2.318818,
    "uncalibrated_confidence": 0.9556,
    "seen": {
      "samples": 404,
      "accuracy": 0.7772,
      "macro_f1": 0.7047
    },
    "unseen": {
      "samples": 137,
      "accuracy": 0.8175,
      "macro_f1": 0.6992
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_baseline_cls_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_baseline_cls_split3407_seed3407 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 16:18:04.992210: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781972285.010181     134 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781972285.016127     134 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781972285.031688     134 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781972285.031712     134 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781972285.031714     134 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781972285.031717     134 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3068,
      "labels": {
        "negative": 685,
        "neutral": 542,
        "positive": 1841
      },
      "unique_aspects": 1074
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 132,
      "unseen_aspect_ratio": 0.0366
    },
    "valid": {
      "samples": 539,
      "labels": {
        "negative": 122,
        "neutral": 95,
        "positive": 322
      },
      "unique_aspects": 267,
      "unseen_aspect_samples": 132,
      "unseen_aspect_ratio": 0.2449
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 368,
      "unseen_aspect_ratio": 0.3286
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.0477 valid_loss=0.6863 valid_acc=0.7458 valid_f1=0.5180 lr=6.57e-06 time=69.0s eta=12.6m
saved best checkpoint: epoch=1 valid_f1=0.5180
epoch=2/12 train_loss=0.6359 valid_loss=0.5751 valid_acc=0.7829 valid_f1=0.6642 lr=7.42e-06 time=68.3s eta=11.4m
saved best checkpoint: epoch=2 valid_f1=0.6642
epoch=3/12 train_loss=0.4897 valid_loss=0.5434 valid_acc=0.8033 valid_f1=0.7207 lr=6.68e-06 time=68.6s eta=10.3m
saved best checkpoint: epoch=3 valid_f1=0.7207
epoch=4/12 train_loss=0.3907 valid_loss=0.5268 valid_acc=0.8108 valid_f1=0.7435 lr=5.94e-06 time=68.5s eta=9.1m
saved best checkpoint: epoch=4 valid_f1=0.7435
epoch=5/12 train_loss=0.3085 valid_loss=0.5439 valid_acc=0.8237 valid_f1=0.7619 lr=5.20e-06 time=68.5s eta=8.0m
saved best checkpoint: epoch=5 valid_f1=0.7619
epoch=6/12 train_loss=0.2615 valid_loss=0.5717 valid_acc=0.8182 valid_f1=0.7437 lr=4.46e-06 time=69.0s eta=6.9m
no improvement: 1/3
epoch=7/12 train_loss=0.2221 valid_loss=0.6084 valid_acc=0.8312 valid_f1=0.7689 lr=3.71e-06 time=68.3s eta=5.7m
saved best checkpoint: epoch=7 valid_f1=0.7689
epoch=8/12 train_loss=0.1920 valid_loss=0.6440 valid_acc=0.8349 valid_f1=0.7873 lr=2.97e-06 time=67.8s eta=4.5m
saved best checkpoint: epoch=8 valid_f1=0.7873
epoch=9/12 train_loss=0.1656 valid_loss=0.6184 valid_acc=0.8460 valid_f1=0.7933 lr=2.23e-06 time=68.8s eta=3.4m
saved best checkpoint: epoch=9 valid_f1=0.7933
epoch=10/12 train_loss=0.1542 valid_loss=0.6545 valid_acc=0.8349 valid_f1=0.7754 lr=1.49e-06 time=68.5s eta=2.3m
no improvement: 1/3
epoch=11/12 train_loss=0.1495 valid_loss=0.6662 valid_acc=0.8367 valid_f1=0.7670 lr=7.52e-07 time=68.5s eta=1.1m
no improvement: 2/3
epoch=12/12 train_loss=0.1344 valid_loss=0.6682 valid_acc=0.8423 valid_f1=0.7768 lr=1.16e-08 time=67.3s eta=0.0m
no improvement: 3/3
early stopping at epoch 12; best epoch was 9
calibration_temperature=1.808044
{
  "validation": {
    "accuracy": 0.846,
    "precision_macro": 0.7893,
    "recall_macro": 0.7982,
    "macro_f1": 0.7933,
    "weighted_f1": 0.8479,
    "roc_auc_macro": 0.9293,
    "average_confidence": 0.8463,
    "expected_calibration_error": 0.0472,
    "temperature": 1.808044,
    "uncalibrated_confidence": 0.9326,
    "seen": {
      "samples": 407,
      "accuracy": 0.8649,
      "macro_f1": 0.8197
    },
    "unseen": {
      "samples": 132,
      "accuracy": 0.7879,
      "macro_f1": 0.698
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_baseline_cls_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_aspect_attention_term_split2024_seed2024 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 16:34:04.410494: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781973244.430115     161 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781973244.436618     161 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781973244.454259     161 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781973244.454282     161 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781973244.454285     161 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781973244.454288     161 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3070,
      "labels": {
        "negative": 686,
        "neutral": 542,
        "positive": 1842
      },
      "unique_aspects": 1069
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 537,
      "labels": {
        "negative": 121,
        "neutral": 95,
        "positive": 321
      },
      "unique_aspects": 281,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2551
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=0.9966 valid_loss=0.6954 valid_acc=0.7114 valid_f1=0.5686 lr=6.61e-06 time=71.4s eta=13.1m
saved best checkpoint: epoch=1 valid_f1=0.5686
epoch=2/12 train_loss=0.6007 valid_loss=0.4991 valid_acc=0.8156 valid_f1=0.7454 lr=7.41e-06 time=70.2s eta=11.7m
saved best checkpoint: epoch=2 valid_f1=0.7454
epoch=3/12 train_loss=0.4301 valid_loss=0.5019 valid_acc=0.8194 valid_f1=0.7496 lr=6.67e-06 time=70.0s eta=10.5m
saved best checkpoint: epoch=3 valid_f1=0.7496
epoch=4/12 train_loss=0.3186 valid_loss=0.5474 valid_acc=0.8231 valid_f1=0.7481 lr=5.93e-06 time=70.0s eta=9.3m
no improvement: 1/3
epoch=5/12 train_loss=0.2377 valid_loss=0.6099 valid_acc=0.8268 valid_f1=0.7483 lr=5.19e-06 time=69.2s eta=8.1m
no improvement: 2/3
epoch=6/12 train_loss=0.1992 valid_loss=0.6962 valid_acc=0.8250 valid_f1=0.7378 lr=4.45e-06 time=69.5s eta=7.0m
no improvement: 3/3
early stopping at epoch 6; best epoch was 3
calibration_temperature=1.266695
{
  "validation": {
    "accuracy": 0.8194,
    "precision_macro": 0.7486,
    "recall_macro": 0.7507,
    "macro_f1": 0.7496,
    "weighted_f1": 0.82,
    "roc_auc_macro": 0.9304,
    "average_confidence": 0.8269,
    "expected_calibration_error": 0.0276,
    "temperature": 1.266695,
    "uncalibrated_confidence": 0.865,
    "seen": {
      "samples": 400,
      "accuracy": 0.8,
      "macro_f1": 0.7292
    },
    "unseen": {
      "samples": 137,
      "accuracy": 0.8759,
      "macro_f1": 0.8179
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_aspect_attention_term_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_aspect_attention_term_split42_seed42 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 16:43:17.899276: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781973797.918059     188 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781973797.924295     188 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781973797.940151     188 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781973797.940195     188 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781973797.940201     188 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781973797.940205     188 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3066,
      "labels": {
        "negative": 684,
        "neutral": 540,
        "positive": 1842
      },
      "unique_aspects": 1066
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 541,
      "labels": {
        "negative": 123,
        "neutral": 97,
        "positive": 321
      },
      "unique_aspects": 273,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2532
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 364,
      "unseen_aspect_ratio": 0.325
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=0.9664 valid_loss=0.7286 valid_acc=0.6969 valid_f1=0.5109 lr=6.64e-06 time=72.0s eta=13.2m
saved best checkpoint: epoch=1 valid_f1=0.5109
epoch=2/12 train_loss=0.6234 valid_loss=0.6254 valid_acc=0.7745 valid_f1=0.6700 lr=7.41e-06 time=71.6s eta=11.9m
saved best checkpoint: epoch=2 valid_f1=0.6700
epoch=3/12 train_loss=0.4416 valid_loss=0.6029 valid_acc=0.7782 valid_f1=0.7123 lr=6.67e-06 time=71.2s eta=10.7m
saved best checkpoint: epoch=3 valid_f1=0.7123
epoch=4/12 train_loss=0.3524 valid_loss=0.6359 valid_acc=0.8059 valid_f1=0.7216 lr=5.93e-06 time=70.9s eta=9.5m
saved best checkpoint: epoch=4 valid_f1=0.7216
epoch=5/12 train_loss=0.2690 valid_loss=0.6566 valid_acc=0.8078 valid_f1=0.7349 lr=5.19e-06 time=70.6s eta=8.2m
saved best checkpoint: epoch=5 valid_f1=0.7349
epoch=6/12 train_loss=0.2118 valid_loss=0.7134 valid_acc=0.8004 valid_f1=0.7321 lr=4.45e-06 time=70.2s eta=7.0m
no improvement: 1/3
epoch=7/12 train_loss=0.1655 valid_loss=0.7348 valid_acc=0.8207 valid_f1=0.7510 lr=3.71e-06 time=70.6s eta=5.9m
saved best checkpoint: epoch=7 valid_f1=0.7510
epoch=8/12 train_loss=0.1532 valid_loss=0.7716 valid_acc=0.8170 valid_f1=0.7528 lr=2.97e-06 time=70.1s eta=4.7m
no improvement: 1/3
epoch=9/12 train_loss=0.1352 valid_loss=0.7907 valid_acc=0.8244 valid_f1=0.7636 lr=2.23e-06 time=70.5s eta=3.5m
saved best checkpoint: epoch=9 valid_f1=0.7636
epoch=10/12 train_loss=0.1228 valid_loss=0.8074 valid_acc=0.8207 valid_f1=0.7604 lr=1.49e-06 time=69.9s eta=2.3m
no improvement: 1/3
epoch=11/12 train_loss=0.1069 valid_loss=0.8111 valid_acc=0.8170 valid_f1=0.7499 lr=7.48e-07 time=69.2s eta=1.2m
no improvement: 2/3
epoch=12/12 train_loss=0.1087 valid_loss=0.8088 valid_acc=0.8152 valid_f1=0.7470 lr=7.71e-09 time=69.4s eta=0.0m
no improvement: 3/3
early stopping at epoch 12; best epoch was 9
calibration_temperature=2.062198
{
  "validation": {
    "accuracy": 0.8244,
    "precision_macro": 0.7671,
    "recall_macro": 0.761,
    "macro_f1": 0.7636,
    "weighted_f1": 0.8228,
    "roc_auc_macro": 0.8959,
    "average_confidence": 0.8274,
    "expected_calibration_error": 0.0383,
    "temperature": 2.062198,
    "uncalibrated_confidence": 0.9532,
    "seen": {
      "samples": 404,
      "accuracy": 0.8168,
      "macro_f1": 0.7691
    },
    "unseen": {
      "samples": 137,
      "accuracy": 0.8467,
      "macro_f1": 0.7349
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_aspect_attention_term_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_aspect_attention_term_split3407_seed3407 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 16:59:40.275615: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781974780.293850     215 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781974780.299897     215 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781974780.315892     215 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781974780.315912     215 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781974780.315915     215 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781974780.315917     215 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3068,
      "labels": {
        "negative": 685,
        "neutral": 542,
        "positive": 1841
      },
      "unique_aspects": 1074
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 132,
      "unseen_aspect_ratio": 0.0366
    },
    "valid": {
      "samples": 539,
      "labels": {
        "negative": 122,
        "neutral": 95,
        "positive": 322
      },
      "unique_aspects": 267,
      "unseen_aspect_samples": 132,
      "unseen_aspect_ratio": 0.2449
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 368,
      "unseen_aspect_ratio": 0.3286
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=0.9591 valid_loss=0.6171 valid_acc=0.7458 valid_f1=0.5485 lr=6.64e-06 time=70.0s eta=12.8m
saved best checkpoint: epoch=1 valid_f1=0.5485
epoch=2/12 train_loss=0.5966 valid_loss=0.5238 valid_acc=0.8033 valid_f1=0.6912 lr=7.41e-06 time=69.5s eta=11.6m
saved best checkpoint: epoch=2 valid_f1=0.6912
epoch=3/12 train_loss=0.4262 valid_loss=0.5288 valid_acc=0.7978 valid_f1=0.7012 lr=6.67e-06 time=69.2s eta=10.4m
saved best checkpoint: epoch=3 valid_f1=0.7012
epoch=4/12 train_loss=0.3372 valid_loss=0.5547 valid_acc=0.8126 valid_f1=0.7363 lr=5.93e-06 time=69.6s eta=9.3m
saved best checkpoint: epoch=4 valid_f1=0.7363
epoch=5/12 train_loss=0.2612 valid_loss=0.5522 valid_acc=0.8293 valid_f1=0.7585 lr=5.19e-06 time=69.3s eta=8.1m
saved best checkpoint: epoch=5 valid_f1=0.7585
epoch=6/12 train_loss=0.2126 valid_loss=0.5945 valid_acc=0.8330 valid_f1=0.7769 lr=4.45e-06 time=70.2s eta=7.0m
saved best checkpoint: epoch=6 valid_f1=0.7769
epoch=7/12 train_loss=0.1751 valid_loss=0.6345 valid_acc=0.8312 valid_f1=0.7759 lr=3.71e-06 time=70.9s eta=5.9m
no improvement: 1/3
epoch=8/12 train_loss=0.1514 valid_loss=0.6865 valid_acc=0.8256 valid_f1=0.7601 lr=2.97e-06 time=68.6s eta=4.6m
no improvement: 2/3
epoch=9/12 train_loss=0.1324 valid_loss=0.7066 valid_acc=0.8330 valid_f1=0.7781 lr=2.23e-06 time=69.9s eta=3.5m
no improvement: 3/3
early stopping at epoch 9; best epoch was 6
calibration_temperature=1.678522
{
  "validation": {
    "accuracy": 0.833,
    "precision_macro": 0.7834,
    "recall_macro": 0.7775,
    "macro_f1": 0.7769,
    "weighted_f1": 0.8369,
    "roc_auc_macro": 0.9337,
    "average_confidence": 0.841,
    "expected_calibration_error": 0.0394,
    "temperature": 1.678522,
    "uncalibrated_confidence": 0.9232,
    "seen": {
      "samples": 407,
      "accuracy": 0.8477,
      "macro_f1": 0.8009
    },
    "unseen": {
      "samples": 132,
      "accuracy": 0.7879,
      "macro_f1": 0.6814
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_aspect_attention_term_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_hybrid_term_split2024_seed2024 --evaluation-split validation --pooling-strategy hybrid --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 17:12:23.115427: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781975543.133762     242 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781975543.139885     242 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781975543.158957     242 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781975543.158977     242 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781975543.158979     242 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781975543.158981     242 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3070,
      "labels": {
        "negative": 686,
        "neutral": 542,
        "positive": 1842
      },
      "unique_aspects": 1069
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 537,
      "labels": {
        "negative": 121,
        "neutral": 95,
        "positive": 321
      },
      "unique_aspects": 281,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2551
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=0.9812 valid_loss=0.6930 valid_acc=0.6946 valid_f1=0.4791 lr=6.61e-06 time=70.1s eta=12.8m
saved best checkpoint: epoch=1 valid_f1=0.4791
epoch=2/12 train_loss=0.5922 valid_loss=0.5116 valid_acc=0.7914 valid_f1=0.7184 lr=7.41e-06 time=69.3s eta=11.6m
saved best checkpoint: epoch=2 valid_f1=0.7184
epoch=3/12 train_loss=0.4213 valid_loss=0.5506 valid_acc=0.8026 valid_f1=0.7214 lr=6.67e-06 time=68.6s eta=10.3m
saved best checkpoint: epoch=3 valid_f1=0.7214
epoch=4/12 train_loss=0.3093 valid_loss=0.5993 valid_acc=0.8045 valid_f1=0.7215 lr=5.93e-06 time=68.7s eta=9.2m
no improvement: 1/3
epoch=5/12 train_loss=0.2452 valid_loss=0.6631 valid_acc=0.8119 valid_f1=0.7406 lr=5.19e-06 time=68.1s eta=7.9m
saved best checkpoint: epoch=5 valid_f1=0.7406
epoch=6/12 train_loss=0.1927 valid_loss=0.6752 valid_acc=0.8138 valid_f1=0.7516 lr=4.45e-06 time=67.8s eta=6.8m
saved best checkpoint: epoch=6 valid_f1=0.7516
epoch=7/12 train_loss=0.1604 valid_loss=0.7084 valid_acc=0.8138 valid_f1=0.7371 lr=3.71e-06 time=68.5s eta=5.7m
no improvement: 1/3
epoch=8/12 train_loss=0.1366 valid_loss=0.7483 valid_acc=0.8156 valid_f1=0.7428 lr=2.97e-06 time=71.8s eta=4.8m
no improvement: 2/3
epoch=9/12 train_loss=0.1214 valid_loss=0.7414 valid_acc=0.8156 valid_f1=0.7351 lr=2.23e-06 time=70.1s eta=3.5m
no improvement: 3/3
early stopping at epoch 9; best epoch was 6
calibration_temperature=1.842826
{
  "validation": {
    "accuracy": 0.8138,
    "precision_macro": 0.7471,
    "recall_macro": 0.7567,
    "macro_f1": 0.7516,
    "weighted_f1": 0.8161,
    "roc_auc_macro": 0.9199,
    "average_confidence": 0.8263,
    "expected_calibration_error": 0.0484,
    "temperature": 1.842826,
    "uncalibrated_confidence": 0.9262,
    "seen": {
      "samples": 400,
      "accuracy": 0.8175,
      "macro_f1": 0.7648
    },
    "unseen": {
      "samples": 137,
      "accuracy": 0.8029,
      "macro_f1": 0.7022
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_hybrid_term_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_hybrid_term_split42_seed42 --evaluation-split validation --pooling-strategy hybrid --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 17:25:00.004591: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781976300.022680     269 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781976300.028678     269 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781976300.044556     269 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781976300.044601     269 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781976300.044607     269 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781976300.044611     269 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3066,
      "labels": {
        "negative": 684,
        "neutral": 540,
        "positive": 1842
      },
      "unique_aspects": 1066
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 541,
      "labels": {
        "negative": 123,
        "neutral": 97,
        "positive": 321
      },
      "unique_aspects": 273,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2532
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 364,
      "unseen_aspect_ratio": 0.325
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=0.9916 valid_loss=0.6746 valid_acc=0.7283 valid_f1=0.5299 lr=6.61e-06 time=70.6s eta=12.9m
saved best checkpoint: epoch=1 valid_f1=0.5299
epoch=2/12 train_loss=0.5934 valid_loss=0.6388 valid_acc=0.7745 valid_f1=0.6624 lr=7.41e-06 time=70.2s eta=11.7m
saved best checkpoint: epoch=2 valid_f1=0.6624
epoch=3/12 train_loss=0.4190 valid_loss=0.6221 valid_acc=0.7948 valid_f1=0.7100 lr=6.67e-06 time=69.6s eta=10.4m
saved best checkpoint: epoch=3 valid_f1=0.7100
epoch=4/12 train_loss=0.3198 valid_loss=0.6560 valid_acc=0.7930 valid_f1=0.6965 lr=5.93e-06 time=69.3s eta=9.2m
no improvement: 1/3
epoch=5/12 train_loss=0.2379 valid_loss=0.6898 valid_acc=0.7967 valid_f1=0.7259 lr=5.19e-06 time=68.3s eta=8.0m
saved best checkpoint: epoch=5 valid_f1=0.7259
epoch=6/12 train_loss=0.1886 valid_loss=0.7947 valid_acc=0.8041 valid_f1=0.7293 lr=4.45e-06 time=68.8s eta=6.9m
saved best checkpoint: epoch=6 valid_f1=0.7293
epoch=7/12 train_loss=0.1523 valid_loss=0.7878 valid_acc=0.8207 valid_f1=0.7561 lr=3.71e-06 time=69.1s eta=5.8m
saved best checkpoint: epoch=7 valid_f1=0.7561
epoch=8/12 train_loss=0.1375 valid_loss=0.8788 valid_acc=0.7985 valid_f1=0.7104 lr=2.97e-06 time=68.9s eta=4.6m
no improvement: 1/3
epoch=9/12 train_loss=0.1257 valid_loss=0.8259 valid_acc=0.8133 valid_f1=0.7386 lr=2.23e-06 time=69.5s eta=3.5m
no improvement: 2/3
epoch=10/12 train_loss=0.1226 valid_loss=0.8547 valid_acc=0.8133 valid_f1=0.7423 lr=1.49e-06 time=68.9s eta=2.3m
no improvement: 3/3
early stopping at epoch 10; best epoch was 7
calibration_temperature=2.046243
{
  "validation": {
    "accuracy": 0.8207,
    "precision_macro": 0.7599,
    "recall_macro": 0.7534,
    "macro_f1": 0.7561,
    "weighted_f1": 0.8186,
    "roc_auc_macro": 0.9014,
    "average_confidence": 0.8163,
    "expected_calibration_error": 0.0518,
    "temperature": 2.046243,
    "uncalibrated_confidence": 0.9407,
    "seen": {
      "samples": 404,
      "accuracy": 0.8218,
      "macro_f1": 0.7715
    },
    "unseen": {
      "samples": 137,
      "accuracy": 0.8175,
      "macro_f1": 0.6895
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_hybrid_term_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_hybrid_term_split3407_seed3407 --evaluation-split validation --pooling-strategy hybrid --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 17:38:48.650526: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781977128.669293     296 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781977128.675385     296 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781977128.691532     296 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781977128.691555     296 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781977128.691558     296 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781977128.691560     296 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3068,
      "labels": {
        "negative": 685,
        "neutral": 542,
        "positive": 1841
      },
      "unique_aspects": 1074
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 132,
      "unseen_aspect_ratio": 0.0366
    },
    "valid": {
      "samples": 539,
      "labels": {
        "negative": 122,
        "neutral": 95,
        "positive": 322
      },
      "unique_aspects": 267,
      "unseen_aspect_samples": 132,
      "unseen_aspect_ratio": 0.2449
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 368,
      "unseen_aspect_ratio": 0.3286
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=0.9823 valid_loss=0.6184 valid_acc=0.7477 valid_f1=0.5225 lr=6.61e-06 time=70.0s eta=12.8m
saved best checkpoint: epoch=1 valid_f1=0.5225
epoch=2/12 train_loss=0.5900 valid_loss=0.4958 valid_acc=0.8033 valid_f1=0.7104 lr=7.41e-06 time=70.8s eta=11.8m
saved best checkpoint: epoch=2 valid_f1=0.7104
epoch=3/12 train_loss=0.3972 valid_loss=0.5453 valid_acc=0.8312 valid_f1=0.7672 lr=6.67e-06 time=70.2s eta=10.5m
saved best checkpoint: epoch=3 valid_f1=0.7672
epoch=4/12 train_loss=0.3116 valid_loss=0.6635 valid_acc=0.8015 valid_f1=0.6775 lr=5.93e-06 time=71.0s eta=9.5m
no improvement: 1/3
epoch=5/12 train_loss=0.2509 valid_loss=0.6019 valid_acc=0.8200 valid_f1=0.7410 lr=5.19e-06 time=70.7s eta=8.2m
no improvement: 2/3
epoch=6/12 train_loss=0.1939 valid_loss=0.6939 valid_acc=0.8293 valid_f1=0.7418 lr=4.45e-06 time=70.7s eta=7.1m
no improvement: 3/3
early stopping at epoch 6; best epoch was 3
calibration_temperature=1.422587
{
  "validation": {
    "accuracy": 0.8312,
    "precision_macro": 0.7657,
    "recall_macro": 0.7791,
    "macro_f1": 0.7672,
    "weighted_f1": 0.8304,
    "roc_auc_macro": 0.9315,
    "average_confidence": 0.8308,
    "expected_calibration_error": 0.0454,
    "temperature": 1.422587,
    "uncalibrated_confidence": 0.889,
    "seen": {
      "samples": 407,
      "accuracy": 0.8354,
      "macro_f1": 0.7749
    },
    "unseen": {
      "samples": 132,
      "accuracy": 0.8182,
      "macro_f1": 0.7368
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_hybrid_term_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_cls_neutral125_split2024_seed2024 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 17:48:05.173109: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781977685.193038     323 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781977685.198976     323 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781977685.215184     323 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781977685.215226     323 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781977685.215232     323 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781977685.215235     323 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3070,
      "labels": {
        "negative": 686,
        "neutral": 542,
        "positive": 1842
      },
      "unique_aspects": 1069
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 537,
      "labels": {
        "negative": 121,
        "neutral": 95,
        "positive": 321
      },
      "unique_aspects": 281,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2551
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=1.0102 valid_loss=0.6979 valid_acc=0.7430 valid_f1=0.6164 lr=6.57e-06 time=70.1s eta=12.9m
saved best checkpoint: epoch=1 valid_f1=0.6164
epoch=2/12 train_loss=0.6371 valid_loss=0.6027 valid_acc=0.7579 valid_f1=0.6695 lr=7.42e-06 time=69.2s eta=11.5m
saved best checkpoint: epoch=2 valid_f1=0.6695
epoch=3/12 train_loss=0.5113 valid_loss=0.5861 valid_acc=0.7654 valid_f1=0.6697 lr=6.68e-06 time=68.3s eta=10.2m
no improvement: 1/3
epoch=4/12 train_loss=0.3980 valid_loss=0.5950 valid_acc=0.7970 valid_f1=0.6987 lr=5.94e-06 time=68.6s eta=9.1m
saved best checkpoint: epoch=4 valid_f1=0.6987
epoch=5/12 train_loss=0.3133 valid_loss=0.6061 valid_acc=0.8156 valid_f1=0.7517 lr=5.20e-06 time=68.5s eta=8.0m
saved best checkpoint: epoch=5 valid_f1=0.7517
epoch=6/12 train_loss=0.2483 valid_loss=0.6997 valid_acc=0.8045 valid_f1=0.7364 lr=4.46e-06 time=70.3s eta=7.0m
no improvement: 1/3
epoch=7/12 train_loss=0.2223 valid_loss=0.7089 valid_acc=0.8194 valid_f1=0.7556 lr=3.71e-06 time=69.2s eta=5.8m
saved best checkpoint: epoch=7 valid_f1=0.7556
epoch=8/12 train_loss=0.1897 valid_loss=0.7589 valid_acc=0.8007 valid_f1=0.7342 lr=2.97e-06 time=68.1s eta=4.5m
no improvement: 1/3
epoch=9/12 train_loss=0.1701 valid_loss=0.7630 valid_acc=0.8101 valid_f1=0.7488 lr=2.23e-06 time=67.7s eta=3.4m
no improvement: 2/3
epoch=10/12 train_loss=0.1507 valid_loss=0.8126 valid_acc=0.8119 valid_f1=0.7448 lr=1.49e-06 time=69.9s eta=2.3m
no improvement: 3/3
early stopping at epoch 10; best epoch was 7
calibration_temperature=1.924390
{
  "validation": {
    "accuracy": 0.8194,
    "precision_macro": 0.7527,
    "recall_macro": 0.7588,
    "macro_f1": 0.7556,
    "weighted_f1": 0.8204,
    "roc_auc_macro": 0.9093,
    "average_confidence": 0.8307,
    "expected_calibration_error": 0.0466,
    "temperature": 1.92439,
    "uncalibrated_confidence": 0.936,
    "seen": {
      "samples": 400,
      "accuracy": 0.81,
      "macro_f1": 0.7562
    },
    "unseen": {
      "samples": 137,
      "accuracy": 0.8467,
      "macro_f1": 0.7482
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_cls_neutral125_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_cls_neutral125_split42_seed42 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 18:01:48.352899: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781978508.371698     350 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781978508.377998     350 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781978508.393702     350 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781978508.393744     350 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781978508.393750     350 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781978508.393754     350 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3066,
      "labels": {
        "negative": 684,
        "neutral": 540,
        "positive": 1842
      },
      "unique_aspects": 1066
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 541,
      "labels": {
        "negative": 123,
        "neutral": 97,
        "positive": 321
      },
      "unique_aspects": 273,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2532
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 364,
      "unseen_aspect_ratio": 0.325
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=0.9414 valid_loss=0.7424 valid_acc=0.7394 valid_f1=0.5883 lr=6.61e-06 time=69.7s eta=12.8m
saved best checkpoint: epoch=1 valid_f1=0.5883
epoch=2/12 train_loss=0.6266 valid_loss=0.7340 valid_acc=0.7375 valid_f1=0.6209 lr=7.41e-06 time=69.4s eta=11.6m
saved best checkpoint: epoch=2 valid_f1=0.6209
epoch=3/12 train_loss=0.5127 valid_loss=0.7098 valid_acc=0.7153 valid_f1=0.6244 lr=6.67e-06 time=68.4s eta=10.3m
saved best checkpoint: epoch=3 valid_f1=0.6244
epoch=4/12 train_loss=0.4357 valid_loss=0.6894 valid_acc=0.7468 valid_f1=0.6613 lr=5.93e-06 time=68.3s eta=9.1m
saved best checkpoint: epoch=4 valid_f1=0.6613
epoch=5/12 train_loss=0.3512 valid_loss=0.8155 valid_acc=0.7671 valid_f1=0.6578 lr=5.19e-06 time=68.0s eta=7.9m
no improvement: 1/3
epoch=6/12 train_loss=0.2936 valid_loss=0.7866 valid_acc=0.7708 valid_f1=0.6835 lr=4.45e-06 time=67.4s eta=6.7m
saved best checkpoint: epoch=6 valid_f1=0.6835
epoch=7/12 train_loss=0.2583 valid_loss=0.8233 valid_acc=0.7856 valid_f1=0.6959 lr=3.71e-06 time=68.4s eta=5.7m
saved best checkpoint: epoch=7 valid_f1=0.6959
epoch=8/12 train_loss=0.2020 valid_loss=0.9229 valid_acc=0.7763 valid_f1=0.6894 lr=2.97e-06 time=68.2s eta=4.5m
no improvement: 1/3
epoch=9/12 train_loss=0.1959 valid_loss=0.9481 valid_acc=0.7763 valid_f1=0.6918 lr=2.23e-06 time=67.7s eta=3.4m
no improvement: 2/3
epoch=10/12 train_loss=0.1733 valid_loss=0.9657 valid_acc=0.7874 valid_f1=0.7063 lr=1.49e-06 time=68.5s eta=2.3m
saved best checkpoint: epoch=10 valid_f1=0.7063
epoch=11/12 train_loss=0.1618 valid_loss=0.9717 valid_acc=0.7930 valid_f1=0.7128 lr=7.52e-07 time=68.8s eta=1.1m
saved best checkpoint: epoch=11 valid_f1=0.7128
epoch=12/12 train_loss=0.1512 valid_loss=0.9846 valid_acc=0.7948 valid_f1=0.7154 lr=1.16e-08 time=69.1s eta=0.0m
saved best checkpoint: epoch=12 valid_f1=0.7154
calibration_temperature=2.315651
{
  "validation": {
    "accuracy": 0.7948,
    "precision_macro": 0.7204,
    "recall_macro": 0.713,
    "macro_f1": 0.7154,
    "weighted_f1": 0.7911,
    "roc_auc_macro": 0.8716,
    "average_confidence": 0.8004,
    "expected_calibration_error": 0.0344,
    "temperature": 2.315651,
    "uncalibrated_confidence": 0.9583,
    "seen": {
      "samples": 404,
      "accuracy": 0.7896,
      "macro_f1": 0.7232
    },
    "unseen": {
      "samples": 137,
      "accuracy": 0.8102,
      "macro_f1": 0.6809
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_cls_neutral125_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_cls_neutral125_split3407_seed3407 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 18:17:49.413404: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781979469.431534     377 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781979469.437524     377 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781979469.453267     377 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781979469.453315     377 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781979469.453321     377 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781979469.453326     377 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3068,
      "labels": {
        "negative": 685,
        "neutral": 542,
        "positive": 1841
      },
      "unique_aspects": 1074
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 132,
      "unseen_aspect_ratio": 0.0366
    },
    "valid": {
      "samples": 539,
      "labels": {
        "negative": 122,
        "neutral": 95,
        "positive": 322
      },
      "unique_aspects": 267,
      "unseen_aspect_samples": 132,
      "unseen_aspect_ratio": 0.2449
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 368,
      "unseen_aspect_ratio": 0.3286
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=1.0348 valid_loss=0.6938 valid_acc=0.7328 valid_f1=0.5043 lr=6.57e-06 time=69.5s eta=12.7m
saved best checkpoint: epoch=1 valid_f1=0.5043
epoch=2/12 train_loss=0.6454 valid_loss=0.5837 valid_acc=0.7848 valid_f1=0.6910 lr=7.42e-06 time=69.1s eta=11.5m
saved best checkpoint: epoch=2 valid_f1=0.6910
epoch=3/12 train_loss=0.4933 valid_loss=0.5543 valid_acc=0.8033 valid_f1=0.7291 lr=6.68e-06 time=68.3s eta=10.2m
saved best checkpoint: epoch=3 valid_f1=0.7291
epoch=4/12 train_loss=0.3940 valid_loss=0.5314 valid_acc=0.8126 valid_f1=0.7466 lr=5.94e-06 time=69.2s eta=9.2m
saved best checkpoint: epoch=4 valid_f1=0.7466
epoch=5/12 train_loss=0.3136 valid_loss=0.5582 valid_acc=0.8330 valid_f1=0.7758 lr=5.20e-06 time=68.8s eta=8.0m
saved best checkpoint: epoch=5 valid_f1=0.7758
epoch=6/12 train_loss=0.2661 valid_loss=0.5853 valid_acc=0.8237 valid_f1=0.7633 lr=4.46e-06 time=68.3s eta=6.8m
no improvement: 1/3
epoch=7/12 train_loss=0.2216 valid_loss=0.6090 valid_acc=0.8386 valid_f1=0.7841 lr=3.71e-06 time=67.9s eta=5.7m
saved best checkpoint: epoch=7 valid_f1=0.7841
epoch=8/12 train_loss=0.1897 valid_loss=0.6360 valid_acc=0.8404 valid_f1=0.7903 lr=2.97e-06 time=67.7s eta=4.5m
saved best checkpoint: epoch=8 valid_f1=0.7903
epoch=9/12 train_loss=0.1677 valid_loss=0.6206 valid_acc=0.8386 valid_f1=0.7812 lr=2.23e-06 time=68.1s eta=3.4m
no improvement: 1/3
epoch=10/12 train_loss=0.1569 valid_loss=0.6561 valid_acc=0.8423 valid_f1=0.7886 lr=1.49e-06 time=67.7s eta=2.3m
no improvement: 2/3
epoch=11/12 train_loss=0.1502 valid_loss=0.6724 valid_acc=0.8349 valid_f1=0.7655 lr=7.52e-07 time=67.8s eta=1.1m
no improvement: 3/3
early stopping at epoch 11; best epoch was 8
calibration_temperature=1.806903
{
  "validation": {
    "accuracy": 0.8404,
    "precision_macro": 0.7828,
    "recall_macro": 0.7994,
    "macro_f1": 0.7903,
    "weighted_f1": 0.8435,
    "roc_auc_macro": 0.9269,
    "average_confidence": 0.84,
    "expected_calibration_error": 0.0455,
    "temperature": 1.806903,
    "uncalibrated_confidence": 0.9297,
    "seen": {
      "samples": 407,
      "accuracy": 0.855,
      "macro_f1": 0.8104
    },
    "unseen": {
      "samples": 132,
      "accuracy": 0.7955,
      "macro_f1": 0.717
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_cls_neutral125_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_cls_neutral150_split2024_seed2024 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.5 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 18:32:37.142501: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781980357.160475     404 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781980357.166660     404 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781980357.183007     404 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781980357.183027     404 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781980357.183029     404 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781980357.183032     404 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3070,
      "labels": {
        "negative": 686,
        "neutral": 542,
        "positive": 1842
      },
      "unique_aspects": 1069
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 537,
      "labels": {
        "negative": 121,
        "neutral": 95,
        "positive": 321
      },
      "unique_aspects": 281,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2551
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.857143,
    "neutral": 1.285714,
    "positive": 0.857143
  }
}
epoch=1/12 train_loss=0.9872 valid_loss=0.7176 valid_acc=0.6238 valid_f1=0.4368 lr=6.57e-06 time=69.2s eta=12.7m
saved best checkpoint: epoch=1 valid_f1=0.4368
epoch=2/12 train_loss=0.6548 valid_loss=0.6179 valid_acc=0.7412 valid_f1=0.6404 lr=7.42e-06 time=68.5s eta=11.4m
saved best checkpoint: epoch=2 valid_f1=0.6404
epoch=3/12 train_loss=0.5261 valid_loss=0.6015 valid_acc=0.7598 valid_f1=0.6654 lr=6.68e-06 time=68.3s eta=10.2m
saved best checkpoint: epoch=3 valid_f1=0.6654
epoch=4/12 train_loss=0.4134 valid_loss=0.5889 valid_acc=0.7803 valid_f1=0.6880 lr=5.94e-06 time=69.4s eta=9.3m
saved best checkpoint: epoch=4 valid_f1=0.6880
epoch=5/12 train_loss=0.3269 valid_loss=0.6184 valid_acc=0.7933 valid_f1=0.7198 lr=5.20e-06 time=69.0s eta=8.1m
saved best checkpoint: epoch=5 valid_f1=0.7198
epoch=6/12 train_loss=0.2628 valid_loss=0.6776 valid_acc=0.8138 valid_f1=0.7437 lr=4.46e-06 time=68.8s eta=6.9m
saved best checkpoint: epoch=6 valid_f1=0.7437
epoch=7/12 train_loss=0.2329 valid_loss=0.6854 valid_acc=0.8082 valid_f1=0.7369 lr=3.71e-06 time=69.3s eta=5.8m
no improvement: 1/3
epoch=8/12 train_loss=0.1973 valid_loss=0.7230 valid_acc=0.8101 valid_f1=0.7511 lr=2.97e-06 time=68.7s eta=4.6m
saved best checkpoint: epoch=8 valid_f1=0.7511
epoch=9/12 train_loss=0.1749 valid_loss=0.7573 valid_acc=0.8231 valid_f1=0.7611 lr=2.23e-06 time=68.7s eta=3.4m
saved best checkpoint: epoch=9 valid_f1=0.7611
epoch=10/12 train_loss=0.1516 valid_loss=0.7960 valid_acc=0.8231 valid_f1=0.7575 lr=1.49e-06 time=68.4s eta=2.3m
no improvement: 1/3
epoch=11/12 train_loss=0.1464 valid_loss=0.7772 valid_acc=0.8250 valid_f1=0.7606 lr=7.52e-07 time=68.0s eta=1.1m
no improvement: 2/3
epoch=12/12 train_loss=0.1427 valid_loss=0.7789 valid_acc=0.8194 valid_f1=0.7555 lr=1.16e-08 time=68.3s eta=0.0m
no improvement: 3/3
early stopping at epoch 12; best epoch was 9
calibration_temperature=1.986055
{
  "validation": {
    "accuracy": 0.8231,
    "precision_macro": 0.7561,
    "recall_macro": 0.7688,
    "macro_f1": 0.7611,
    "weighted_f1": 0.8249,
    "roc_auc_macro": 0.9044,
    "average_confidence": 0.8307,
    "expected_calibration_error": 0.057,
    "temperature": 1.986055,
    "uncalibrated_confidence": 0.9482,
    "seen": {
      "samples": 400,
      "accuracy": 0.825,
      "macro_f1": 0.7742
    },
    "unseen": {
      "samples": 137,
      "accuracy": 0.8175,
      "macro_f1": 0.709
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_cls_neutral150_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_cls_neutral150_split42_seed42 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.5 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 18:48:39.065279: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781981319.084382     431 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781981319.090703     431 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781981319.107932     431 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781981319.107955     431 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781981319.107957     431 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781981319.107959     431 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3066,
      "labels": {
        "negative": 684,
        "neutral": 540,
        "positive": 1842
      },
      "unique_aspects": 1066
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 541,
      "labels": {
        "negative": 123,
        "neutral": 97,
        "positive": 321
      },
      "unique_aspects": 273,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2532
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 364,
      "unseen_aspect_ratio": 0.325
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.857143,
    "neutral": 1.285714,
    "positive": 0.857143
  }
}
epoch=1/12 train_loss=0.9237 valid_loss=0.7425 valid_acc=0.7024 valid_f1=0.5586 lr=6.64e-06 time=69.7s eta=12.8m
saved best checkpoint: epoch=1 valid_f1=0.5586
epoch=2/12 train_loss=0.6244 valid_loss=0.7624 valid_acc=0.7172 valid_f1=0.5949 lr=7.41e-06 time=69.4s eta=11.6m
saved best checkpoint: epoch=2 valid_f1=0.5949
epoch=3/12 train_loss=0.5151 valid_loss=0.7191 valid_acc=0.7006 valid_f1=0.6118 lr=6.67e-06 time=69.3s eta=10.4m
saved best checkpoint: epoch=3 valid_f1=0.6118
epoch=4/12 train_loss=0.4339 valid_loss=0.6810 valid_acc=0.7579 valid_f1=0.6686 lr=5.93e-06 time=69.6s eta=9.3m
saved best checkpoint: epoch=4 valid_f1=0.6686
epoch=5/12 train_loss=0.3486 valid_loss=0.8298 valid_acc=0.7708 valid_f1=0.6583 lr=5.19e-06 time=69.2s eta=8.1m
no improvement: 1/3
epoch=6/12 train_loss=0.2907 valid_loss=0.7914 valid_acc=0.7893 valid_f1=0.7049 lr=4.45e-06 time=68.8s eta=6.9m
saved best checkpoint: epoch=6 valid_f1=0.7049
epoch=7/12 train_loss=0.2478 valid_loss=0.8239 valid_acc=0.7911 valid_f1=0.7067 lr=3.71e-06 time=69.6s eta=5.8m
no improvement: 1/3
epoch=8/12 train_loss=0.2037 valid_loss=0.8924 valid_acc=0.7893 valid_f1=0.7115 lr=2.97e-06 time=68.6s eta=4.6m
saved best checkpoint: epoch=8 valid_f1=0.7115
epoch=9/12 train_loss=0.1829 valid_loss=0.9386 valid_acc=0.7856 valid_f1=0.7008 lr=2.23e-06 time=69.3s eta=3.5m
no improvement: 1/3
epoch=10/12 train_loss=0.1719 valid_loss=0.9570 valid_acc=0.7800 valid_f1=0.6965 lr=1.49e-06 time=69.0s eta=2.3m
no improvement: 2/3
epoch=11/12 train_loss=0.1631 valid_loss=0.9683 valid_acc=0.7874 valid_f1=0.7022 lr=7.52e-07 time=68.7s eta=1.1m
no improvement: 3/3
early stopping at epoch 11; best epoch was 8
calibration_temperature=2.171327
{
  "validation": {
    "accuracy": 0.7893,
    "precision_macro": 0.7181,
    "recall_macro": 0.7076,
    "macro_f1": 0.7115,
    "weighted_f1": 0.7894,
    "roc_auc_macro": 0.8861,
    "average_confidence": 0.8037,
    "expected_calibration_error": 0.0479,
    "temperature": 2.171327,
    "uncalibrated_confidence": 0.948,
    "seen": {
      "samples": 404,
      "accuracy": 0.7921,
      "macro_f1": 0.7289
    },
    "unseen": {
      "samples": 137,
      "accuracy": 0.781,
      "macro_f1": 0.6461
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_cls_neutral150_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_cls_neutral150_split3407_seed3407 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.5 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 19:03:35.081683: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781982215.100435     458 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781982215.106705     458 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781982215.122491     458 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781982215.122538     458 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781982215.122544     458 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781982215.122548     458 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3068,
      "labels": {
        "negative": 685,
        "neutral": 542,
        "positive": 1841
      },
      "unique_aspects": 1074
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 132,
      "unseen_aspect_ratio": 0.0366
    },
    "valid": {
      "samples": 539,
      "labels": {
        "negative": 122,
        "neutral": 95,
        "positive": 322
      },
      "unique_aspects": 267,
      "unseen_aspect_samples": 132,
      "unseen_aspect_ratio": 0.2449
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 368,
      "unseen_aspect_ratio": 0.3286
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.857143,
    "neutral": 1.285714,
    "positive": 0.857143
  }
}
epoch=1/12 train_loss=1.0217 valid_loss=0.6962 valid_acc=0.7180 valid_f1=0.4866 lr=6.57e-06 time=70.9s eta=13.0m
saved best checkpoint: epoch=1 valid_f1=0.4866
epoch=2/12 train_loss=0.6465 valid_loss=0.5769 valid_acc=0.7996 valid_f1=0.7205 lr=7.42e-06 time=70.8s eta=11.8m
saved best checkpoint: epoch=2 valid_f1=0.7205
epoch=3/12 train_loss=0.4953 valid_loss=0.5555 valid_acc=0.8071 valid_f1=0.7402 lr=6.68e-06 time=70.5s eta=10.6m
saved best checkpoint: epoch=3 valid_f1=0.7402
epoch=4/12 train_loss=0.3957 valid_loss=0.5379 valid_acc=0.8108 valid_f1=0.7459 lr=5.94e-06 time=70.9s eta=9.5m
saved best checkpoint: epoch=4 valid_f1=0.7459
epoch=5/12 train_loss=0.3178 valid_loss=0.5520 valid_acc=0.8367 valid_f1=0.7870 lr=5.20e-06 time=70.6s eta=8.2m
saved best checkpoint: epoch=5 valid_f1=0.7870
epoch=6/12 train_loss=0.2605 valid_loss=0.6088 valid_acc=0.8163 valid_f1=0.7557 lr=4.46e-06 time=70.3s eta=7.0m
no improvement: 1/3
epoch=7/12 train_loss=0.2180 valid_loss=0.6298 valid_acc=0.8293 valid_f1=0.7695 lr=3.71e-06 time=70.3s eta=5.9m
no improvement: 2/3
epoch=8/12 train_loss=0.1893 valid_loss=0.6440 valid_acc=0.8349 valid_f1=0.7828 lr=2.97e-06 time=69.9s eta=4.7m
no improvement: 3/3
early stopping at epoch 8; best epoch was 5
calibration_temperature=1.461690
{
  "validation": {
    "accuracy": 0.8367,
    "precision_macro": 0.7757,
    "recall_macro": 0.8017,
    "macro_f1": 0.787,
    "weighted_f1": 0.841,
    "roc_auc_macro": 0.9305,
    "average_confidence": 0.822,
    "expected_calibration_error": 0.0292,
    "temperature": 1.46169,
    "uncalibrated_confidence": 0.8827,
    "seen": {
      "samples": 407,
      "accuracy": 0.8501,
      "macro_f1": 0.8047
    },
    "unseen": {
      "samples": 132,
      "accuracy": 0.7955,
      "macro_f1": 0.7151
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_cls_neutral150_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_aspect_attention_neutral125_split2024_seed2024 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 19:15:13.233474: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781982913.252214     485 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781982913.258653     485 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781982913.274542     485 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781982913.274564     485 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781982913.274567     485 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781982913.274569     485 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3070,
      "labels": {
        "negative": 686,
        "neutral": 542,
        "positive": 1842
      },
      "unique_aspects": 1069
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 537,
      "labels": {
        "negative": 121,
        "neutral": 95,
        "positive": 321
      },
      "unique_aspects": 281,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2551
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=0.9907 valid_loss=0.7096 valid_acc=0.7188 valid_f1=0.6248 lr=6.61e-06 time=70.0s eta=12.8m
saved best checkpoint: epoch=1 valid_f1=0.6248
epoch=2/12 train_loss=0.6110 valid_loss=0.5074 valid_acc=0.7989 valid_f1=0.7296 lr=7.42e-06 time=69.2s eta=11.5m
saved best checkpoint: epoch=2 valid_f1=0.7296
epoch=3/12 train_loss=0.4402 valid_loss=0.5098 valid_acc=0.8082 valid_f1=0.7391 lr=6.68e-06 time=69.1s eta=10.4m
saved best checkpoint: epoch=3 valid_f1=0.7391
epoch=4/12 train_loss=0.3245 valid_loss=0.5533 valid_acc=0.8231 valid_f1=0.7498 lr=5.94e-06 time=69.2s eta=9.2m
saved best checkpoint: epoch=4 valid_f1=0.7498
epoch=5/12 train_loss=0.2389 valid_loss=0.6293 valid_acc=0.8268 valid_f1=0.7500 lr=5.20e-06 time=68.9s eta=8.0m
no improvement: 1/3
epoch=6/12 train_loss=0.1993 valid_loss=0.7254 valid_acc=0.8268 valid_f1=0.7399 lr=4.46e-06 time=69.0s eta=6.9m
no improvement: 2/3
epoch=7/12 train_loss=0.1684 valid_loss=0.7094 valid_acc=0.8343 valid_f1=0.7644 lr=3.71e-06 time=69.5s eta=5.8m
saved best checkpoint: epoch=7 valid_f1=0.7644
epoch=8/12 train_loss=0.1428 valid_loss=0.7074 valid_acc=0.8268 valid_f1=0.7539 lr=2.97e-06 time=69.1s eta=4.6m
no improvement: 1/3
epoch=9/12 train_loss=0.1329 valid_loss=0.7044 valid_acc=0.8305 valid_f1=0.7631 lr=2.23e-06 time=69.7s eta=3.5m
no improvement: 2/3
epoch=10/12 train_loss=0.1222 valid_loss=0.7078 valid_acc=0.8399 valid_f1=0.7744 lr=1.49e-06 time=68.8s eta=2.3m
saved best checkpoint: epoch=10 valid_f1=0.7744
epoch=11/12 train_loss=0.1134 valid_loss=0.7141 valid_acc=0.8380 valid_f1=0.7671 lr=7.52e-07 time=68.9s eta=1.1m
no improvement: 1/3
epoch=12/12 train_loss=0.1171 valid_loss=0.7079 valid_acc=0.8417 valid_f1=0.7757 lr=1.16e-08 time=68.9s eta=0.0m
no improvement: 2/3
calibration_temperature=1.881660
{
  "validation": {
    "accuracy": 0.8399,
    "precision_macro": 0.78,
    "recall_macro": 0.7717,
    "macro_f1": 0.7744,
    "weighted_f1": 0.837,
    "roc_auc_macro": 0.9052,
    "average_confidence": 0.8406,
    "expected_calibration_error": 0.0261,
    "temperature": 1.88166,
    "uncalibrated_confidence": 0.9475,
    "seen": {
      "samples": 400,
      "accuracy": 0.8275,
      "macro_f1": 0.7662
    },
    "unseen": {
      "samples": 137,
      "accuracy": 0.8759,
      "macro_f1": 0.7979
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_aspect_attention_neutral125_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_aspect_attention_neutral125_split42_seed42 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 19:31:18.651410: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781983878.670460     512 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781983878.676484     512 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781983878.692386     512 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781983878.692408     512 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781983878.692411     512 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781983878.692413     512 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3066,
      "labels": {
        "negative": 684,
        "neutral": 540,
        "positive": 1842
      },
      "unique_aspects": 1066
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 541,
      "labels": {
        "negative": 123,
        "neutral": 97,
        "positive": 321
      },
      "unique_aspects": 273,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2532
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 364,
      "unseen_aspect_ratio": 0.325
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=0.9615 valid_loss=0.7458 valid_acc=0.6839 valid_f1=0.5164 lr=6.64e-06 time=70.3s eta=12.9m
saved best checkpoint: epoch=1 valid_f1=0.5164
epoch=2/12 train_loss=0.6318 valid_loss=0.6316 valid_acc=0.7634 valid_f1=0.6733 lr=7.41e-06 time=69.8s eta=11.6m
saved best checkpoint: epoch=2 valid_f1=0.6733
epoch=3/12 train_loss=0.4490 valid_loss=0.6042 valid_acc=0.7819 valid_f1=0.7187 lr=6.67e-06 time=69.8s eta=10.5m
saved best checkpoint: epoch=3 valid_f1=0.7187
epoch=4/12 train_loss=0.3574 valid_loss=0.6427 valid_acc=0.8115 valid_f1=0.7342 lr=5.94e-06 time=70.7s eta=9.4m
saved best checkpoint: epoch=4 valid_f1=0.7342
epoch=5/12 train_loss=0.2716 valid_loss=0.6784 valid_acc=0.8059 valid_f1=0.7355 lr=5.20e-06 time=71.9s eta=8.4m
no improvement: 1/3
epoch=6/12 train_loss=0.2172 valid_loss=0.7085 valid_acc=0.8059 valid_f1=0.7449 lr=4.46e-06 time=71.4s eta=7.1m
saved best checkpoint: epoch=6 valid_f1=0.7449
epoch=7/12 train_loss=0.1683 valid_loss=0.7325 valid_acc=0.8226 valid_f1=0.7491 lr=3.71e-06 time=70.5s eta=5.9m
saved best checkpoint: epoch=7 valid_f1=0.7491
epoch=8/12 train_loss=0.1567 valid_loss=0.7607 valid_acc=0.8115 valid_f1=0.7469 lr=2.97e-06 time=69.1s eta=4.6m
no improvement: 1/3
epoch=9/12 train_loss=0.1348 valid_loss=0.7840 valid_acc=0.8226 valid_f1=0.7571 lr=2.23e-06 time=69.6s eta=3.5m
saved best checkpoint: epoch=9 valid_f1=0.7571
epoch=10/12 train_loss=0.1229 valid_loss=0.8002 valid_acc=0.8244 valid_f1=0.7642 lr=1.49e-06 time=69.8s eta=2.3m
saved best checkpoint: epoch=10 valid_f1=0.7642
epoch=11/12 train_loss=0.1078 valid_loss=0.8062 valid_acc=0.8207 valid_f1=0.7552 lr=7.52e-07 time=70.3s eta=1.2m
no improvement: 1/3
epoch=12/12 train_loss=0.1080 valid_loss=0.8036 valid_acc=0.8226 valid_f1=0.7554 lr=1.16e-08 time=72.0s eta=0.0m
no improvement: 2/3
calibration_temperature=2.045658
{
  "validation": {
    "accuracy": 0.8244,
    "precision_macro": 0.7654,
    "recall_macro": 0.7634,
    "macro_f1": 0.7642,
    "weighted_f1": 0.8236,
    "roc_auc_macro": 0.8973,
    "average_confidence": 0.8268,
    "expected_calibration_error": 0.0367,
    "temperature": 2.045658,
    "uncalibrated_confidence": 0.9542,
    "seen": {
      "samples": 404,
      "accuracy": 0.8193,
      "macro_f1": 0.772
    },
    "unseen": {
      "samples": 137,
      "accuracy": 0.8394,
      "macro_f1": 0.7285
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_aspect_attention_neutral125_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_ablation_core --run-name tune_aspect_attention_neutral125_split3407_seed3407 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 19:47:42.303979: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781984862.323492     539 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781984862.329960     539 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781984862.347071     539 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781984862.347096     539 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781984862.347099     539 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781984862.347101     539 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3068,
      "labels": {
        "negative": 685,
        "neutral": 542,
        "positive": 1841
      },
      "unique_aspects": 1074
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 132,
      "unseen_aspect_ratio": 0.0366
    },
    "valid": {
      "samples": 539,
      "labels": {
        "negative": 122,
        "neutral": 95,
        "positive": 322
      },
      "unique_aspects": 267,
      "unseen_aspect_samples": 132,
      "unseen_aspect_ratio": 0.2449
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 368,
      "unseen_aspect_ratio": 0.3286
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=0.9547 valid_loss=0.6308 valid_acc=0.7458 valid_f1=0.5887 lr=6.64e-06 time=69.7s eta=12.8m
saved best checkpoint: epoch=1 valid_f1=0.5887
epoch=2/12 train_loss=0.6073 valid_loss=0.5382 valid_acc=0.8089 valid_f1=0.7118 lr=7.41e-06 time=70.0s eta=11.7m
saved best checkpoint: epoch=2 valid_f1=0.7118
epoch=3/12 train_loss=0.4325 valid_loss=0.5305 valid_acc=0.8052 valid_f1=0.7269 lr=6.67e-06 time=70.2s eta=10.5m
saved best checkpoint: epoch=3 valid_f1=0.7269
epoch=4/12 train_loss=0.3446 valid_loss=0.5764 valid_acc=0.8108 valid_f1=0.7368 lr=5.93e-06 time=70.0s eta=9.3m
saved best checkpoint: epoch=4 valid_f1=0.7368
epoch=5/12 train_loss=0.2713 valid_loss=0.5784 valid_acc=0.8256 valid_f1=0.7490 lr=5.19e-06 time=69.3s eta=8.1m
saved best checkpoint: epoch=5 valid_f1=0.7490
epoch=6/12 train_loss=0.2149 valid_loss=0.6059 valid_acc=0.8349 valid_f1=0.7828 lr=4.45e-06 time=70.8s eta=7.1m
saved best checkpoint: epoch=6 valid_f1=0.7828
epoch=7/12 train_loss=0.1781 valid_loss=0.6414 valid_acc=0.8293 valid_f1=0.7733 lr=3.71e-06 time=71.1s eta=5.9m
no improvement: 1/3
epoch=8/12 train_loss=0.1508 valid_loss=0.7079 valid_acc=0.8219 valid_f1=0.7537 lr=2.97e-06 time=69.7s eta=4.6m
no improvement: 2/3
epoch=9/12 train_loss=0.1329 valid_loss=0.7301 valid_acc=0.8293 valid_f1=0.7701 lr=2.23e-06 time=70.4s eta=3.5m
no improvement: 3/3
early stopping at epoch 9; best epoch was 6
calibration_temperature=1.714435
{
  "validation": {
    "accuracy": 0.8349,
    "precision_macro": 0.7923,
    "recall_macro": 0.7843,
    "macro_f1": 0.7828,
    "weighted_f1": 0.8395,
    "roc_auc_macro": 0.9327,
    "average_confidence": 0.8375,
    "expected_calibration_error": 0.0564,
    "temperature": 1.714435,
    "uncalibrated_confidence": 0.925,
    "seen": {
      "samples": 407,
      "accuracy": 0.8452,
      "macro_f1": 0.8004
    },
    "unseen": {
      "samples": 132,
      "accuracy": 0.803,
      "macro_f1": 0.7101
    }
  },
  "zip": "/kaggle/working/tuning_ablation_core/tune_aspect_attention_neutral125_split3407_seed3407_artifacts.zip"
}
{
  "selection_metric": "mean Macro-F1 minus one standard deviation",
  "search_space": "ablation_core",
  "final_split_seed": 2024,
  "validation_seed_pairs": [
    [
      2024,
      2024
    ],
    [
      42,
      42
    ],
    [
      3407,
      3407
    ]
  ],
  "best_configuration": {
    "name": "aspect_attention_neutral125",
    "pooling_strategy": "aspect_attention",
    "input_format": "term",
    "encoder_layer_pooling": "last",
    "encoder_learning_rate": 8e-06,
    "head_learning_rate": 2e-05,
    "dropout": 0.3,
    "class_weighting": "none",
    "neutral_weight_multiplier": 1.25,
    "label_smoothing": 0.02,
    "loss_type": "cross_entropy",
    "scheduler": "linear",
    "warmup_ratio": 0.1,
    "max_length": 128
  },
  "best_validation_summary": {
    "trial": "aspect_attention_neutral125",
    "mean_macro_f1": 0.7738,
    "std_macro_f1": 0.007605,
    "robust_macro_f1": 0.766195,
    "mean_accuracy": 0.833067,
    "mean_loss": 0.704633,
    "mean_log_loss": 0.499133,
    "mean_ece": 0.039733,
    "validation_seed_pairs": "2024:2024,42:42,3407:3407",
    "pooling_strategy": "aspect_attention",
    "input_format": "term",
    "encoder_layer_pooling": "last",
    "encoder_learning_rate": 8e-06,
    "head_learning_rate": 2e-05,
    "dropout": 0.3,
    "class_weighting": "none",
    "neutral_weight_multiplier": 1.25,
    "label_smoothing": 0.02,
    "loss_type": "cross_entropy",
    "scheduler": "linear",
    "warmup_ratio": 0.1,
    "max_length": 128
  },
  "ranking": [
    {
      "trial": "aspect_attention_neutral125",
      "mean_macro_f1": 0.7738,
      "std_macro_f1": 0.007605,
      "robust_macro_f1": 0.766195,
      "mean_accuracy": 0.833067,
      "mean_loss": 0.704633,
      "mean_log_loss": 0.499133,
      "mean_ece": 0.039733,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "aspect_attention",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.25,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "aspect_attention_term",
      "mean_macro_f1": 0.763367,
      "std_macro_f1": 0.011146,
      "robust_macro_f1": 0.75222,
      "mean_accuracy": 0.8256,
      "mean_loss": 0.629033,
      "mean_log_loss": 0.479033,
      "mean_ece": 0.0351,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "aspect_attention",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.0,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "hybrid_term",
      "mean_macro_f1": 0.7583,
      "std_macro_f1": 0.006556,
      "robust_macro_f1": 0.751744,
      "mean_accuracy": 0.8219,
      "mean_loss": 0.669433,
      "mean_log_loss": 0.4999,
      "mean_ece": 0.048533,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "hybrid",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.0,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "cls_neutral125",
      "mean_macro_f1": 0.753767,
      "std_macro_f1": 0.030605,
      "robust_macro_f1": 0.723161,
      "mean_accuracy": 0.8182,
      "mean_loss": 0.7765,
      "mean_log_loss": 0.521867,
      "mean_ece": 0.042167,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "cls",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.25,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "cls_neutral150",
      "mean_macro_f1": 0.7532,
      "std_macro_f1": 0.031325,
      "robust_macro_f1": 0.721875,
      "mean_accuracy": 0.816367,
      "mean_loss": 0.7339,
      "mean_log_loss": 0.521733,
      "mean_ece": 0.0447,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "cls",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.5,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "baseline_cls",
      "mean_macro_f1": 0.7531,
      "std_macro_f1": 0.036736,
      "robust_macro_f1": 0.716364,
      "mean_accuracy": 0.818833,
      "mean_loss": 0.746267,
      "mean_log_loss": 0.511467,
      "mean_ece": 0.048833,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "cls",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.0,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    }
  ]
}
FINAL RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 15 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/outputs_ablation_core --run-name rest_aspect_attention_neutral125_seed2024 --evaluation-split test --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing --refit-full-train

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 20:00:29.548440: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781985629.566510     566 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781985629.572413     566 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781985629.588486     566 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781985629.588508     566 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781985629.588511     566 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781985629.588513     566 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3070,
      "labels": {
        "negative": 686,
        "neutral": 542,
        "positive": 1842
      },
      "unique_aspects": 1069
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 537,
      "labels": {
        "negative": 121,
        "neutral": 95,
        "positive": 321
      },
      "unique_aspects": 281,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2551
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/15 train_loss=1.0121 valid_loss=0.7948 valid_acc=0.6797 valid_f1=0.5597 lr=5.28e-06 time=70.2s eta=16.4m
saved best checkpoint: epoch=1 valid_f1=0.5597
epoch=2/15 train_loss=0.6416 valid_loss=0.5076 valid_acc=0.8101 valid_f1=0.7434 lr=7.71e-06 time=69.9s eta=15.2m
saved best checkpoint: epoch=2 valid_f1=0.7434
epoch=3/15 train_loss=0.4603 valid_loss=0.5004 valid_acc=0.8156 valid_f1=0.7424 lr=7.12e-06 time=69.7s eta=13.9m
no improvement: 1/3
epoch=4/15 train_loss=0.3352 valid_loss=0.5415 valid_acc=0.8194 valid_f1=0.7429 lr=6.52e-06 time=70.2s eta=12.9m
no improvement: 2/3
epoch=5/15 train_loss=0.2452 valid_loss=0.5982 valid_acc=0.8305 valid_f1=0.7584 lr=5.93e-06 time=69.4s eta=11.6m
saved best checkpoint: epoch=5 valid_f1=0.7584
epoch=6/15 train_loss=0.1994 valid_loss=0.7069 valid_acc=0.8268 valid_f1=0.7466 lr=5.34e-06 time=69.2s eta=10.4m
no improvement: 1/3
epoch=7/15 train_loss=0.1687 valid_loss=0.6933 valid_acc=0.8343 valid_f1=0.7713 lr=4.75e-06 time=69.1s eta=9.2m
saved best checkpoint: epoch=7 valid_f1=0.7713
epoch=8/15 train_loss=0.1442 valid_loss=0.6897 valid_acc=0.8268 valid_f1=0.7548 lr=4.15e-06 time=69.0s eta=8.1m
no improvement: 1/3
epoch=9/15 train_loss=0.1292 valid_loss=0.6991 valid_acc=0.8268 valid_f1=0.7573 lr=3.56e-06 time=69.1s eta=6.9m
no improvement: 2/3
epoch=10/15 train_loss=0.1143 valid_loss=0.7055 valid_acc=0.8399 valid_f1=0.7768 lr=2.97e-06 time=68.9s eta=5.7m
saved best checkpoint: epoch=10 valid_f1=0.7768
epoch=11/15 train_loss=0.1123 valid_loss=0.7068 valid_acc=0.8305 valid_f1=0.7498 lr=2.38e-06 time=69.1s eta=4.6m
no improvement: 1/3
epoch=12/15 train_loss=0.1105 valid_loss=0.7070 valid_acc=0.8454 valid_f1=0.7791 lr=1.79e-06 time=69.8s eta=3.5m
saved best checkpoint: epoch=12 valid_f1=0.7791
epoch=13/15 train_loss=0.1067 valid_loss=0.6979 valid_acc=0.8417 valid_f1=0.7792 lr=1.19e-06 time=69.6s eta=2.3m
no improvement: 1/3
epoch=14/15 train_loss=0.1027 valid_loss=0.7048 valid_acc=0.8361 valid_f1=0.7704 lr=6.02e-07 time=69.9s eta=1.2m
no improvement: 2/3
epoch=15/15 train_loss=0.1010 valid_loss=0.7028 valid_acc=0.8361 valid_f1=0.7706 lr=9.26e-09 time=69.7s eta=0.0m
no improvement: 3/3
early stopping at epoch 15; best epoch was 12
calibration_temperature=1.883212
refit_epoch=1/12 train_loss=1.0036 lr=5.29e-06 time=82.6s
refit_epoch=2/12 train_loss=0.6167 lr=7.71e-06 time=80.6s
refit_epoch=3/12 train_loss=0.4330 lr=7.12e-06 time=80.3s
refit_epoch=4/12 train_loss=0.3138 lr=6.52e-06 time=80.0s
refit_epoch=5/12 train_loss=0.2521 lr=5.93e-06 time=79.9s
refit_epoch=6/12 train_loss=0.1991 lr=5.34e-06 time=79.2s
refit_epoch=7/12 train_loss=0.1595 lr=4.75e-06 time=79.3s
refit_epoch=8/12 train_loss=0.1525 lr=4.16e-06 time=78.9s
refit_epoch=9/12 train_loss=0.1309 lr=3.56e-06 time=79.3s
refit_epoch=10/12 train_loss=0.1144 lr=2.97e-06 time=79.0s
refit_epoch=11/12 train_loss=0.1124 lr=2.38e-06 time=79.8s
refit_epoch=12/12 train_loss=0.1066 lr=1.79e-06 time=78.9s
{
  "test": {
    "accuracy": 0.8652,
    "precision_macro": 0.8275,
    "recall_macro": 0.7656,
    "macro_f1": 0.781,
    "weighted_f1": 0.852,
    "roc_auc_macro": 0.9111,
    "average_confidence": 0.8608,
    "expected_calibration_error": 0.0459,
    "temperature": 1.883212,
    "uncalibrated_confidence": 0.9679,
    "seen": {
      "samples": 767,
      "accuracy": 0.8918,
      "macro_f1": 0.8183
    },
    "unseen": {
      "samples": 353,
      "accuracy": 0.8074,
      "macro_f1": 0.7068
    }
  },
  "zip": "/kaggle/working/outputs_ablation_core/rest_aspect_attention_neutral125_seed2024_artifacts.zip"
}
FINAL RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 15 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 42 --output-dir /kaggle/working/outputs_ablation_core --run-name rest_aspect_attention_neutral125_seed42 --evaluation-split test --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing --refit-full-train

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 20:36:12.886501: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781987772.904329     594 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781987772.910525     594 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781987772.926187     594 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781987772.926208     594 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781987772.926210     594 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781987772.926212     594 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3070,
      "labels": {
        "negative": 686,
        "neutral": 542,
        "positive": 1842
      },
      "unique_aspects": 1069
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 537,
      "labels": {
        "negative": 121,
        "neutral": 95,
        "positive": 321
      },
      "unique_aspects": 281,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2551
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/15 train_loss=0.9992 valid_loss=0.8115 valid_acc=0.6145 valid_f1=0.3300 lr=5.31e-06 time=71.5s eta=16.7m
saved best checkpoint: epoch=1 valid_f1=0.3300
epoch=2/15 train_loss=0.6732 valid_loss=0.5673 valid_acc=0.7709 valid_f1=0.6722 lr=7.71e-06 time=70.7s eta=15.3m
saved best checkpoint: epoch=2 valid_f1=0.6722
epoch=3/15 train_loss=0.4658 valid_loss=0.5581 valid_acc=0.8194 valid_f1=0.7505 lr=7.12e-06 time=70.6s eta=14.1m
saved best checkpoint: epoch=3 valid_f1=0.7505
epoch=4/15 train_loss=0.3518 valid_loss=0.5823 valid_acc=0.8212 valid_f1=0.7620 lr=6.52e-06 time=71.1s eta=13.0m
saved best checkpoint: epoch=4 valid_f1=0.7620
epoch=5/15 train_loss=0.2743 valid_loss=0.6595 valid_acc=0.8231 valid_f1=0.7508 lr=5.94e-06 time=70.6s eta=11.8m
no improvement: 1/3
epoch=6/15 train_loss=0.2168 valid_loss=0.6973 valid_acc=0.8231 valid_f1=0.7611 lr=5.34e-06 time=70.9s eta=10.6m
no improvement: 2/3
epoch=7/15 train_loss=0.1707 valid_loss=0.7042 valid_acc=0.8175 valid_f1=0.7557 lr=4.75e-06 time=70.4s eta=9.4m
no improvement: 3/3
early stopping at epoch 7; best epoch was 4
calibration_temperature=1.560496
refit_epoch=1/4 train_loss=1.0019 lr=5.31e-06 time=80.3s
refit_epoch=2/4 train_loss=0.6374 lr=7.71e-06 time=80.6s
refit_epoch=3/4 train_loss=0.4556 lr=7.12e-06 time=80.6s
refit_epoch=4/4 train_loss=0.3464 lr=6.52e-06 time=80.2s
{
  "test": {
    "accuracy": 0.8732,
    "precision_macro": 0.8285,
    "recall_macro": 0.7821,
    "macro_f1": 0.7995,
    "weighted_f1": 0.8652,
    "roc_auc_macro": 0.9573,
    "average_confidence": 0.8641,
    "expected_calibration_error": 0.0344,
    "temperature": 1.560496,
    "uncalibrated_confidence": 0.9303,
    "seen": {
      "samples": 767,
      "accuracy": 0.8944,
      "macro_f1": 0.8239
    },
    "unseen": {
      "samples": 353,
      "accuracy": 0.8272,
      "macro_f1": 0.7526
    }
  },
  "zip": "/kaggle/working/outputs_ablation_core/rest_aspect_attention_neutral125_seed42_artifacts.zip"
}
FINAL RUN: /usr/bin/python3 train.py --dataset rest --model microsoft/deberta-v3-base --epochs 15 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 3407 --output-dir /kaggle/working/outputs_ablation_core --run-name rest_aspect_attention_neutral125_seed3407 --evaluation-split test --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing --refit-full-train

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-20 20:52:12.121546: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781988732.141286     622 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781988732.147669     622 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781988732.164476     622 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781988732.164523     622 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781988732.164529     622 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781988732.164533     622 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3070,
      "labels": {
        "negative": 686,
        "neutral": 542,
        "positive": 1842
      },
      "unique_aspects": 1069
    },
    "train_all": {
      "samples": 3607,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2163
      },
      "unique_aspects": 1201,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.038
    },
    "valid": {
      "samples": 537,
      "labels": {
        "negative": 121,
        "neutral": 95,
        "positive": 321
      },
      "unique_aspects": 281,
      "unseen_aspect_samples": 137,
      "unseen_aspect_ratio": 0.2551
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 520,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "positive": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 1.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/15 train_loss=0.9896 valid_loss=0.7006 valid_acc=0.6834 valid_f1=0.4697 lr=5.28e-06 time=72.7s eta=17.0m
saved best checkpoint: epoch=1 valid_f1=0.4697
epoch=2/15 train_loss=0.6299 valid_loss=0.5352 valid_acc=0.7765 valid_f1=0.6997 lr=7.71e-06 time=72.1s eta=15.6m
saved best checkpoint: epoch=2 valid_f1=0.6997
epoch=3/15 train_loss=0.4733 valid_loss=0.5017 valid_acc=0.8026 valid_f1=0.7423 lr=7.12e-06 time=72.0s eta=14.4m
saved best checkpoint: epoch=3 valid_f1=0.7423
epoch=4/15 train_loss=0.3370 valid_loss=0.6915 valid_acc=0.8045 valid_f1=0.6978 lr=6.52e-06 time=71.7s eta=13.1m
no improvement: 1/3
epoch=5/15 train_loss=0.2602 valid_loss=0.6437 valid_acc=0.8026 valid_f1=0.7115 lr=5.93e-06 time=71.0s eta=11.8m
no improvement: 2/3
epoch=6/15 train_loss=0.2227 valid_loss=0.7321 valid_acc=0.7989 valid_f1=0.7133 lr=5.34e-06 time=71.2s eta=10.7m
no improvement: 3/3
early stopping at epoch 6; best epoch was 3
calibration_temperature=1.125398
refit_epoch=1/3 train_loss=0.9639 lr=5.29e-06 time=81.9s
refit_epoch=2/3 train_loss=0.6217 lr=7.71e-06 time=84.3s
refit_epoch=3/3 train_loss=0.4478 lr=7.12e-06 time=82.7s
{
  "test": {
    "accuracy": 0.8571,
    "precision_macro": 0.8116,
    "recall_macro": 0.7503,
    "macro_f1": 0.7706,
    "weighted_f1": 0.8443,
    "roc_auc_macro": 0.9457,
    "average_confidence": 0.901,
    "expected_calibration_error": 0.0439,
    "temperature": 1.125398,
    "uncalibrated_confidence": 0.9156,
    "seen": {
      "samples": 767,
      "accuracy": 0.8748,
      "macro_f1": 0.7831
    },
    "unseen": {
      "samples": 353,
      "accuracy": 0.8187,
      "macro_f1": 0.7516
    }
  },
  "zip": "/kaggle/working/outputs_ablation_core/rest_aspect_attention_neutral125_seed3407_artifacts.zip"
}

CompletedProcess(args=['/usr/bin/python3', 'tune.py', '--dataset', 'rest', '--search-space', 'ablation_core', '--validation-seed-pairs', '2024:2024,42:42,3407:3407', '--valid-ratio', '0.15', '--final-seeds', '2024,42,3407', '--epochs', '12', '--final-epochs', '15', '--patience', '3', '--batch-size', '8', '--gradient-accumulation-steps', '2', '--amp', '--gradient-checkpointing', '--run-final', '--output-dir', '/kaggle/working/tuning_ablation_core', '--final-output-dir', '/kaggle/working/outputs_ablation_core'], returncode=0)

## 5. Tổng hợp nhanh kết quả core ablation

Bước này đọc các file kết quả được sinh ra sau tuning và final evaluation, sau đó hiển thị các metric chính để so sánh giữa các trial.

Các metric cần chú ý gồm `Macro-F1`, độ lệch chuẩn giữa các seed, `Robust Macro-F1`, per-seed final metrics và calibration error nếu có.

In [6]:
import pandas as pd

summary_path = WORK / 'tuning_ablation_core' / 'tuning_summary.csv'
final_path = WORK / 'outputs_ablation_core' / 'final_runs_summary.csv'
meanstd_path = WORK / 'outputs_ablation_core' / 'final_metrics_mean_std.json'

print('Tuning summary:', summary_path)
summary = pd.read_csv(summary_path)
cols = [c for c in ['trial','mean_macro_f1','std_macro_f1','robust_macro_f1','mean_accuracy','mean_ece','pooling_strategy','input_format','neutral_weight_multiplier'] if c in summary.columns]
display(summary[cols])

if final_path.exists():
    print('Final runs:', final_path)
    final = pd.read_csv(final_path)
    display(final)

if meanstd_path.exists():
    print(json.dumps(json.loads(meanstd_path.read_text()), indent=2))

Tuning summary: /kaggle/working/tuning_ablation_core/tuning_summary.csv

,trial,mean_macro_f1,std_macro_f1,robust_macro_f1,mean_accuracy,mean_ece,pooling_strategy,input_format,neutral_weight_multiplier
0,aspect_attention_neutral125,0.773800,0.007605,0.766195,0.833067,0.039733,aspect_attention,term,1.25
1,aspect_attention_term,0.763367,0.011146,0.752220,0.825600,0.035100,aspect_attention,term,1.00
2,hybrid_term,0.758300,0.006556,0.751744,0.821900,0.048533,hybrid,term,1.00
3,cls_neutral125,0.753767,0.030605,0.723161,0.818200,0.042167,cls,term,1.25
4,cls_neutral150,0.753200,0.031325,0.721875,0.816367,0.044700,cls,term,1.50
5,baseline_cls,0.753100,0.036736,0.716364,0.818833,0.048833,cls,term,1.00

Final runs: /kaggle/working/outputs_ablation_core/final_runs_summary.csv

,seed,best_epoch,accuracy,precision_macro,recall_macro,macro_f1,weighted_f1,roc_auc_macro,log_loss,expected_calibration_error,temperature
0,2024,12,0.8652,0.8275,0.7656,0.7810,0.8520,0.9111,0.4201,0.0459,1.883212
1,42,4,0.8732,0.8285,0.7821,0.7995,0.8652,0.9573,0.3355,0.0344,1.560496
2,3407,3,0.8571,0.8116,0.7503,0.7706,0.8443,0.9457,0.3707,0.0439,1.125398

{
  "accuracy": {
    "mean": 0.865167,
    "std": 0.006573
  },
  "precision_macro": {
    "mean": 0.822533,
    "std": 0.007742
  },
  "recall_macro": {
    "mean": 0.766,
    "std": 0.012985
  },
  "macro_f1": {
    "mean": 0.7837,
    "std": 0.011952
  },
  "weighted_f1": {
    "mean": 0.853833,
    "std": 0.00863
  },
  "roc_auc_macro": {
    "mean": 0.938033,
    "std": 0.019625
  },
  "log_loss": {
    "mean": 0.375433,
    "std": 0.0347
  },
  "expected_calibration_error": {
    "mean": 0.0414,
    "std": 0.005017
  }
}

## 6. Thực nghiệm bổ sung: aspect description ablation

Bước này là thí nghiệm tùy chọn để kiểm tra riêng tác động của `aspects.json`. Mặc định cell không chạy để ưu tiên nhóm core ablation trước.

Chỉ nên bật `RUN_DESC_ABLATION = True` sau khi đã có kết quả core ablation, nhằm tránh nhầm lẫn giữa đóng góp của aspect description với các thay đổi như pooling hoặc class weighting.

In [7]:
RUN_DESC_ABLATION = False  # Set to True only after completing core ablation if description-based trials are required.

if RUN_DESC_ABLATION:
    desc_cmd = [
        sys.executable, 'tune.py',
        '--dataset', 'rest',
        '--search-space', 'ablation_desc',
        '--validation-seed-pairs', SEED_PAIRS,
        '--valid-ratio', str(VALID_RATIO),
        '--final-seeds', FINAL_SEEDS,
        '--epochs', str(EPOCHS),
        '--final-epochs', str(FINAL_EPOCHS),
        '--patience', '3',
        '--batch-size', str(BATCH_SIZE),
        '--gradient-accumulation-steps', str(GRAD_ACCUM),
        '--amp',
        '--gradient-checkpointing',
        '--run-final',
        '--output-dir', str(WORK / 'tuning_ablation_desc'),
        '--final-output-dir', str(WORK / 'outputs_ablation_desc'),
    ]
    print(' '.join(desc_cmd))
    subprocess.run(desc_cmd, check=True)
else:
    print('Description ablation is disabled. Set RUN_DESC_ABLATION = True to execute this optional experiment.')

Description ablation is disabled. Set RUN_DESC_ABLATION = True to execute this optional experiment.

## 7. Đóng gói kết quả thực nghiệm

Bước này gom các file kết quả tuning và final evaluation thành một file `.zip` để tải về từ Kaggle.

Mặc định notebook không đưa checkpoint vào file nén để giảm dung lượng. Nếu cần lưu checkpoint phục vụ phân tích sâu hơn, đặt `INCLUDE_CHECKPOINTS = True`.

In [8]:
INCLUDE_CHECKPOINTS = False
zip_out = WORK / 'absa_ablation_results_fresh.zip'
folders = [WORK / 'tuning_ablation_core', WORK / 'outputs_ablation_core', WORK / 'tuning_ablation_desc', WORK / 'outputs_ablation_desc']

with zipfile.ZipFile(zip_out, 'w', compression=zipfile.ZIP_DEFLATED) as zf:
    for folder in folders:
        if not folder.exists():
            continue
        for path in folder.rglob('*'):
            if path.is_file():
                if not INCLUDE_CHECKPOINTS and path.suffix in {'.pt', '.pth', '.bin', '.safetensors'}:
                    continue
                zf.write(path, path.relative_to(WORK))

print('Created:', zip_out)
print('Size MB:', round(zip_out.stat().st_size / 1024 / 1024, 2))

Created: /kaggle/working/absa_ablation_results_fresh.zip
Size MB: 1600.14