# ABSA Restaurant tiếng Việt — Clean Ablation Training

Notebook này huấn luyện pipeline ABSA trên bản dịch tiếng Việt của dataset Restaurant.

Khác với notebook tiếng Anh, encoder mặc định là `microsoft/mdeberta-v3-base` (multilingual). Quy trình vẫn giữ nguyên: làm sạch overlap, chia validation theo câu, core ablation trên ba seed, chọn bằng robust Macro-F1, refit full train và đánh giá official test.

Trước khi chạy:

1. Upload `absa_rest_vi_ablation_fresh.zip` thành Kaggle Dataset.
2. Gắn Dataset đó vào notebook.
3. Bật GPU và Internet.
4. Chạy toàn bộ cell theo thứ tự.

In [1]:
from pathlib import Path
import os, shutil, zipfile, json, subprocess, sys

print('Python:', sys.version)
print('Kaggle working exists:', Path('/kaggle/working').exists())
try:
    subprocess.run(['nvidia-smi'], check=False)
except FileNotFoundError:
    print('Không tìm thấy nvidia-smi; kiểm tra lại GPU accelerator.')

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Kaggle working exists: True
Mon Jun 22 19:44:59 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.159.04             Driver Version: 580.159.04     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla T4                       Off |   00000000:00:05.0 Off |                    0 |
| N/A   49C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

## 1. Giải nén package và tạo trạng thái clean-start

Cell tự tìm ZIP trong Kaggle Input. Nếu Kaggle đã giải nén Dataset, notebook tìm `train.py` và copy thư mục nguồn.

In [2]:
WORK = Path('/kaggle/working') if Path('/kaggle/working').exists() else Path.cwd()
INPUT = Path('/kaggle/input/datasets/banhbaogachcua/nlp-source-vi')
PROJECT = WORK / 'absa_rest_vi_ablation_fresh'

CORE_TUNING = WORK / 'tuning_rest_vi_ablation_core'
CORE_FINAL = WORK / 'outputs_rest_vi_ablation_core'
RESULT_ZIP = WORK / 'absa_rest_vi_results_fresh.zip'

CLEAN_RUN = True
if CLEAN_RUN:
    for path in [PROJECT, CORE_TUNING, CORE_FINAL, RESULT_ZIP]:
        if path.exists():
            print('Removing old:', path)
            shutil.rmtree(path) if path.is_dir() else path.unlink()

if not INPUT.exists():
    raise FileNotFoundError(f'Không tìm thấy Kaggle Input: {INPUT}')

zip_candidates = list(INPUT.rglob('absa_rest_vi_ablation_fresh.zip'))
if not zip_candidates:
    zip_candidates = list(INPUT.rglob('*rest*vi*ablation*.zip'))

if zip_candidates:
    zip_path = zip_candidates[0]
    print('Extracting ZIP:', zip_path)
    PROJECT.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(PROJECT)
else:
    candidates = [p for p in INPUT.rglob('train.py') if (p.parent / 'dataset/rest_vi').exists()]
    if not candidates:
        visible = [str(p.relative_to(INPUT)) for p in INPUT.rglob('*') if p.is_file()][:50]
        raise FileNotFoundError('Không tìm thấy package Restaurant VI. Files: ' + str(visible))
    source_dir = candidates[0].parent
    print('Copying extracted source:', source_dir)
    shutil.copytree(source_dir, PROJECT, dirs_exist_ok=True)

if not (PROJECT / 'train.py').exists():
    candidates = list(PROJECT.rglob('train.py'))
    if not candidates:
        raise FileNotFoundError('Đã giải nén nhưng không tìm thấy train.py')
    PROJECT = candidates[0].parent

print('PROJECT =', PROJECT)
print('Files:', sorted(p.name for p in PROJECT.iterdir()))

Copying extracted source: /kaggle/input/datasets/banhbaogachcua/nlp-source-vi
PROJECT = /kaggle/working/absa_rest_vi_ablation_fresh
Files: ['KAGGLE_REST_VI.md', 'README.md', 'absa_pipeline.py', 'dataset', 'kaggle_rest_vi_ablation_fresh.ipynb', 'requirements.txt', 'train.py', 'tune.py']

## 2. Cài đặt thư viện

Kaggle cần bật Internet để tải multilingual DeBERTa lần đầu.

In [3]:
os.chdir(PROJECT)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', 'pip'], check=True)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '-r', 'requirements.txt'], check=True)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 43.8 MB/s eta 0:00:00

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.

CompletedProcess(args=['/usr/bin/python3', '-m', 'pip', 'install', '-q', '-r', 'requirements.txt'], returncode=0)

## 3. Kiểm tra package và dataset tiếng Việt

Cell xác nhận số câu, số aspect, nhãn và vị trí `term/from/to`. Các trường dependency syntax không được yêu cầu.

In [4]:
os.chdir(PROJECT)
required = [
    Path('train.py'), Path('tune.py'), Path('absa_pipeline.py'),
    Path('dataset/rest_vi/train.multiple.json'),
    Path('dataset/rest_vi/test.multiple.json'),
    Path('dataset/rest_vi/aspects.json'),
]
missing = [str(path) for path in required if not path.exists()]
assert not missing, f'Thiếu file bắt buộc: {missing}'

forbidden_suffixes = {'.pt', '.pth', '.bin', '.safetensors'}
history_files = [str(p.relative_to(PROJECT)) for p in PROJECT.rglob('*') if p.suffix in forbidden_suffixes]
assert not history_files, f'Package chứa checkpoint cũ: {history_files[:20]}'

from collections import Counter
for split in ['train', 'test']:
    rows = json.loads(Path(f'dataset/rest_vi/{split}.multiple.json').read_text(encoding='utf-8'))
    aspects = [a for row in rows for a in row.get('aspects', [])]
    errors = []
    for row in rows:
        assert row['sentence'] == ' '.join(row['tokens'])
        for aspect in row['aspects']:
            actual = row['tokens'][aspect['from']:aspect['to']]
            if actual != aspect['term']:
                errors.append((row['index'], aspect['term'], actual))
    assert not errors, errors[:10]
    print(split, 'sentences=', len(rows), 'aspect_samples=', len(aspects),
          'labels=', dict(Counter(a['polarity'] for a in aspects)))

subprocess.run([sys.executable, 'tune.py', '--help'], check=True)

train sentences= 1980 aspect_samples= 3608 labels= {'negative': 807, 'positive': 2164, 'neutral': 637}
test sentences= 600 aspect_samples= 1120 labels= {'positive': 728, 'neutral': 196, 'negative': 196}
usage: tune.py [-h] [--dataset {lap,rest,rest_vi,twi}] [--model MODEL]
               [--epochs EPOCHS] [--final-epochs FINAL_EPOCHS]
               [--patience PATIENCE] [--batch-size BATCH_SIZE]
               [--gradient-accumulation-steps GRADIENT_ACCUMULATION_STEPS]
               [--weight-decay WEIGHT_DECAY] [--valid-ratio VALID_RATIO]
               [--split-seed SPLIT_SEED] [--tuning-seeds TUNING_SEEDS]
               [--validation-seed-pairs VALIDATION_SEED_PAIRS]
               [--final-seeds FINAL_SEEDS] [--output-dir OUTPUT_DIR]
               [--final-output-dir FINAL_OUTPUT_DIR] [--amp]
               [--gradient-checkpointing] [--run-final]
               [--keep-trial-checkpoints] [--resume]
               [--search-space {ablation_all,ablation_core,ablation_desc,initial,refined}]
               [--trials TRIALS]

Select ABSA hyperparameters using validation Macro-F1

options:
  -h, --help            show this help message and exit
  --dataset {lap,rest,rest_vi,twi}
  --model MODEL
  --epochs EPOCHS
  --final-epochs FINAL_EPOCHS
  --patience PATIENCE
  --batch-size BATCH_SIZE
  --gradient-accumulation-steps GRADIENT_ACCUMULATION_STEPS
  --weight-decay WEIGHT_DECAY
  --valid-ratio VALID_RATIO
  --split-seed SPLIT_SEED
  --tuning-seeds TUNING_SEEDS
  --validation-seed-pairs VALIDATION_SEED_PAIRS
                        Comma-separated split_seed:model_seed pairs.
  --final-seeds FINAL_SEEDS
  --output-dir OUTPUT_DIR
  --final-output-dir FINAL_OUTPUT_DIR
  --amp
  --gradient-checkpointing
  --run-final
  --keep-trial-checkpoints
  --resume
  --search-space {ablation_all,ablation_core,ablation_desc,initial,refined}
  --trials TRIALS       Comma-separated trial names or 'all'.

CompletedProcess(args=['/usr/bin/python3', 'tune.py', '--help'], returncode=0)

## 4. Chạy core ablation

Mặc định chạy 18 validation run và 3 final run. Với GPU 16 GB, nếu hết bộ nhớ hãy đổi `BATCH_SIZE=4`, `GRAD_ACCUM=4`; effective batch size vẫn bằng 16.

Để kiểm tra nhanh pipeline trước, đặt `QUICK_CHECK=True`. Chế độ này chỉ chạy một cấu hình/một seed và không phải kết quả báo cáo cuối.

In [5]:
os.chdir(PROJECT)

MODEL = 'microsoft/mdeberta-v3-base'
VALID_RATIO = 0.15
BATCH_SIZE = 8
GRAD_ACCUM = 2
EPOCHS = 12
FINAL_EPOCHS = 15
SEED_PAIRS = '2024:2024,42:42,3407:3407'
FINAL_SEEDS = '2024,42,3407'
QUICK_CHECK = False

cmd = [
    sys.executable, 'tune.py',
    '--dataset', 'rest_vi',
    '--model', MODEL,
    '--search-space', 'ablation_core',
    '--validation-seed-pairs', '2024:2024' if QUICK_CHECK else SEED_PAIRS,
    '--valid-ratio', str(VALID_RATIO),
    '--final-seeds', '2024' if QUICK_CHECK else FINAL_SEEDS,
    '--epochs', '2' if QUICK_CHECK else str(EPOCHS),
    '--final-epochs', '2' if QUICK_CHECK else str(FINAL_EPOCHS),
    '--patience', '2' if QUICK_CHECK else '3',
    '--batch-size', str(BATCH_SIZE),
    '--gradient-accumulation-steps', str(GRAD_ACCUM),
    '--amp', '--gradient-checkpointing', '--run-final',
    '--output-dir', str(CORE_TUNING),
    '--final-output-dir', str(CORE_FINAL),
]
if QUICK_CHECK:
    cmd.extend(['--trials', 'aspect_attention_term'])

print(' '.join(cmd))
subprocess.run(cmd, check=True)

/usr/bin/python3 tune.py --dataset rest_vi --model microsoft/mdeberta-v3-base --search-space ablation_core --validation-seed-pairs 2024:2024,42:42,3407:3407 --valid-ratio 0.15 --final-seeds 2024,42,3407 --epochs 12 --final-epochs 15 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --amp --gradient-checkpointing --run-final --output-dir /kaggle/working/tuning_rest_vi_ablation_core --final-output-dir /kaggle/working/outputs_rest_vi_ablation_core
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_baseline_cls_split2024_seed2024 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 19:45:47.541614: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782157547.704924      63 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782157547.750340      63 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782157548.165740      63 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782157548.165772      63 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782157548.165775      63 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782157548.165778      63 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 684,
        "neutral": 541,
        "positive": 1839
      },
      "unique_aspects": 1079
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.041
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 123,
        "neutral": 96,
        "positive": 323
      },
      "unique_aspects": 286,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.2731
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.0442 valid_loss=0.7877 valid_acc=0.5959 valid_f1=0.2489 lr=6.54e-06 time=87.1s eta=16.0m
saved best checkpoint: epoch=1 valid_f1=0.2489
epoch=2/12 train_loss=0.7263 valid_loss=0.6466 valid_acc=0.7435 valid_f1=0.6276 lr=7.42e-06 time=84.0s eta=14.0m
saved best checkpoint: epoch=2 valid_f1=0.6276
epoch=3/12 train_loss=0.5934 valid_loss=0.6673 valid_acc=0.7601 valid_f1=0.6137 lr=6.68e-06 time=83.2s eta=12.5m
no improvement: 1/3
epoch=4/12 train_loss=0.5090 valid_loss=0.6799 valid_acc=0.7712 valid_f1=0.6590 lr=5.94e-06 time=83.5s eta=11.1m
saved best checkpoint: epoch=4 valid_f1=0.6590
epoch=5/12 train_loss=0.4492 valid_loss=0.6650 valid_acc=0.7380 valid_f1=0.6595 lr=5.20e-06 time=83.6s eta=9.8m
no improvement: 1/3
epoch=6/12 train_loss=0.3868 valid_loss=0.6981 valid_acc=0.7491 valid_f1=0.6712 lr=4.46e-06 time=83.1s eta=8.3m
saved best checkpoint: epoch=6 valid_f1=0.6712
epoch=7/12 train_loss=0.3505 valid_loss=0.7417 valid_acc=0.7472 valid_f1=0.6648 lr=3.72e-06 time=83.5s eta=7.0m
no improvement: 1/3
epoch=8/12 train_loss=0.3058 valid_loss=0.7628 valid_acc=0.7546 valid_f1=0.6609 lr=2.98e-06 time=83.1s eta=5.5m
no improvement: 2/3
epoch=9/12 train_loss=0.2690 valid_loss=0.8274 valid_acc=0.7657 valid_f1=0.6792 lr=2.24e-06 time=83.4s eta=4.2m
saved best checkpoint: epoch=9 valid_f1=0.6792
epoch=10/12 train_loss=0.2475 valid_loss=0.8324 valid_acc=0.7694 valid_f1=0.6864 lr=1.50e-06 time=83.4s eta=2.8m
saved best checkpoint: epoch=10 valid_f1=0.6864
epoch=11/12 train_loss=0.2330 valid_loss=0.8464 valid_acc=0.7620 valid_f1=0.6832 lr=7.60e-07 time=83.2s eta=1.4m
no improvement: 1/3
epoch=12/12 train_loss=0.2103 valid_loss=0.8517 valid_acc=0.7657 valid_f1=0.6842 lr=1.93e-08 time=83.2s eta=0.0m
no improvement: 2/3
calibration_temperature=2.065023
{
  "validation": {
    "accuracy": 0.7694,
    "precision_macro": 0.7051,
    "recall_macro": 0.675,
    "macro_f1": 0.6864,
    "weighted_f1": 0.766,
    "roc_auc_macro": 0.886,
    "average_confidence": 0.7886,
    "expected_calibration_error": 0.0723,
    "temperature": 2.065023,
    "uncalibrated_confidence": 0.922,
    "seen": {
      "samples": 394,
      "accuracy": 0.769,
      "macro_f1": 0.6956
    },
    "unseen": {
      "samples": 148,
      "accuracy": 0.7703,
      "macro_f1": 0.6572
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_baseline_cls_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_baseline_cls_split42_seed42 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 20:06:45.300399: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782158805.319103     108 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782158805.325084     108 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782158805.341148     108 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782158805.341188     108 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782158805.341194     108 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782158805.341198     108 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 683,
        "neutral": 542,
        "positive": 1839
      },
      "unique_aspects": 1070
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 155,
      "unseen_aspect_ratio": 0.043
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 124,
        "neutral": 95,
        "positive": 323
      },
      "unique_aspects": 287,
      "unseen_aspect_samples": 155,
      "unseen_aspect_ratio": 0.286
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=0.9895 valid_loss=0.7760 valid_acc=0.6900 valid_f1=0.4542 lr=6.54e-06 time=85.2s eta=15.6m
saved best checkpoint: epoch=1 valid_f1=0.4542
epoch=2/12 train_loss=0.7525 valid_loss=0.6381 valid_acc=0.7435 valid_f1=0.5849 lr=7.42e-06 time=84.8s eta=14.1m
saved best checkpoint: epoch=2 valid_f1=0.5849
epoch=3/12 train_loss=0.6276 valid_loss=0.6788 valid_acc=0.7509 valid_f1=0.6212 lr=6.68e-06 time=84.8s eta=12.7m
saved best checkpoint: epoch=3 valid_f1=0.6212
epoch=4/12 train_loss=0.5331 valid_loss=0.6762 valid_acc=0.7638 valid_f1=0.6415 lr=5.94e-06 time=85.0s eta=11.3m
saved best checkpoint: epoch=4 valid_f1=0.6415
epoch=5/12 train_loss=0.4690 valid_loss=0.6446 valid_acc=0.7675 valid_f1=0.6760 lr=5.20e-06 time=84.7s eta=9.9m
saved best checkpoint: epoch=5 valid_f1=0.6760
epoch=6/12 train_loss=0.4016 valid_loss=0.6657 valid_acc=0.7528 valid_f1=0.6700 lr=4.46e-06 time=84.7s eta=8.5m
no improvement: 1/3
epoch=7/12 train_loss=0.3453 valid_loss=0.7163 valid_acc=0.7583 valid_f1=0.6859 lr=3.72e-06 time=83.9s eta=7.0m
saved best checkpoint: epoch=7 valid_f1=0.6859
epoch=8/12 train_loss=0.2967 valid_loss=0.7813 valid_acc=0.7601 valid_f1=0.6641 lr=2.98e-06 time=86.2s eta=5.7m
no improvement: 1/3
epoch=9/12 train_loss=0.2648 valid_loss=0.8177 valid_acc=0.7546 valid_f1=0.6549 lr=2.24e-06 time=83.9s eta=4.2m
no improvement: 2/3
epoch=10/12 train_loss=0.2407 valid_loss=0.8417 valid_acc=0.7694 valid_f1=0.6830 lr=1.50e-06 time=84.2s eta=2.8m
no improvement: 3/3
early stopping at epoch 10; best epoch was 7
calibration_temperature=1.718209
{
  "validation": {
    "accuracy": 0.7583,
    "precision_macro": 0.7156,
    "recall_macro": 0.6829,
    "macro_f1": 0.6859,
    "weighted_f1": 0.7602,
    "roc_auc_macro": 0.8909,
    "average_confidence": 0.7773,
    "expected_calibration_error": 0.0626,
    "temperature": 1.718209,
    "uncalibrated_confidence": 0.8776,
    "seen": {
      "samples": 387,
      "accuracy": 0.7571,
      "macro_f1": 0.6888
    },
    "unseen": {
      "samples": 155,
      "accuracy": 0.7613,
      "macro_f1": 0.6778
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_baseline_cls_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_baseline_cls_split3407_seed3407 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 20:24:48.612841: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782159888.632515     135 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782159888.638870     135 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782159888.656672     135 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782159888.656693     135 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782159888.656695     135 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782159888.656698     135 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3066,
      "labels": {
        "negative": 687,
        "neutral": 542,
        "positive": 1837
      },
      "unique_aspects": 1065
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 161,
      "unseen_aspect_ratio": 0.0446
    },
    "valid": {
      "samples": 540,
      "labels": {
        "negative": 120,
        "neutral": 95,
        "positive": 325
      },
      "unique_aspects": 290,
      "unseen_aspect_samples": 161,
      "unseen_aspect_ratio": 0.2981
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 368,
      "unseen_aspect_ratio": 0.3286
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.0533 valid_loss=0.8630 valid_acc=0.6019 valid_f1=0.2505 lr=6.57e-06 time=83.0s eta=15.2m
saved best checkpoint: epoch=1 valid_f1=0.2505
epoch=2/12 train_loss=0.7474 valid_loss=0.6796 valid_acc=0.7278 valid_f1=0.5765 lr=7.42e-06 time=82.9s eta=13.8m
saved best checkpoint: epoch=2 valid_f1=0.5765
epoch=3/12 train_loss=0.5976 valid_loss=0.6993 valid_acc=0.7519 valid_f1=0.6436 lr=6.68e-06 time=84.9s eta=12.7m
saved best checkpoint: epoch=3 valid_f1=0.6436
epoch=4/12 train_loss=0.5249 valid_loss=0.7236 valid_acc=0.7556 valid_f1=0.6593 lr=5.94e-06 time=85.3s eta=11.4m
saved best checkpoint: epoch=4 valid_f1=0.6593
epoch=5/12 train_loss=0.4445 valid_loss=0.7345 valid_acc=0.7426 valid_f1=0.6085 lr=5.20e-06 time=82.8s eta=9.7m
no improvement: 1/3
epoch=6/12 train_loss=0.3991 valid_loss=0.7007 valid_acc=0.7500 valid_f1=0.6673 lr=4.46e-06 time=82.5s eta=8.2m
saved best checkpoint: epoch=6 valid_f1=0.6673
epoch=7/12 train_loss=0.3509 valid_loss=0.7584 valid_acc=0.7463 valid_f1=0.6484 lr=3.72e-06 time=83.0s eta=6.9m
no improvement: 1/3
epoch=8/12 train_loss=0.3159 valid_loss=0.7760 valid_acc=0.7463 valid_f1=0.6580 lr=2.98e-06 time=82.3s eta=5.5m
no improvement: 2/3
epoch=9/12 train_loss=0.2743 valid_loss=0.8210 valid_acc=0.7519 valid_f1=0.6735 lr=2.24e-06 time=83.1s eta=4.2m
saved best checkpoint: epoch=9 valid_f1=0.6735
epoch=10/12 train_loss=0.2376 valid_loss=0.8476 valid_acc=0.7444 valid_f1=0.6506 lr=1.50e-06 time=83.3s eta=2.8m
no improvement: 1/3
epoch=11/12 train_loss=0.2258 valid_loss=0.8540 valid_acc=0.7611 valid_f1=0.6682 lr=7.60e-07 time=82.4s eta=1.4m
no improvement: 2/3
epoch=12/12 train_loss=0.2188 valid_loss=0.8685 valid_acc=0.7556 valid_f1=0.6664 lr=1.93e-08 time=82.7s eta=0.0m
no improvement: 3/3
early stopping at epoch 12; best epoch was 9
calibration_temperature=2.024330
{
  "validation": {
    "accuracy": 0.7519,
    "precision_macro": 0.6728,
    "recall_macro": 0.6746,
    "macro_f1": 0.6735,
    "weighted_f1": 0.751,
    "roc_auc_macro": 0.8892,
    "average_confidence": 0.7886,
    "expected_calibration_error": 0.0723,
    "temperature": 2.02433,
    "uncalibrated_confidence": 0.9166,
    "seen": {
      "samples": 379,
      "accuracy": 0.7282,
      "macro_f1": 0.6636
    },
    "unseen": {
      "samples": 161,
      "accuracy": 0.8075,
      "macro_f1": 0.6962
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_baseline_cls_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_aspect_attention_term_split2024_seed2024 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 20:45:25.277632: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782161125.299228     162 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782161125.305848     162 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782161125.323502     162 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782161125.323523     162 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782161125.323526     162 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782161125.323529     162 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 684,
        "neutral": 541,
        "positive": 1839
      },
      "unique_aspects": 1079
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.041
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 123,
        "neutral": 96,
        "positive": 323
      },
      "unique_aspects": 286,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.2731
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.0267 valid_loss=0.8097 valid_acc=0.6439 valid_f1=0.4084 lr=6.57e-06 time=86.7s eta=15.9m
saved best checkpoint: epoch=1 valid_f1=0.4084
epoch=2/12 train_loss=0.7227 valid_loss=0.7519 valid_acc=0.6974 valid_f1=0.5674 lr=7.42e-06 time=86.8s eta=14.5m
saved best checkpoint: epoch=2 valid_f1=0.5674
epoch=3/12 train_loss=0.5587 valid_loss=0.7472 valid_acc=0.7251 valid_f1=0.5806 lr=6.68e-06 time=86.4s eta=13.0m
saved best checkpoint: epoch=3 valid_f1=0.5806
epoch=4/12 train_loss=0.4684 valid_loss=0.7291 valid_acc=0.7140 valid_f1=0.6473 lr=5.94e-06 time=86.5s eta=11.5m
saved best checkpoint: epoch=4 valid_f1=0.6473
epoch=5/12 train_loss=0.3871 valid_loss=0.7392 valid_acc=0.7362 valid_f1=0.6583 lr=5.20e-06 time=85.4s eta=10.0m
saved best checkpoint: epoch=5 valid_f1=0.6583
epoch=6/12 train_loss=0.3142 valid_loss=0.7904 valid_acc=0.7509 valid_f1=0.6506 lr=4.46e-06 time=85.2s eta=8.5m
no improvement: 1/3
epoch=7/12 train_loss=0.2688 valid_loss=0.8517 valid_acc=0.7435 valid_f1=0.6697 lr=3.72e-06 time=87.4s eta=7.3m
saved best checkpoint: epoch=7 valid_f1=0.6697
epoch=8/12 train_loss=0.2323 valid_loss=0.8452 valid_acc=0.7454 valid_f1=0.6577 lr=2.98e-06 time=89.1s eta=5.9m
no improvement: 1/3
epoch=9/12 train_loss=0.2114 valid_loss=0.8859 valid_acc=0.7546 valid_f1=0.6633 lr=2.24e-06 time=85.6s eta=4.3m
no improvement: 2/3
epoch=10/12 train_loss=0.1807 valid_loss=0.9397 valid_acc=0.7565 valid_f1=0.6621 lr=1.50e-06 time=84.9s eta=2.8m
no improvement: 3/3
early stopping at epoch 10; best epoch was 7
calibration_temperature=2.042850
{
  "validation": {
    "accuracy": 0.7435,
    "precision_macro": 0.6752,
    "recall_macro": 0.6657,
    "macro_f1": 0.6697,
    "weighted_f1": 0.7441,
    "roc_auc_macro": 0.8711,
    "average_confidence": 0.7696,
    "expected_calibration_error": 0.0656,
    "temperature": 2.04285,
    "uncalibrated_confidence": 0.9071,
    "seen": {
      "samples": 394,
      "accuracy": 0.7513,
      "macro_f1": 0.6858
    },
    "unseen": {
      "samples": 148,
      "accuracy": 0.723,
      "macro_f1": 0.629
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_aspect_attention_term_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_aspect_attention_term_split42_seed42 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 21:03:46.096545: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782162226.115857     189 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782162226.122349     189 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782162226.138829     189 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782162226.138849     189 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782162226.138852     189 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782162226.138855     189 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 683,
        "neutral": 542,
        "positive": 1839
      },
      "unique_aspects": 1070
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 155,
      "unseen_aspect_ratio": 0.043
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 124,
        "neutral": 95,
        "positive": 323
      },
      "unique_aspects": 287,
      "unseen_aspect_samples": 155,
      "unseen_aspect_ratio": 0.286
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.0382 valid_loss=0.7746 valid_acc=0.6310 valid_f1=0.3471 lr=6.61e-06 time=84.7s eta=15.5m
saved best checkpoint: epoch=1 valid_f1=0.3471
epoch=2/12 train_loss=0.7206 valid_loss=0.5731 valid_acc=0.7675 valid_f1=0.6637 lr=7.42e-06 time=83.9s eta=14.0m
saved best checkpoint: epoch=2 valid_f1=0.6637
epoch=3/12 train_loss=0.5513 valid_loss=0.5758 valid_acc=0.7823 valid_f1=0.6963 lr=6.68e-06 time=85.8s eta=12.9m
saved best checkpoint: epoch=3 valid_f1=0.6963
epoch=4/12 train_loss=0.4397 valid_loss=0.6002 valid_acc=0.7694 valid_f1=0.6767 lr=5.94e-06 time=88.7s eta=11.8m
no improvement: 1/3
epoch=5/12 train_loss=0.3417 valid_loss=0.6550 valid_acc=0.7878 valid_f1=0.6972 lr=5.20e-06 time=83.7s eta=9.8m
no improvement: 2/3
epoch=6/12 train_loss=0.2819 valid_loss=0.6848 valid_acc=0.7731 valid_f1=0.6912 lr=4.46e-06 time=83.4s eta=8.3m
no improvement: 3/3
early stopping at epoch 6; best epoch was 3
calibration_temperature=1.284312
{
  "validation": {
    "accuracy": 0.7823,
    "precision_macro": 0.7133,
    "recall_macro": 0.684,
    "macro_f1": 0.6963,
    "weighted_f1": 0.7749,
    "roc_auc_macro": 0.9029,
    "average_confidence": 0.7919,
    "expected_calibration_error": 0.0327,
    "temperature": 1.284312,
    "uncalibrated_confidence": 0.8353,
    "seen": {
      "samples": 387,
      "accuracy": 0.7752,
      "macro_f1": 0.6925
    },
    "unseen": {
      "samples": 155,
      "accuracy": 0.8,
      "macro_f1": 0.7059
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_aspect_attention_term_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_aspect_attention_term_split3407_seed3407 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 21:16:09.705625: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782162969.725199     216 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782162969.731841     216 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782162969.749045     216 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782162969.749064     216 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782162969.749067     216 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782162969.749069     216 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3066,
      "labels": {
        "negative": 687,
        "neutral": 542,
        "positive": 1837
      },
      "unique_aspects": 1065
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 161,
      "unseen_aspect_ratio": 0.0446
    },
    "valid": {
      "samples": 540,
      "labels": {
        "negative": 120,
        "neutral": 95,
        "positive": 325
      },
      "unique_aspects": 290,
      "unseen_aspect_samples": 161,
      "unseen_aspect_ratio": 0.2981
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 368,
      "unseen_aspect_ratio": 0.3286
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.0500 valid_loss=0.9201 valid_acc=0.6019 valid_f1=0.2505 lr=6.57e-06 time=84.1s eta=15.4m
saved best checkpoint: epoch=1 valid_f1=0.2505
epoch=2/12 train_loss=0.7088 valid_loss=0.6087 valid_acc=0.7574 valid_f1=0.6706 lr=7.42e-06 time=84.3s eta=14.0m
saved best checkpoint: epoch=2 valid_f1=0.6706
epoch=3/12 train_loss=0.5587 valid_loss=0.6233 valid_acc=0.7500 valid_f1=0.6499 lr=6.68e-06 time=85.6s eta=12.8m
no improvement: 1/3
epoch=4/12 train_loss=0.4302 valid_loss=0.6097 valid_acc=0.7593 valid_f1=0.6792 lr=5.94e-06 time=83.8s eta=11.2m
saved best checkpoint: epoch=4 valid_f1=0.6792
epoch=5/12 train_loss=0.3570 valid_loss=0.6579 valid_acc=0.7852 valid_f1=0.7093 lr=5.21e-06 time=84.3s eta=9.8m
saved best checkpoint: epoch=5 valid_f1=0.7093
epoch=6/12 train_loss=0.2950 valid_loss=0.6656 valid_acc=0.7833 valid_f1=0.7082 lr=4.47e-06 time=87.3s eta=8.7m
no improvement: 1/3
epoch=7/12 train_loss=0.2526 valid_loss=0.7735 valid_acc=0.7796 valid_f1=0.6906 lr=3.73e-06 time=83.8s eta=7.0m
no improvement: 2/3
epoch=8/12 train_loss=0.2209 valid_loss=0.7680 valid_acc=0.7741 valid_f1=0.6989 lr=2.99e-06 time=83.3s eta=5.6m
no improvement: 3/3
early stopping at epoch 8; best epoch was 5
calibration_temperature=1.668952
{
  "validation": {
    "accuracy": 0.7852,
    "precision_macro": 0.718,
    "recall_macro": 0.7099,
    "macro_f1": 0.7093,
    "weighted_f1": 0.7799,
    "roc_auc_macro": 0.9039,
    "average_confidence": 0.7937,
    "expected_calibration_error": 0.0517,
    "temperature": 1.668952,
    "uncalibrated_confidence": 0.8784,
    "seen": {
      "samples": 379,
      "accuracy": 0.7704,
      "macro_f1": 0.7116
    },
    "unseen": {
      "samples": 161,
      "accuracy": 0.8199,
      "macro_f1": 0.6919
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_aspect_attention_term_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_hybrid_term_split2024_seed2024 --evaluation-split validation --pooling-strategy hybrid --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 21:31:20.262212: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782163880.281354     243 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782163880.287504     243 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782163880.303894     243 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782163880.303917     243 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782163880.303920     243 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782163880.303922     243 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 684,
        "neutral": 541,
        "positive": 1839
      },
      "unique_aspects": 1079
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.041
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 123,
        "neutral": 96,
        "positive": 323
      },
      "unique_aspects": 286,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.2731
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.0184 valid_loss=0.8497 valid_acc=0.6107 valid_f1=0.3051 lr=6.61e-06 time=84.9s eta=15.6m
saved best checkpoint: epoch=1 valid_f1=0.3051
epoch=2/12 train_loss=0.7228 valid_loss=0.6540 valid_acc=0.7417 valid_f1=0.6580 lr=7.42e-06 time=84.2s eta=14.0m
saved best checkpoint: epoch=2 valid_f1=0.6580
epoch=3/12 train_loss=0.5378 valid_loss=0.6530 valid_acc=0.7417 valid_f1=0.6623 lr=6.68e-06 time=83.7s eta=12.6m
saved best checkpoint: epoch=3 valid_f1=0.6623
epoch=4/12 train_loss=0.4449 valid_loss=0.6881 valid_acc=0.7509 valid_f1=0.6575 lr=5.94e-06 time=83.9s eta=11.2m
no improvement: 1/3
epoch=5/12 train_loss=0.3451 valid_loss=0.7817 valid_acc=0.7620 valid_f1=0.6550 lr=5.20e-06 time=83.6s eta=9.7m
no improvement: 2/3
epoch=6/12 train_loss=0.2788 valid_loss=0.7447 valid_acc=0.7546 valid_f1=0.6681 lr=4.46e-06 time=84.0s eta=8.4m
saved best checkpoint: epoch=6 valid_f1=0.6681
epoch=7/12 train_loss=0.2345 valid_loss=0.7839 valid_acc=0.7601 valid_f1=0.6650 lr=3.72e-06 time=84.2s eta=7.0m
no improvement: 1/3
epoch=8/12 train_loss=0.1983 valid_loss=0.8834 valid_acc=0.7454 valid_f1=0.6718 lr=2.98e-06 time=86.4s eta=5.8m
saved best checkpoint: epoch=8 valid_f1=0.6718
epoch=9/12 train_loss=0.1685 valid_loss=0.8825 valid_acc=0.7657 valid_f1=0.6775 lr=2.24e-06 time=87.4s eta=4.4m
saved best checkpoint: epoch=9 valid_f1=0.6775
epoch=10/12 train_loss=0.1513 valid_loss=0.9011 valid_acc=0.7749 valid_f1=0.6752 lr=1.50e-06 time=87.1s eta=2.9m
no improvement: 1/3
epoch=11/12 train_loss=0.1411 valid_loss=0.9068 valid_acc=0.7804 valid_f1=0.6905 lr=7.56e-07 time=81.1s eta=1.4m
saved best checkpoint: epoch=11 valid_f1=0.6905
epoch=12/12 train_loss=0.1353 valid_loss=0.9110 valid_acc=0.7804 valid_f1=0.6929 lr=1.54e-08 time=82.2s eta=0.0m
saved best checkpoint: epoch=12 valid_f1=0.6929
calibration_temperature=2.211982
{
  "validation": {
    "accuracy": 0.7804,
    "precision_macro": 0.7137,
    "recall_macro": 0.6809,
    "macro_f1": 0.6929,
    "weighted_f1": 0.7709,
    "roc_auc_macro": 0.8533,
    "average_confidence": 0.7867,
    "expected_calibration_error": 0.0604,
    "temperature": 2.211982,
    "uncalibrated_confidence": 0.9385,
    "seen": {
      "samples": 394,
      "accuracy": 0.7716,
      "macro_f1": 0.6892
    },
    "unseen": {
      "samples": 148,
      "accuracy": 0.8041,
      "macro_f1": 0.7071
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_hybrid_term_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_hybrid_term_split42_seed42 --evaluation-split validation --pooling-strategy hybrid --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 21:52:10.254648: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782165130.274499     270 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782165130.281350     270 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782165130.299102     270 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782165130.299154     270 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782165130.299161     270 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782165130.299164     270 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 683,
        "neutral": 542,
        "positive": 1839
      },
      "unique_aspects": 1070
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 155,
      "unseen_aspect_ratio": 0.043
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 124,
        "neutral": 95,
        "positive": 323
      },
      "unique_aspects": 287,
      "unseen_aspect_samples": 155,
      "unseen_aspect_ratio": 0.286
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.0177 valid_loss=0.7877 valid_acc=0.6531 valid_f1=0.4230 lr=6.61e-06 time=81.7s eta=15.0m
saved best checkpoint: epoch=1 valid_f1=0.4230
epoch=2/12 train_loss=0.7202 valid_loss=0.5760 valid_acc=0.7749 valid_f1=0.6969 lr=7.42e-06 time=81.3s eta=13.6m
saved best checkpoint: epoch=2 valid_f1=0.6969
epoch=3/12 train_loss=0.5481 valid_loss=0.6140 valid_acc=0.7509 valid_f1=0.6588 lr=6.68e-06 time=81.9s eta=12.3m
no improvement: 1/3
epoch=4/12 train_loss=0.4447 valid_loss=0.6370 valid_acc=0.7638 valid_f1=0.6729 lr=5.94e-06 time=81.6s eta=10.9m
no improvement: 2/3
epoch=5/12 train_loss=0.3456 valid_loss=0.7240 valid_acc=0.7601 valid_f1=0.6624 lr=5.20e-06 time=81.6s eta=9.5m
no improvement: 3/3
early stopping at epoch 5; best epoch was 2
calibration_temperature=0.976543
{
  "validation": {
    "accuracy": 0.7749,
    "precision_macro": 0.7031,
    "recall_macro": 0.6915,
    "macro_f1": 0.6969,
    "weighted_f1": 0.7728,
    "roc_auc_macro": 0.8926,
    "average_confidence": 0.7831,
    "expected_calibration_error": 0.045,
    "temperature": 0.976543,
    "uncalibrated_confidence": 0.7781,
    "seen": {
      "samples": 387,
      "accuracy": 0.7778,
      "macro_f1": 0.7029
    },
    "unseen": {
      "samples": 155,
      "accuracy": 0.7677,
      "macro_f1": 0.6799
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_hybrid_term_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_hybrid_term_split3407_seed3407 --evaluation-split validation --pooling-strategy hybrid --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 22:02:42.660120: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782165762.679590     297 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782165762.685894     297 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782165762.702523     297 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782165762.702592     297 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782165762.702598     297 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782165762.702602     297 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3066,
      "labels": {
        "negative": 687,
        "neutral": 542,
        "positive": 1837
      },
      "unique_aspects": 1065
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 161,
      "unseen_aspect_ratio": 0.0446
    },
    "valid": {
      "samples": 540,
      "labels": {
        "negative": 120,
        "neutral": 95,
        "positive": 325
      },
      "unique_aspects": 290,
      "unseen_aspect_samples": 161,
      "unseen_aspect_ratio": 0.2981
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 368,
      "unseen_aspect_ratio": 0.3286
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.1104 valid_loss=0.7911 valid_acc=0.6278 valid_f1=0.3274 lr=6.57e-06 time=83.0s eta=15.2m
saved best checkpoint: epoch=1 valid_f1=0.3274
epoch=2/12 train_loss=0.7085 valid_loss=0.6674 valid_acc=0.7204 valid_f1=0.5761 lr=7.42e-06 time=83.1s eta=13.8m
saved best checkpoint: epoch=2 valid_f1=0.5761
epoch=3/12 train_loss=0.5480 valid_loss=0.6519 valid_acc=0.7667 valid_f1=0.6574 lr=6.68e-06 time=82.8s eta=12.4m
saved best checkpoint: epoch=3 valid_f1=0.6574
epoch=4/12 train_loss=0.4421 valid_loss=0.6811 valid_acc=0.7759 valid_f1=0.6653 lr=5.94e-06 time=82.7s eta=11.0m
saved best checkpoint: epoch=4 valid_f1=0.6653
epoch=5/12 train_loss=0.3563 valid_loss=0.6781 valid_acc=0.7463 valid_f1=0.6730 lr=5.20e-06 time=82.1s eta=9.6m
saved best checkpoint: epoch=5 valid_f1=0.6730
epoch=6/12 train_loss=0.2806 valid_loss=0.7347 valid_acc=0.7648 valid_f1=0.6742 lr=4.46e-06 time=82.3s eta=8.2m
no improvement: 1/3
epoch=7/12 train_loss=0.2278 valid_loss=0.7829 valid_acc=0.7722 valid_f1=0.6704 lr=3.72e-06 time=82.2s eta=6.8m
no improvement: 2/3
epoch=8/12 train_loss=0.1967 valid_loss=0.8088 valid_acc=0.7815 valid_f1=0.6941 lr=2.98e-06 time=82.1s eta=5.5m
saved best checkpoint: epoch=8 valid_f1=0.6941
epoch=9/12 train_loss=0.1711 valid_loss=0.8442 valid_acc=0.7815 valid_f1=0.6821 lr=2.24e-06 time=83.1s eta=4.2m
no improvement: 1/3
epoch=10/12 train_loss=0.1607 valid_loss=0.8394 valid_acc=0.7796 valid_f1=0.6810 lr=1.50e-06 time=82.3s eta=2.7m
no improvement: 2/3
epoch=11/12 train_loss=0.1427 valid_loss=0.8510 valid_acc=0.7815 valid_f1=0.6884 lr=7.60e-07 time=82.4s eta=1.4m
no improvement: 3/3
early stopping at epoch 11; best epoch was 8
calibration_temperature=2.085331
{
  "validation": {
    "accuracy": 0.7815,
    "precision_macro": 0.7096,
    "recall_macro": 0.6833,
    "macro_f1": 0.6941,
    "weighted_f1": 0.7741,
    "roc_auc_macro": 0.9031,
    "average_confidence": 0.8078,
    "expected_calibration_error": 0.0391,
    "temperature": 2.085331,
    "uncalibrated_confidence": 0.9357,
    "seen": {
      "samples": 379,
      "accuracy": 0.7652,
      "macro_f1": 0.6954
    },
    "unseen": {
      "samples": 161,
      "accuracy": 0.8199,
      "macro_f1": 0.6809
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_hybrid_term_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_cls_neutral125_split2024_seed2024 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 22:21:44.337278: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782166904.356446     324 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782166904.362708     324 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782166904.379022     324 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782166904.379073     324 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782166904.379079     324 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782166904.379083     324 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 684,
        "neutral": 541,
        "positive": 1839
      },
      "unique_aspects": 1079
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.041
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 123,
        "neutral": 96,
        "positive": 323
      },
      "unique_aspects": 286,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.2731
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=1.0215 valid_loss=0.9000 valid_acc=0.5959 valid_f1=0.2489 lr=6.61e-06 time=83.5s eta=15.3m
saved best checkpoint: epoch=1 valid_f1=0.2489
epoch=2/12 train_loss=0.7393 valid_loss=0.6311 valid_acc=0.7325 valid_f1=0.6381 lr=7.42e-06 time=82.4s eta=13.7m
saved best checkpoint: epoch=2 valid_f1=0.6381
epoch=3/12 train_loss=0.6058 valid_loss=0.7027 valid_acc=0.7601 valid_f1=0.6116 lr=6.68e-06 time=82.3s eta=12.3m
no improvement: 1/3
epoch=4/12 train_loss=0.5108 valid_loss=0.7002 valid_acc=0.7565 valid_f1=0.6339 lr=5.94e-06 time=82.1s eta=10.9m
no improvement: 2/3
epoch=5/12 train_loss=0.4547 valid_loss=0.6582 valid_acc=0.7454 valid_f1=0.6553 lr=5.20e-06 time=82.2s eta=9.6m
saved best checkpoint: epoch=5 valid_f1=0.6553
epoch=6/12 train_loss=0.3927 valid_loss=0.6954 valid_acc=0.7712 valid_f1=0.6850 lr=4.46e-06 time=82.2s eta=8.2m
saved best checkpoint: epoch=6 valid_f1=0.6850
epoch=7/12 train_loss=0.3412 valid_loss=0.7453 valid_acc=0.7546 valid_f1=0.6713 lr=3.72e-06 time=82.6s eta=6.9m
no improvement: 1/3
epoch=8/12 train_loss=0.3000 valid_loss=0.7609 valid_acc=0.7620 valid_f1=0.6745 lr=2.98e-06 time=82.3s eta=5.5m
no improvement: 2/3
epoch=9/12 train_loss=0.2631 valid_loss=0.8462 valid_acc=0.7601 valid_f1=0.6679 lr=2.24e-06 time=82.4s eta=4.1m
no improvement: 3/3
early stopping at epoch 9; best epoch was 6
calibration_temperature=1.635161
{
  "validation": {
    "accuracy": 0.7712,
    "precision_macro": 0.6998,
    "recall_macro": 0.6739,
    "macro_f1": 0.685,
    "weighted_f1": 0.7658,
    "roc_auc_macro": 0.8866,
    "average_confidence": 0.7866,
    "expected_calibration_error": 0.0501,
    "temperature": 1.635161,
    "uncalibrated_confidence": 0.877,
    "seen": {
      "samples": 394,
      "accuracy": 0.764,
      "macro_f1": 0.6831
    },
    "unseen": {
      "samples": 148,
      "accuracy": 0.7905,
      "macro_f1": 0.6907
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_cls_neutral125_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_cls_neutral125_split42_seed42 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 22:37:53.659574: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782167873.685839     351 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782167873.692729     351 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782167873.714898     351 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782167873.714937     351 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782167873.714943     351 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782167873.714949     351 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 683,
        "neutral": 542,
        "positive": 1839
      },
      "unique_aspects": 1070
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 155,
      "unseen_aspect_ratio": 0.043
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 124,
        "neutral": 95,
        "positive": 323
      },
      "unique_aspects": 287,
      "unseen_aspect_samples": 155,
      "unseen_aspect_ratio": 0.286
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=0.9704 valid_loss=0.8123 valid_acc=0.6531 valid_f1=0.4473 lr=6.54e-06 time=82.6s eta=15.1m
saved best checkpoint: epoch=1 valid_f1=0.4473
epoch=2/12 train_loss=0.7559 valid_loss=0.6501 valid_acc=0.7528 valid_f1=0.6341 lr=7.42e-06 time=82.5s eta=13.8m
saved best checkpoint: epoch=2 valid_f1=0.6341
epoch=3/12 train_loss=0.6256 valid_loss=0.6116 valid_acc=0.7657 valid_f1=0.6645 lr=6.68e-06 time=82.2s eta=12.3m
saved best checkpoint: epoch=3 valid_f1=0.6645
epoch=4/12 train_loss=0.5327 valid_loss=0.6687 valid_acc=0.7657 valid_f1=0.6633 lr=5.94e-06 time=82.8s eta=11.0m
no improvement: 1/3
epoch=5/12 train_loss=0.4575 valid_loss=0.6372 valid_acc=0.7675 valid_f1=0.6808 lr=5.20e-06 time=81.7s eta=9.5m
saved best checkpoint: epoch=5 valid_f1=0.6808
epoch=6/12 train_loss=0.4017 valid_loss=0.6724 valid_acc=0.7454 valid_f1=0.6667 lr=4.46e-06 time=82.2s eta=8.2m
no improvement: 1/3
epoch=7/12 train_loss=0.3455 valid_loss=0.7292 valid_acc=0.7399 valid_f1=0.6645 lr=3.72e-06 time=82.9s eta=6.9m
no improvement: 2/3
epoch=8/12 train_loss=0.3064 valid_loss=0.8099 valid_acc=0.7620 valid_f1=0.6615 lr=2.98e-06 time=82.4s eta=5.5m
no improvement: 3/3
early stopping at epoch 8; best epoch was 5
calibration_temperature=1.365484
{
  "validation": {
    "accuracy": 0.7675,
    "precision_macro": 0.7042,
    "recall_macro": 0.6691,
    "macro_f1": 0.6808,
    "weighted_f1": 0.7623,
    "roc_auc_macro": 0.8888,
    "average_confidence": 0.7792,
    "expected_calibration_error": 0.0566,
    "temperature": 1.365484,
    "uncalibrated_confidence": 0.842,
    "seen": {
      "samples": 387,
      "accuracy": 0.7597,
      "macro_f1": 0.6781
    },
    "unseen": {
      "samples": 155,
      "accuracy": 0.7871,
      "macro_f1": 0.6871
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_cls_neutral125_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_cls_neutral125_split3407_seed3407 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 22:52:41.067264: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782168761.086966     378 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782168761.093606     378 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782168761.110364     378 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782168761.110412     378 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782168761.110418     378 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782168761.110422     378 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3066,
      "labels": {
        "negative": 687,
        "neutral": 542,
        "positive": 1837
      },
      "unique_aspects": 1065
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 161,
      "unseen_aspect_ratio": 0.0446
    },
    "valid": {
      "samples": 540,
      "labels": {
        "negative": 120,
        "neutral": 95,
        "positive": 325
      },
      "unique_aspects": 290,
      "unseen_aspect_samples": 161,
      "unseen_aspect_ratio": 0.2981
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 368,
      "unseen_aspect_ratio": 0.3286
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=1.0257 valid_loss=0.9121 valid_acc=0.6019 valid_f1=0.2505 lr=6.57e-06 time=81.3s eta=14.9m
saved best checkpoint: epoch=1 valid_f1=0.2505
epoch=2/12 train_loss=0.7494 valid_loss=0.7108 valid_acc=0.7148 valid_f1=0.6143 lr=7.42e-06 time=80.9s eta=13.5m
saved best checkpoint: epoch=2 valid_f1=0.6143
epoch=3/12 train_loss=0.6063 valid_loss=0.7640 valid_acc=0.7519 valid_f1=0.6375 lr=6.68e-06 time=80.9s eta=12.1m
saved best checkpoint: epoch=3 valid_f1=0.6375
epoch=4/12 train_loss=0.5221 valid_loss=0.7268 valid_acc=0.7352 valid_f1=0.6329 lr=5.94e-06 time=81.5s eta=10.9m
no improvement: 1/3
epoch=5/12 train_loss=0.4467 valid_loss=0.8117 valid_acc=0.7556 valid_f1=0.6241 lr=5.20e-06 time=80.4s eta=9.4m
no improvement: 2/3
epoch=6/12 train_loss=0.4014 valid_loss=0.7102 valid_acc=0.7352 valid_f1=0.6513 lr=4.46e-06 time=80.5s eta=8.0m
saved best checkpoint: epoch=6 valid_f1=0.6513
epoch=7/12 train_loss=0.3538 valid_loss=0.7765 valid_acc=0.7407 valid_f1=0.6502 lr=3.72e-06 time=80.9s eta=6.7m
no improvement: 1/3
epoch=8/12 train_loss=0.3128 valid_loss=0.8250 valid_acc=0.7519 valid_f1=0.6564 lr=2.98e-06 time=81.2s eta=5.4m
saved best checkpoint: epoch=8 valid_f1=0.6564
epoch=9/12 train_loss=0.2723 valid_loss=0.8239 valid_acc=0.7648 valid_f1=0.6744 lr=2.24e-06 time=81.2s eta=4.1m
saved best checkpoint: epoch=9 valid_f1=0.6744
epoch=10/12 train_loss=0.2384 valid_loss=0.8398 valid_acc=0.7407 valid_f1=0.6519 lr=1.50e-06 time=80.8s eta=2.7m
no improvement: 1/3
epoch=11/12 train_loss=0.2291 valid_loss=0.8492 valid_acc=0.7481 valid_f1=0.6516 lr=7.56e-07 time=80.4s eta=1.3m
no improvement: 2/3
epoch=12/12 train_loss=0.2141 valid_loss=0.8625 valid_acc=0.7648 valid_f1=0.6721 lr=1.54e-08 time=80.8s eta=0.0m
no improvement: 3/3
early stopping at epoch 12; best epoch was 9
calibration_temperature=1.966303
{
  "validation": {
    "accuracy": 0.7648,
    "precision_macro": 0.6828,
    "recall_macro": 0.6759,
    "macro_f1": 0.6744,
    "weighted_f1": 0.757,
    "roc_auc_macro": 0.8919,
    "average_confidence": 0.7945,
    "expected_calibration_error": 0.078,
    "temperature": 1.966303,
    "uncalibrated_confidence": 0.9206,
    "seen": {
      "samples": 379,
      "accuracy": 0.7467,
      "macro_f1": 0.668
    },
    "unseen": {
      "samples": 161,
      "accuracy": 0.8075,
      "macro_f1": 0.6884
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_cls_neutral125_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_cls_neutral150_split2024_seed2024 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.5 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 23:12:43.156360: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782169963.175240     405 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782169963.181397     405 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782169963.197901     405 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782169963.197965     405 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782169963.197971     405 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782169963.197976     405 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 684,
        "neutral": 541,
        "positive": 1839
      },
      "unique_aspects": 1079
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.041
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 123,
        "neutral": 96,
        "positive": 323
      },
      "unique_aspects": 286,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.2731
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 0.857143,
    "neutral": 1.285714,
    "positive": 0.857143
  }
}
epoch=1/12 train_loss=1.0008 valid_loss=0.8532 valid_acc=0.5959 valid_f1=0.2489 lr=6.61e-06 time=81.1s eta=14.9m
saved best checkpoint: epoch=1 valid_f1=0.2489
epoch=2/12 train_loss=0.7200 valid_loss=0.6571 valid_acc=0.7159 valid_f1=0.6391 lr=7.42e-06 time=80.8s eta=13.5m
saved best checkpoint: epoch=2 valid_f1=0.6391
epoch=3/12 train_loss=0.6026 valid_loss=0.6870 valid_acc=0.7417 valid_f1=0.6342 lr=6.68e-06 time=80.3s eta=12.0m
no improvement: 1/3
epoch=4/12 train_loss=0.5123 valid_loss=0.7132 valid_acc=0.7528 valid_f1=0.6424 lr=5.94e-06 time=81.1s eta=10.8m
saved best checkpoint: epoch=4 valid_f1=0.6424
epoch=5/12 train_loss=0.4437 valid_loss=0.7090 valid_acc=0.7343 valid_f1=0.6522 lr=5.20e-06 time=80.9s eta=9.4m
saved best checkpoint: epoch=5 valid_f1=0.6522
epoch=6/12 train_loss=0.3828 valid_loss=0.7245 valid_acc=0.7454 valid_f1=0.6683 lr=4.46e-06 time=80.5s eta=8.0m
saved best checkpoint: epoch=6 valid_f1=0.6683
epoch=7/12 train_loss=0.3401 valid_loss=0.7694 valid_acc=0.7380 valid_f1=0.6643 lr=3.72e-06 time=80.5s eta=6.7m
no improvement: 1/3
epoch=8/12 train_loss=0.2961 valid_loss=0.7890 valid_acc=0.7509 valid_f1=0.6715 lr=2.98e-06 time=79.7s eta=5.3m
saved best checkpoint: epoch=8 valid_f1=0.6715
epoch=9/12 train_loss=0.2614 valid_loss=0.8713 valid_acc=0.7472 valid_f1=0.6650 lr=2.24e-06 time=86.0s eta=4.3m
no improvement: 1/3
epoch=10/12 train_loss=0.2339 valid_loss=0.8864 valid_acc=0.7565 valid_f1=0.6705 lr=1.50e-06 time=80.4s eta=2.7m
no improvement: 2/3
epoch=11/12 train_loss=0.2201 valid_loss=0.9072 valid_acc=0.7657 valid_f1=0.6716 lr=7.56e-07 time=84.1s eta=1.4m
no improvement: 3/3
early stopping at epoch 11; best epoch was 8
calibration_temperature=1.870475
{
  "validation": {
    "accuracy": 0.7509,
    "precision_macro": 0.6855,
    "recall_macro": 0.6662,
    "macro_f1": 0.6715,
    "weighted_f1": 0.7528,
    "roc_auc_macro": 0.885,
    "average_confidence": 0.7845,
    "expected_calibration_error": 0.0765,
    "temperature": 1.870475,
    "uncalibrated_confidence": 0.9066,
    "seen": {
      "samples": 394,
      "accuracy": 0.7411,
      "macro_f1": 0.6684
    },
    "unseen": {
      "samples": 148,
      "accuracy": 0.777,
      "macro_f1": 0.6793
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_cls_neutral150_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_cls_neutral150_split42_seed42 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.5 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 23:31:34.066250: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782171094.085301     432 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782171094.091483     432 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782171094.107668     432 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782171094.107686     432 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782171094.107688     432 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782171094.107690     432 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 683,
        "neutral": 542,
        "positive": 1839
      },
      "unique_aspects": 1070
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 155,
      "unseen_aspect_ratio": 0.043
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 124,
        "neutral": 95,
        "positive": 323
      },
      "unique_aspects": 287,
      "unseen_aspect_samples": 155,
      "unseen_aspect_ratio": 0.286
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 0.857143,
    "neutral": 1.285714,
    "positive": 0.857143
  }
}
epoch=1/12 train_loss=0.9522 valid_loss=0.7869 valid_acc=0.6458 valid_f1=0.4061 lr=6.54e-06 time=82.7s eta=15.2m
saved best checkpoint: epoch=1 valid_f1=0.4061
epoch=2/12 train_loss=0.7491 valid_loss=0.6541 valid_acc=0.7269 valid_f1=0.6259 lr=7.42e-06 time=82.4s eta=13.7m
saved best checkpoint: epoch=2 valid_f1=0.6259
epoch=3/12 train_loss=0.6334 valid_loss=0.6314 valid_acc=0.7675 valid_f1=0.6610 lr=6.68e-06 time=81.5s eta=12.2m
saved best checkpoint: epoch=3 valid_f1=0.6610
epoch=4/12 train_loss=0.5471 valid_loss=0.6788 valid_acc=0.7565 valid_f1=0.6409 lr=5.94e-06 time=81.9s eta=10.9m
no improvement: 1/3
epoch=5/12 train_loss=0.4726 valid_loss=0.6518 valid_acc=0.7528 valid_f1=0.6605 lr=5.20e-06 time=80.9s eta=9.4m
no improvement: 2/3
epoch=6/12 train_loss=0.4071 valid_loss=0.6629 valid_acc=0.7454 valid_f1=0.6654 lr=4.46e-06 time=81.7s eta=8.2m
saved best checkpoint: epoch=6 valid_f1=0.6654
epoch=7/12 train_loss=0.3572 valid_loss=0.7098 valid_acc=0.7399 valid_f1=0.6645 lr=3.72e-06 time=82.2s eta=6.9m
no improvement: 1/3
epoch=8/12 train_loss=0.3171 valid_loss=0.7630 valid_acc=0.7620 valid_f1=0.6633 lr=2.98e-06 time=81.4s eta=5.4m
no improvement: 2/3
epoch=9/12 train_loss=0.2761 valid_loss=0.8279 valid_acc=0.7509 valid_f1=0.6581 lr=2.24e-06 time=81.3s eta=4.1m
no improvement: 3/3
early stopping at epoch 9; best epoch was 6
calibration_temperature=1.504485
{
  "validation": {
    "accuracy": 0.7454,
    "precision_macro": 0.6755,
    "recall_macro": 0.6641,
    "macro_f1": 0.6654,
    "weighted_f1": 0.7489,
    "roc_auc_macro": 0.8914,
    "average_confidence": 0.7774,
    "expected_calibration_error": 0.0643,
    "temperature": 1.504485,
    "uncalibrated_confidence": 0.859,
    "seen": {
      "samples": 387,
      "accuracy": 0.7519,
      "macro_f1": 0.6802
    },
    "unseen": {
      "samples": 155,
      "accuracy": 0.729,
      "macro_f1": 0.6278
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_cls_neutral150_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_cls_neutral150_split3407_seed3407 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.5 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-22 23:47:37.646538: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782172057.666219     459 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782172057.672575     459 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782172057.688754     459 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782172057.688794     459 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782172057.688800     459 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782172057.688804     459 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3066,
      "labels": {
        "negative": 687,
        "neutral": 542,
        "positive": 1837
      },
      "unique_aspects": 1065
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 161,
      "unseen_aspect_ratio": 0.0446
    },
    "valid": {
      "samples": 540,
      "labels": {
        "negative": 120,
        "neutral": 95,
        "positive": 325
      },
      "unique_aspects": 290,
      "unseen_aspect_samples": 161,
      "unseen_aspect_ratio": 0.2981
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 368,
      "unseen_aspect_ratio": 0.3286
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 0.857143,
    "neutral": 1.285714,
    "positive": 0.857143
  }
}
epoch=1/12 train_loss=1.0063 valid_loss=0.9017 valid_acc=0.6019 valid_f1=0.2505 lr=6.57e-06 time=81.8s eta=15.0m
saved best checkpoint: epoch=1 valid_f1=0.2505
epoch=2/12 train_loss=0.7516 valid_loss=0.7164 valid_acc=0.7167 valid_f1=0.6212 lr=7.42e-06 time=81.9s eta=13.7m
saved best checkpoint: epoch=2 valid_f1=0.6212
epoch=3/12 train_loss=0.6095 valid_loss=0.7593 valid_acc=0.7463 valid_f1=0.6369 lr=6.68e-06 time=82.3s eta=12.3m
saved best checkpoint: epoch=3 valid_f1=0.6369
epoch=4/12 train_loss=0.5309 valid_loss=0.7456 valid_acc=0.7352 valid_f1=0.6327 lr=5.94e-06 time=81.9s eta=10.9m
no improvement: 1/3
epoch=5/12 train_loss=0.4543 valid_loss=0.7779 valid_acc=0.7593 valid_f1=0.6510 lr=5.20e-06 time=81.5s eta=9.5m
saved best checkpoint: epoch=5 valid_f1=0.6510
epoch=6/12 train_loss=0.3971 valid_loss=0.7251 valid_acc=0.7407 valid_f1=0.6599 lr=4.46e-06 time=82.4s eta=8.2m
saved best checkpoint: epoch=6 valid_f1=0.6599
epoch=7/12 train_loss=0.3484 valid_loss=0.7926 valid_acc=0.7481 valid_f1=0.6599 lr=3.71e-06 time=82.0s eta=6.8m
no improvement: 1/3
epoch=8/12 train_loss=0.3047 valid_loss=0.8479 valid_acc=0.7648 valid_f1=0.6707 lr=2.97e-06 time=81.4s eta=5.4m
saved best checkpoint: epoch=8 valid_f1=0.6707
epoch=9/12 train_loss=0.2694 valid_loss=0.8451 valid_acc=0.7519 valid_f1=0.6709 lr=2.23e-06 time=81.9s eta=4.1m
no improvement: 1/3
epoch=10/12 train_loss=0.2349 valid_loss=0.8846 valid_acc=0.7500 valid_f1=0.6623 lr=1.49e-06 time=81.9s eta=2.7m
no improvement: 2/3
epoch=11/12 train_loss=0.2208 valid_loss=0.8865 valid_acc=0.7500 valid_f1=0.6629 lr=7.56e-07 time=82.1s eta=1.4m
no improvement: 3/3
early stopping at epoch 11; best epoch was 8
calibration_temperature=1.882620
{
  "validation": {
    "accuracy": 0.7648,
    "precision_macro": 0.688,
    "recall_macro": 0.6745,
    "macro_f1": 0.6707,
    "weighted_f1": 0.755,
    "roc_auc_macro": 0.8804,
    "average_confidence": 0.785,
    "expected_calibration_error": 0.0641,
    "temperature": 1.88262,
    "uncalibrated_confidence": 0.9105,
    "seen": {
      "samples": 379,
      "accuracy": 0.7467,
      "macro_f1": 0.6654
    },
    "unseen": {
      "samples": 161,
      "accuracy": 0.8075,
      "macro_f1": 0.6821
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_cls_neutral150_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_aspect_attention_neutral125_split2024_seed2024 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-23 00:06:32.973815: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782173192.993450     486 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782173193.000043     486 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782173193.016686     486 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782173193.016728     486 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782173193.016734     486 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782173193.016738     486 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 684,
        "neutral": 541,
        "positive": 1839
      },
      "unique_aspects": 1079
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.041
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 123,
        "neutral": 96,
        "positive": 323
      },
      "unique_aspects": 286,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.2731
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=1.0149 valid_loss=0.8011 valid_acc=0.6494 valid_f1=0.4273 lr=6.61e-06 time=85.4s eta=15.7m
saved best checkpoint: epoch=1 valid_f1=0.4273
epoch=2/12 train_loss=0.7243 valid_loss=0.7545 valid_acc=0.6937 valid_f1=0.5759 lr=7.42e-06 time=85.0s eta=14.2m
saved best checkpoint: epoch=2 valid_f1=0.5759
epoch=3/12 train_loss=0.5623 valid_loss=0.7734 valid_acc=0.7288 valid_f1=0.5741 lr=6.68e-06 time=85.4s eta=12.8m
no improvement: 1/3
epoch=4/12 train_loss=0.4677 valid_loss=0.7280 valid_acc=0.7214 valid_f1=0.6622 lr=5.94e-06 time=84.1s eta=11.2m
saved best checkpoint: epoch=4 valid_f1=0.6622
epoch=5/12 train_loss=0.3811 valid_loss=0.7304 valid_acc=0.7343 valid_f1=0.6659 lr=5.20e-06 time=84.2s eta=9.8m
saved best checkpoint: epoch=5 valid_f1=0.6659
epoch=6/12 train_loss=0.3048 valid_loss=0.7906 valid_acc=0.7509 valid_f1=0.6371 lr=4.46e-06 time=84.4s eta=8.4m
no improvement: 1/3
epoch=7/12 train_loss=0.2588 valid_loss=0.8259 valid_acc=0.7454 valid_f1=0.6631 lr=3.72e-06 time=84.4s eta=7.0m
no improvement: 2/3
epoch=8/12 train_loss=0.2184 valid_loss=0.8598 valid_acc=0.7435 valid_f1=0.6612 lr=2.98e-06 time=84.1s eta=5.6m
no improvement: 3/3
early stopping at epoch 8; best epoch was 5
calibration_temperature=1.574707
{
  "validation": {
    "accuracy": 0.7343,
    "precision_macro": 0.6619,
    "recall_macro": 0.6714,
    "macro_f1": 0.6659,
    "weighted_f1": 0.7387,
    "roc_auc_macro": 0.8622,
    "average_confidence": 0.7514,
    "expected_calibration_error": 0.0576,
    "temperature": 1.574707,
    "uncalibrated_confidence": 0.8442,
    "seen": {
      "samples": 394,
      "accuracy": 0.731,
      "macro_f1": 0.6642
    },
    "unseen": {
      "samples": 148,
      "accuracy": 0.7432,
      "macro_f1": 0.6743
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_aspect_attention_neutral125_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_aspect_attention_neutral125_split42_seed42 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-23 00:21:41.884253: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782174101.903655     513 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782174101.910055     513 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782174101.927431     513 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782174101.927479     513 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782174101.927486     513 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782174101.927490     513 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 683,
        "neutral": 542,
        "positive": 1839
      },
      "unique_aspects": 1070
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 155,
      "unseen_aspect_ratio": 0.043
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 124,
        "neutral": 95,
        "positive": 323
      },
      "unique_aspects": 287,
      "unseen_aspect_samples": 155,
      "unseen_aspect_ratio": 0.286
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=1.0261 valid_loss=0.8132 valid_acc=0.6125 valid_f1=0.3030 lr=6.57e-06 time=85.0s eta=15.6m
saved best checkpoint: epoch=1 valid_f1=0.3030
epoch=2/12 train_loss=0.7297 valid_loss=0.5560 valid_acc=0.7804 valid_f1=0.6954 lr=7.42e-06 time=83.0s eta=13.8m
saved best checkpoint: epoch=2 valid_f1=0.6954
epoch=3/12 train_loss=0.5622 valid_loss=0.5807 valid_acc=0.7786 valid_f1=0.6928 lr=6.68e-06 time=83.1s eta=12.5m
no improvement: 1/3
epoch=4/12 train_loss=0.4533 valid_loss=0.6320 valid_acc=0.7786 valid_f1=0.6779 lr=5.94e-06 time=83.0s eta=11.1m
no improvement: 2/3
epoch=5/12 train_loss=0.3611 valid_loss=0.6527 valid_acc=0.7897 valid_f1=0.7021 lr=5.20e-06 time=82.9s eta=9.7m
saved best checkpoint: epoch=5 valid_f1=0.7021
epoch=6/12 train_loss=0.2969 valid_loss=0.6859 valid_acc=0.7878 valid_f1=0.7130 lr=4.46e-06 time=83.2s eta=8.3m
saved best checkpoint: epoch=6 valid_f1=0.7130
epoch=7/12 train_loss=0.2322 valid_loss=0.7750 valid_acc=0.7860 valid_f1=0.7026 lr=3.72e-06 time=83.8s eta=7.0m
no improvement: 1/3
epoch=8/12 train_loss=0.1958 valid_loss=0.7960 valid_acc=0.7804 valid_f1=0.6923 lr=2.98e-06 time=83.6s eta=5.6m
no improvement: 2/3
epoch=9/12 train_loss=0.1685 valid_loss=0.8097 valid_acc=0.7823 valid_f1=0.7098 lr=2.24e-06 time=85.3s eta=4.3m
no improvement: 3/3
early stopping at epoch 9; best epoch was 6
calibration_temperature=1.736525
{
  "validation": {
    "accuracy": 0.7878,
    "precision_macro": 0.7198,
    "recall_macro": 0.7086,
    "macro_f1": 0.713,
    "weighted_f1": 0.7838,
    "roc_auc_macro": 0.9098,
    "average_confidence": 0.8098,
    "expected_calibration_error": 0.0631,
    "temperature": 1.736525,
    "uncalibrated_confidence": 0.9047,
    "seen": {
      "samples": 387,
      "accuracy": 0.7855,
      "macro_f1": 0.7113
    },
    "unseen": {
      "samples": 155,
      "accuracy": 0.7935,
      "macro_f1": 0.7186
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_aspect_attention_neutral125_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_rest_vi_ablation_core --run-name tune_aspect_attention_neutral125_split3407_seed3407 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-23 00:38:12.430948: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782175092.449698     540 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782175092.455632     540 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782175092.471422     540 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782175092.471447     540 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782175092.471449     540 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782175092.471451     540 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3066,
      "labels": {
        "negative": 687,
        "neutral": 542,
        "positive": 1837
      },
      "unique_aspects": 1065
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 161,
      "unseen_aspect_ratio": 0.0446
    },
    "valid": {
      "samples": 540,
      "labels": {
        "negative": 120,
        "neutral": 95,
        "positive": 325
      },
      "unique_aspects": 290,
      "unseen_aspect_samples": 161,
      "unseen_aspect_ratio": 0.2981
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 368,
      "unseen_aspect_ratio": 0.3286
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=1.0420 valid_loss=0.9103 valid_acc=0.6019 valid_f1=0.2505 lr=6.61e-06 time=84.6s eta=15.5m
saved best checkpoint: epoch=1 valid_f1=0.2505
epoch=2/12 train_loss=0.7192 valid_loss=0.6069 valid_acc=0.7463 valid_f1=0.6607 lr=7.41e-06 time=85.0s eta=14.2m
saved best checkpoint: epoch=2 valid_f1=0.6607
epoch=3/12 train_loss=0.5691 valid_loss=0.6333 valid_acc=0.7611 valid_f1=0.6581 lr=6.68e-06 time=84.3s eta=12.6m
no improvement: 1/3
epoch=4/12 train_loss=0.4240 valid_loss=0.6183 valid_acc=0.7648 valid_f1=0.6913 lr=5.94e-06 time=84.1s eta=11.2m
saved best checkpoint: epoch=4 valid_f1=0.6913
epoch=5/12 train_loss=0.3459 valid_loss=0.6469 valid_acc=0.7778 valid_f1=0.7055 lr=5.20e-06 time=84.0s eta=9.8m
saved best checkpoint: epoch=5 valid_f1=0.7055
epoch=6/12 train_loss=0.2871 valid_loss=0.6837 valid_acc=0.7630 valid_f1=0.6807 lr=4.46e-06 time=83.9s eta=8.4m
no improvement: 1/3
epoch=7/12 train_loss=0.2362 valid_loss=0.7522 valid_acc=0.7944 valid_f1=0.7228 lr=3.72e-06 time=83.7s eta=7.0m
saved best checkpoint: epoch=7 valid_f1=0.7228
epoch=8/12 train_loss=0.2091 valid_loss=0.7428 valid_acc=0.7963 valid_f1=0.7216 lr=2.98e-06 time=83.8s eta=5.6m
no improvement: 1/3
epoch=9/12 train_loss=0.1755 valid_loss=0.7880 valid_acc=0.7852 valid_f1=0.7136 lr=2.24e-06 time=83.8s eta=4.2m
no improvement: 2/3
epoch=10/12 train_loss=0.1596 valid_loss=0.8146 valid_acc=0.7944 valid_f1=0.7202 lr=1.50e-06 time=83.9s eta=2.8m
no improvement: 3/3
early stopping at epoch 10; best epoch was 7
calibration_temperature=1.956226
{
  "validation": {
    "accuracy": 0.7944,
    "precision_macro": 0.738,
    "recall_macro": 0.7118,
    "macro_f1": 0.7228,
    "weighted_f1": 0.7913,
    "roc_auc_macro": 0.9061,
    "average_confidence": 0.8107,
    "expected_calibration_error": 0.0576,
    "temperature": 1.956226,
    "uncalibrated_confidence": 0.926,
    "seen": {
      "samples": 379,
      "accuracy": 0.7757,
      "macro_f1": 0.7215
    },
    "unseen": {
      "samples": 161,
      "accuracy": 0.8385,
      "macro_f1": 0.7166
    }
  },
  "zip": "/kaggle/working/tuning_rest_vi_ablation_core/tune_aspect_attention_neutral125_split3407_seed3407_artifacts.zip"
}
{
  "selection_metric": "mean Macro-F1 minus one standard deviation",
  "search_space": "ablation_core",
  "final_split_seed": 2024,
  "validation_seed_pairs": [
    [
      2024,
      2024
    ],
    [
      42,
      42
    ],
    [
      3407,
      3407
    ]
  ],
  "best_configuration": {
    "name": "hybrid_term",
    "pooling_strategy": "hybrid",
    "input_format": "term",
    "encoder_layer_pooling": "last",
    "encoder_learning_rate": 8e-06,
    "head_learning_rate": 2e-05,
    "dropout": 0.3,
    "class_weighting": "none",
    "neutral_weight_multiplier": 1.0,
    "label_smoothing": 0.02,
    "loss_type": "cross_entropy",
    "scheduler": "linear",
    "warmup_ratio": 0.1,
    "max_length": 128
  },
  "best_validation_summary": {
    "trial": "hybrid_term",
    "mean_macro_f1": 0.694633,
    "std_macro_f1": 0.001676,
    "robust_macro_f1": 0.692957,
    "mean_accuracy": 0.778933,
    "mean_loss": 0.765267,
    "mean_log_loss": 0.5729,
    "mean_ece": 0.048167,
    "validation_seed_pairs": "2024:2024,42:42,3407:3407",
    "pooling_strategy": "hybrid",
    "input_format": "term",
    "encoder_layer_pooling": "last",
    "encoder_learning_rate": 8e-06,
    "head_learning_rate": 2e-05,
    "dropout": 0.3,
    "class_weighting": "none",
    "neutral_weight_multiplier": 1.0,
    "label_smoothing": 0.02,
    "loss_type": "cross_entropy",
    "scheduler": "linear",
    "warmup_ratio": 0.1,
    "max_length": 128
  },
  "ranking": [
    {
      "trial": "hybrid_term",
      "mean_macro_f1": 0.694633,
      "std_macro_f1": 0.001676,
      "robust_macro_f1": 0.692957,
      "mean_accuracy": 0.778933,
      "mean_loss": 0.765267,
      "mean_log_loss": 0.5729,
      "mean_ece": 0.048167,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "hybrid",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.0,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "baseline_cls",
      "mean_macro_f1": 0.681933,
      "std_macro_f1": 0.005967,
      "robust_macro_f1": 0.675967,
      "mean_accuracy": 0.759867,
      "mean_loss": 0.7899,
      "mean_log_loss": 0.5868,
      "mean_ece": 0.069067,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "cls",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.0,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "aspect_attention_neutral125",
      "mean_macro_f1": 0.700567,
      "std_macro_f1": 0.024837,
      "robust_macro_f1": 0.675729,
      "mean_accuracy": 0.772167,
      "mean_loss": 0.722833,
      "mean_log_loss": 0.5646,
      "mean_ece": 0.059433,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "aspect_attention",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.25,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "cls_neutral125",
      "mean_macro_f1": 0.680067,
      "std_macro_f1": 0.004358,
      "robust_macro_f1": 0.675708,
      "mean_accuracy": 0.767833,
      "mean_loss": 0.718833,
      "mean_log_loss": 0.571367,
      "mean_ece": 0.061567,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "cls",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.25,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "aspect_attention_term",
      "mean_macro_f1": 0.691767,
      "std_macro_f1": 0.016481,
      "robust_macro_f1": 0.675285,
      "mean_accuracy": 0.770333,
      "mean_loss": 0.695133,
      "mean_log_loss": 0.560567,
      "mean_ece": 0.05,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "aspect_attention",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.0,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "cls_neutral150",
      "mean_macro_f1": 0.6692,
      "std_macro_f1": 0.002707,
      "robust_macro_f1": 0.666493,
      "mean_accuracy": 0.7537,
      "mean_loss": 0.7666,
      "mean_log_loss": 0.592133,
      "mean_ece": 0.0683,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "cls",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.5,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    }
  ]
}
FINAL RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 15 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/outputs_rest_vi_ablation_core --run-name rest_vi_hybrid_term_seed2024 --evaluation-split test --pooling-strategy hybrid --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing --refit-full-train

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-23 00:56:05.352320: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782176165.371129     567 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782176165.377271     567 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782176165.394023     567 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782176165.394050     567 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782176165.394052     567 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782176165.394055     567 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 684,
        "neutral": 541,
        "positive": 1839
      },
      "unique_aspects": 1079
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.041
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 123,
        "neutral": 96,
        "positive": 323
      },
      "unique_aspects": 286,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.2731
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/15 train_loss=1.0311 valid_loss=0.8532 valid_acc=0.5959 valid_f1=0.2492 lr=5.22e-06 time=84.8s eta=19.8m
saved best checkpoint: epoch=1 valid_f1=0.2492
epoch=2/15 train_loss=0.7581 valid_loss=0.6446 valid_acc=0.7491 valid_f1=0.6546 lr=7.72e-06 time=84.6s eta=18.3m
saved best checkpoint: epoch=2 valid_f1=0.6546
epoch=3/15 train_loss=0.5567 valid_loss=0.6432 valid_acc=0.7417 valid_f1=0.6555 lr=7.12e-06 time=84.4s eta=16.9m
no improvement: 1/3
epoch=4/15 train_loss=0.4529 valid_loss=0.6681 valid_acc=0.7491 valid_f1=0.6547 lr=6.53e-06 time=84.5s eta=15.5m
no improvement: 2/3
epoch=5/15 train_loss=0.3475 valid_loss=0.8211 valid_acc=0.7546 valid_f1=0.6210 lr=5.94e-06 time=83.9s eta=14.0m
no improvement: 3/3
early stopping at epoch 5; best epoch was 2
calibration_temperature=0.982818
refit_epoch=1/2 train_loss=1.0248 lr=5.29e-06 time=96.2s
refit_epoch=2/2 train_loss=0.7132 lr=7.71e-06 time=95.9s
{
  "test": {
    "accuracy": 0.7964,
    "precision_macro": 0.7599,
    "recall_macro": 0.6421,
    "macro_f1": 0.6813,
    "weighted_f1": 0.7789,
    "roc_auc_macro": 0.9048,
    "average_confidence": 0.8438,
    "expected_calibration_error": 0.0582,
    "temperature": 0.982818,
    "uncalibrated_confidence": 0.8412,
    "seen": {
      "samples": 766,
      "accuracy": 0.8146,
      "macro_f1": 0.7047
    },
    "unseen": {
      "samples": 354,
      "accuracy": 0.7571,
      "macro_f1": 0.6248
    }
  },
  "zip": "/kaggle/working/outputs_rest_vi_ablation_core/rest_vi_hybrid_term_seed2024_artifacts.zip"
}
FINAL RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 15 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 42 --output-dir /kaggle/working/outputs_rest_vi_ablation_core --run-name rest_vi_hybrid_term_seed42 --evaluation-split test --pooling-strategy hybrid --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing --refit-full-train

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-23 01:10:24.868050: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782177024.889420     595 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782177024.896342     595 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782177024.914677     595 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782177024.914711     595 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782177024.914714     595 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782177024.914717     595 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 684,
        "neutral": 541,
        "positive": 1839
      },
      "unique_aspects": 1079
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.041
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 123,
        "neutral": 96,
        "positive": 323
      },
      "unique_aspects": 286,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.2731
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/15 train_loss=1.0340 valid_loss=0.8349 valid_acc=0.6255 valid_f1=0.3319 lr=5.25e-06 time=84.7s eta=19.8m
saved best checkpoint: epoch=1 valid_f1=0.3319
epoch=2/15 train_loss=0.7574 valid_loss=0.6435 valid_acc=0.7454 valid_f1=0.6422 lr=7.71e-06 time=84.0s eta=18.2m
saved best checkpoint: epoch=2 valid_f1=0.6422
epoch=3/15 train_loss=0.5696 valid_loss=0.6626 valid_acc=0.7638 valid_f1=0.6784 lr=7.12e-06 time=87.5s eta=17.5m
saved best checkpoint: epoch=3 valid_f1=0.6784
epoch=4/15 train_loss=0.4615 valid_loss=0.7276 valid_acc=0.7694 valid_f1=0.6315 lr=6.53e-06 time=84.3s eta=15.5m
no improvement: 1/3
epoch=5/15 train_loss=0.3819 valid_loss=0.8121 valid_acc=0.7491 valid_f1=0.6422 lr=5.94e-06 time=82.7s eta=13.8m
no improvement: 2/3
epoch=6/15 train_loss=0.2992 valid_loss=0.8022 valid_acc=0.7731 valid_f1=0.6814 lr=5.35e-06 time=82.5s eta=12.4m
saved best checkpoint: epoch=6 valid_f1=0.6814
epoch=7/15 train_loss=0.2374 valid_loss=0.8446 valid_acc=0.7565 valid_f1=0.6729 lr=4.76e-06 time=83.7s eta=11.2m
no improvement: 1/3
epoch=8/15 train_loss=0.2060 valid_loss=0.8565 valid_acc=0.7601 valid_f1=0.6697 lr=4.16e-06 time=82.7s eta=9.6m
no improvement: 2/3
epoch=9/15 train_loss=0.1836 valid_loss=0.9307 valid_acc=0.7694 valid_f1=0.6730 lr=3.57e-06 time=83.2s eta=8.3m
no improvement: 3/3
early stopping at epoch 9; best epoch was 6
calibration_temperature=2.014446
refit_epoch=1/6 train_loss=1.0154 lr=5.29e-06 time=94.6s
refit_epoch=2/6 train_loss=0.7150 lr=7.71e-06 time=95.2s
refit_epoch=3/6 train_loss=0.5389 lr=7.12e-06 time=95.0s
refit_epoch=4/6 train_loss=0.4331 lr=6.53e-06 time=94.7s
refit_epoch=5/6 train_loss=0.3455 lr=5.93e-06 time=95.2s
refit_epoch=6/6 train_loss=0.2822 lr=5.34e-06 time=95.2s
{
  "test": {
    "accuracy": 0.8366,
    "precision_macro": 0.7751,
    "recall_macro": 0.736,
    "macro_f1": 0.7463,
    "weighted_f1": 0.8265,
    "roc_auc_macro": 0.9283,
    "average_confidence": 0.8085,
    "expected_calibration_error": 0.0381,
    "temperature": 2.014446,
    "uncalibrated_confidence": 0.935,
    "seen": {
      "samples": 766,
      "accuracy": 0.8525,
      "macro_f1": 0.7639
    },
    "unseen": {
      "samples": 354,
      "accuracy": 0.8023,
      "macro_f1": 0.7065
    }
  },
  "zip": "/kaggle/working/outputs_rest_vi_ablation_core/rest_vi_hybrid_term_seed42_artifacts.zip"
}
FINAL RUN: /usr/bin/python3 train.py --dataset rest_vi --model microsoft/mdeberta-v3-base --epochs 15 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 3407 --output-dir /kaggle/working/outputs_rest_vi_ablation_core --run-name rest_vi_hybrid_term_seed3407 --evaluation-split test --pooling-strategy hybrid --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing --refit-full-train

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-23 01:36:29.319145: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782178589.339033     623 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782178589.345762     623 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782178589.362990     623 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782178589.363010     623 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782178589.363013     623 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782178589.363016     623 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 3064,
      "labels": {
        "negative": 684,
        "neutral": 541,
        "positive": 1839
      },
      "unique_aspects": 1079
    },
    "train_all": {
      "samples": 3606,
      "labels": {
        "negative": 807,
        "neutral": 637,
        "positive": 2162
      },
      "unique_aspects": 1223,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.041
    },
    "valid": {
      "samples": 542,
      "labels": {
        "negative": 123,
        "neutral": 96,
        "positive": 323
      },
      "unique_aspects": 286,
      "unseen_aspect_samples": 148,
      "unseen_aspect_ratio": 0.2731
    },
    "test": {
      "samples": 1120,
      "labels": {
        "negative": 196,
        "neutral": 196,
        "positive": 728
      },
      "unique_aspects": 524,
      "unseen_aspect_samples": 362,
      "unseen_aspect_ratio": 0.3232
    },
    "excluded_train_test_overlap": {
      "samples": 2,
      "labels": {
        "positive": 2
      },
      "unique_aspects": 2,
      "unseen_aspect_samples": 1,
      "unseen_aspect_ratio": 0.5
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/15 train_loss=1.1222 valid_loss=0.7970 valid_acc=0.6679 valid_f1=0.4440 lr=5.28e-06 time=83.5s eta=19.5m
saved best checkpoint: epoch=1 valid_f1=0.4440
epoch=2/15 train_loss=0.7115 valid_loss=0.6795 valid_acc=0.7620 valid_f1=0.6092 lr=7.71e-06 time=83.2s eta=18.0m
saved best checkpoint: epoch=2 valid_f1=0.6092
epoch=3/15 train_loss=0.5342 valid_loss=0.6516 valid_acc=0.7749 valid_f1=0.6839 lr=7.12e-06 time=82.4s eta=16.5m
saved best checkpoint: epoch=3 valid_f1=0.6839
epoch=4/15 train_loss=0.4298 valid_loss=0.6674 valid_acc=0.7657 valid_f1=0.6661 lr=6.53e-06 time=83.5s eta=15.3m
no improvement: 1/3
epoch=5/15 train_loss=0.3281 valid_loss=0.7130 valid_acc=0.7638 valid_f1=0.6762 lr=5.94e-06 time=82.8s eta=13.8m
no improvement: 2/3
epoch=6/15 train_loss=0.2696 valid_loss=0.8037 valid_acc=0.7731 valid_f1=0.6659 lr=5.35e-06 time=82.7s eta=12.4m
no improvement: 3/3
early stopping at epoch 6; best epoch was 3
calibration_temperature=1.454474
refit_epoch=1/3 train_loss=1.0903 lr=5.26e-06 time=95.3s
refit_epoch=2/3 train_loss=0.7041 lr=7.71e-06 time=95.3s
refit_epoch=3/3 train_loss=0.5484 lr=7.12e-06 time=94.7s
{
  "test": {
    "accuracy": 0.808,
    "precision_macro": 0.7364,
    "recall_macro": 0.6915,
    "macro_f1": 0.6886,
    "weighted_f1": 0.7883,
    "roc_auc_macro": 0.9152,
    "average_confidence": 0.8315,
    "expected_calibration_error": 0.0237,
    "temperature": 1.454474,
    "uncalibrated_confidence": 0.8953,
    "seen": {
      "samples": 766,
      "accuracy": 0.8264,
      "macro_f1": 0.7006
    },
    "unseen": {
      "samples": 354,
      "accuracy": 0.7684,
      "macro_f1": 0.6538
    }
  },
  "zip": "/kaggle/working/outputs_rest_vi_ablation_core/rest_vi_hybrid_term_seed3407_artifacts.zip"
}

CompletedProcess(args=['/usr/bin/python3', 'tune.py', '--dataset', 'rest_vi', '--model', 'microsoft/mdeberta-v3-base', '--search-space', 'ablation_core', '--validation-seed-pairs', '2024:2024,42:42,3407:3407', '--valid-ratio', '0.15', '--final-seeds', '2024,42,3407', '--epochs', '12', '--final-epochs', '15', '--patience', '3', '--batch-size', '8', '--gradient-accumulation-steps', '2', '--amp', '--gradient-checkpointing', '--run-final', '--output-dir', '/kaggle/working/tuning_rest_vi_ablation_core', '--final-output-dir', '/kaggle/working/outputs_rest_vi_ablation_core'], returncode=0)

## 5. Tổng hợp kết quả

Bảng đầu là kết quả validation ablation; bảng sau là kết quả official test của cấu hình thắng.

In [6]:
import pandas as pd

summary_path = CORE_TUNING / 'tuning_summary.csv'
final_path = CORE_FINAL / 'final_runs_summary.csv'
meanstd_path = CORE_FINAL / 'final_metrics_mean_std.json'
selection_path = CORE_TUNING / 'selected_configuration.json'

summary = pd.read_csv(summary_path)
cols = [c for c in ['trial','mean_macro_f1','std_macro_f1','robust_macro_f1','mean_accuracy','mean_ece','pooling_strategy','neutral_weight_multiplier'] if c in summary.columns]
display(summary[cols])

if selection_path.exists():
    print('Selected configuration:')
    print(json.dumps(json.loads(selection_path.read_text()), indent=2))
if final_path.exists():
    display(pd.read_csv(final_path))
if meanstd_path.exists():
    print('Final mean/std:')
    print(json.dumps(json.loads(meanstd_path.read_text()), indent=2))

,trial,mean_macro_f1,std_macro_f1,robust_macro_f1,mean_accuracy,mean_ece,pooling_strategy,neutral_weight_multiplier
0,hybrid_term,0.694633,0.001676,0.692957,0.778933,0.048167,hybrid,1.00
1,baseline_cls,0.681933,0.005967,0.675967,0.759867,0.069067,cls,1.00
2,aspect_attention_neutral125,0.700567,0.024837,0.675729,0.772167,0.059433,aspect_attention,1.25
3,cls_neutral125,0.680067,0.004358,0.675708,0.767833,0.061567,cls,1.25
4,aspect_attention_term,0.691767,0.016481,0.675285,0.770333,0.050000,aspect_attention,1.00
5,cls_neutral150,0.669200,0.002707,0.666493,0.753700,0.068300,cls,1.50

Selected configuration:
{
  "selection_metric": "mean Macro-F1 minus one standard deviation",
  "search_space": "ablation_core",
  "final_split_seed": 2024,
  "validation_seed_pairs": [
    [
      2024,
      2024
    ],
    [
      42,
      42
    ],
    [
      3407,
      3407
    ]
  ],
  "best_configuration": {
    "name": "hybrid_term",
    "pooling_strategy": "hybrid",
    "input_format": "term",
    "encoder_layer_pooling": "last",
    "encoder_learning_rate": 8e-06,
    "head_learning_rate": 2e-05,
    "dropout": 0.3,
    "class_weighting": "none",
    "neutral_weight_multiplier": 1.0,
    "label_smoothing": 0.02,
    "loss_type": "cross_entropy",
    "scheduler": "linear",
    "warmup_ratio": 0.1,
    "max_length": 128
  },
  "best_validation_summary": {
    "trial": "hybrid_term",
    "mean_macro_f1": 0.694633,
    "std_macro_f1": 0.001676,
    "robust_macro_f1": 0.692957,
    "mean_accuracy": 0.778933,
    "mean_loss": 0.765267,
    "mean_log_loss": 0.5729,
    "mean_ece": 0.048167,
    "validation_seed_pairs": "2024:2024,42:42,3407:3407",
    "pooling_strategy": "hybrid",
    "input_format": "term",
    "encoder_layer_pooling": "last",
    "encoder_learning_rate": 8e-06,
    "head_learning_rate": 2e-05,
    "dropout": 0.3,
    "class_weighting": "none",
    "neutral_weight_multiplier": 1.0,
    "label_smoothing": 0.02,
    "loss_type": "cross_entropy",
    "scheduler": "linear",
    "warmup_ratio": 0.1,
    "max_length": 128
  },
  "ranking": [
    {
      "trial": "hybrid_term",
      "mean_macro_f1": 0.694633,
      "std_macro_f1": 0.001676,
      "robust_macro_f1": 0.692957,
      "mean_accuracy": 0.778933,
      "mean_loss": 0.765267,
      "mean_log_loss": 0.5729,
      "mean_ece": 0.048167,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "hybrid",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.0,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "baseline_cls",
      "mean_macro_f1": 0.681933,
      "std_macro_f1": 0.005967,
      "robust_macro_f1": 0.675967,
      "mean_accuracy": 0.759867,
      "mean_loss": 0.7899,
      "mean_log_loss": 0.5868,
      "mean_ece": 0.069067,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "cls",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.0,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "aspect_attention_neutral125",
      "mean_macro_f1": 0.700567,
      "std_macro_f1": 0.024837,
      "robust_macro_f1": 0.675729,
      "mean_accuracy": 0.772167,
      "mean_loss": 0.722833,
      "mean_log_loss": 0.5646,
      "mean_ece": 0.059433,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "aspect_attention",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.25,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "cls_neutral125",
      "mean_macro_f1": 0.680067,
      "std_macro_f1": 0.004358,
      "robust_macro_f1": 0.675708,
      "mean_accuracy": 0.767833,
      "mean_loss": 0.718833,
      "mean_log_loss": 0.571367,
      "mean_ece": 0.061567,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "cls",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.25,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "aspect_attention_term",
      "mean_macro_f1": 0.691767,
      "std_macro_f1": 0.016481,
      "robust_macro_f1": 0.675285,
      "mean_accuracy": 0.770333,
      "mean_loss": 0.695133,
      "mean_log_loss": 0.560567,
      "mean_ece": 0.05,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "aspect_attention",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.0,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "cls_neutral150",
      "mean_macro_f1": 0.6692,
      "std_macro_f1": 0.002707,
      "robust_macro_f1": 0.666493,
      "mean_accuracy": 0.7537,
      "mean_loss": 0.7666,
      "mean_log_loss": 0.592133,
      "mean_ece": 0.0683,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "cls",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.5,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    }
  ]
}

,seed,best_epoch,accuracy,precision_macro,recall_macro,macro_f1,weighted_f1,roc_auc_macro,log_loss,expected_calibration_error,temperature
0,2024,2,0.7964,0.7599,0.6421,0.6813,0.7789,0.9048,0.5372,0.0582,0.982818
1,42,6,0.8366,0.7751,0.7360,0.7463,0.8265,0.9283,0.4655,0.0381,2.014446
2,3407,3,0.8080,0.7364,0.6915,0.6886,0.7883,0.9152,0.4865,0.0237,1.454474

Final mean/std:
{
  "accuracy": {
    "mean": 0.813667,
    "std": 0.016894
  },
  "precision_macro": {
    "mean": 0.757133,
    "std": 0.01592
  },
  "recall_macro": {
    "mean": 0.689867,
    "std": 0.038352
  },
  "macro_f1": {
    "mean": 0.7054,
    "std": 0.029074
  },
  "weighted_f1": {
    "mean": 0.7979,
    "std": 0.020584
  },
  "roc_auc_macro": {
    "mean": 0.9161,
    "std": 0.009615
  },
  "log_loss": {
    "mean": 0.4964,
    "std": 0.030097
  },
  "expected_calibration_error": {
    "mean": 0.04,
    "std": 0.014148
  }
}

## 6. Ghi chú về aspect description

`aspects.json` của bản dịch chủ yếu lưu thống kê và term nguồn; trường description đang rỗng. Vì vậy notebook chỉ chạy core ablation với raw aspect term. Không chạy `ablation_desc` cho đến khi có mô tả tiếng Việt được kiểm tra.

In [7]:
aspect_info = json.loads(Path('dataset/rest_vi/aspects.json').read_text(encoding='utf-8'))
non_empty_descriptions = sum(bool(item.get('description', '').strip()) for item in aspect_info.values())
print('Unique translated aspects:', len(aspect_info))
print('Non-empty Vietnamese descriptions:', non_empty_descriptions)
assert non_empty_descriptions == 0, 'Nếu đã bổ sung description, có thể chạy ablation_desc riêng.'

Unique translated aspects: 1562
Non-empty Vietnamese descriptions: 0

## 7. Đóng gói kết quả

Checkpoint và ZIP artifact lồng nhau bị loại mặc định để file kết quả nhỏ hơn. JSON, CSV, prediction và biểu đồ vẫn được giữ.

In [8]:
INCLUDE_CHECKPOINTS = False
folders = [CORE_TUNING, CORE_FINAL]

with zipfile.ZipFile(RESULT_ZIP, 'w', compression=zipfile.ZIP_DEFLATED) as zf:
    for folder in folders:
        if not folder.exists():
            continue
        for path in folder.rglob('*'):
            if not path.is_file():
                continue
            if not INCLUDE_CHECKPOINTS and path.suffix in {'.pt', '.pth', '.bin', '.safetensors'}:
                continue
            if path.name.endswith('_artifacts.zip'):
                continue
            zf.write(path, path.relative_to(WORK))

print('Created:', RESULT_ZIP)
print('Size MB:', round(RESULT_ZIP.stat().st_size / 1024 / 1024, 2))

Created: /kaggle/working/absa_rest_vi_results_fresh.zip
Size MB: 9.3