# ABSA Laptop — Clean Ablation Training

Notebook này huấn luyện lại pipeline ABSA hiện tại trên dataset **Laptop**, giữ nguyên logic tuning, ablation, early stopping, refit và đánh giá như thực nghiệm Restaurant.

Trước khi chạy:

1. Upload `absa_laptop_ablation_fresh.zip` thành Kaggle Dataset.
2. Gắn Dataset đó vào notebook.
3. Bật GPU và Internet.
4. Chạy toàn bộ cell theo thứ tự.

In [1]:
from pathlib import Path
import os, shutil, zipfile, json, subprocess, sys

print('Python:', sys.version)
print('Kaggle working exists:', Path('/kaggle/working').exists())
try:
    subprocess.run(['nvidia-smi'], check=False)
except FileNotFoundError:
    print('nvidia-smi not found; GPU may be disabled.')

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Kaggle working exists: True
Sun Jun 21 15:05:09 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.159.04             Driver Version: 580.159.04     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla T4                       Off |   00000000:00:05.0 Off |                    0 |
| N/A   45C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

## 1. Giải nén package và tạo trạng thái clean-start

Mọi output của lần chạy cũ trong `/kaggle/working` được xóa trước khi bắt đầu.

In [2]:
WORK = Path('/kaggle/working') if Path('/kaggle/working').exists() else Path.cwd()
INPUT = Path('/kaggle/input/datasets/banhbaogachcua/nlp-lap-update')
PROJECT = WORK / 'absa_laptop_ablation_fresh'

CORE_TUNING = WORK / 'tuning_laptop_ablation_core'
CORE_FINAL = WORK / 'outputs_laptop_ablation_core'
DESC_TUNING = WORK / 'tuning_laptop_ablation_desc'
DESC_FINAL = WORK / 'outputs_laptop_ablation_desc'
RESULT_ZIP = WORK / 'absa_laptop_results_fresh.zip'

CLEAN_RUN = True
if CLEAN_RUN:
    for path in [PROJECT, CORE_TUNING, CORE_FINAL, DESC_TUNING, DESC_FINAL, RESULT_ZIP]:
        if path.exists():
            print('Removing old:', path)
            if path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink()

if not INPUT.exists():
    raise FileNotFoundError(f'Không tìm thấy Kaggle Input: {INPUT}')

zip_candidates = list(INPUT.rglob('absa_laptop_ablation_fresh.zip'))
if not zip_candidates:
    zip_candidates = list(INPUT.rglob('*laptop*ablation*.zip'))

if zip_candidates:
    zip_path = zip_candidates[0]
    print('Extracting ZIP:', zip_path)
    PROJECT.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(PROJECT)
else:
    # Kaggle thường tự giải nén file ZIP khi tạo Dataset. Khi đó copy trực tiếp
    # thư mục chứa train.py thay vì yêu cầu file ZIP còn tồn tại.
    train_candidates = list(INPUT.rglob('train.py'))
    if not train_candidates:
        visible = [str(path.relative_to(INPUT)) for path in INPUT.rglob('*') if path.is_file()][:50]
        raise FileNotFoundError(
            'Không tìm thấy ZIP hoặc train.py trong Kaggle Input. '
            f'Các file nhìn thấy: {visible}'
        )
    source_dir = train_candidates[0].parent
    print('Copying extracted source:', source_dir)
    shutil.copytree(source_dir, PROJECT, dirs_exist_ok=True)

if not (PROJECT / 'train.py').exists():
    candidates = list(PROJECT.rglob('train.py'))
    if not candidates:
        raise FileNotFoundError('Đã giải nén nhưng không tìm thấy train.py')
    PROJECT = candidates[0].parent

print('PROJECT =', PROJECT)
print('Files:', sorted(p.name for p in PROJECT.iterdir()))

Copying extracted source: /kaggle/input/datasets/banhbaogachcua/nlp-lap-update
PROJECT = /kaggle/working/absa_laptop_ablation_fresh
Files: ['CLEAN_START.md', 'PATCH_NOTES.md', 'absa_pipeline.py', 'dataset', 'kaggle_laptop_ablation_fresh.ipynb', 'requirements.txt', 'train.py', 'tune.py']

## 2. Cài đặt thư viện

In [3]:
os.chdir(PROJECT)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--upgrade', 'pip'], check=True)
subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '-r', 'requirements.txt'], check=True)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 22.8 MB/s eta 0:00:00

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.

CompletedProcess(args=['/usr/bin/python3', '-m', 'pip', 'install', '-q', '-r', 'requirements.txt'], returncode=0)

## 3. Kiểm tra package và dataset Laptop

In [4]:
os.chdir(PROJECT)
required = [
    Path('train.py'), Path('tune.py'), Path('absa_pipeline.py'),
    Path('dataset/lap/train.multiple.json'),
    Path('dataset/lap/test.multiple.json'),
    Path('dataset/lap/aspects.json'),
]
missing = [str(path) for path in required if not path.exists()]
assert not missing, f'Thiếu file bắt buộc: {missing}'

forbidden_suffixes = {'.pt', '.pth', '.bin', '.safetensors'}
forbidden_dirs = {'outputs', 'runs', 'logs', 'wandb', '__pycache__'}
history_files = [
    str(path.relative_to(PROJECT)) for path in PROJECT.rglob('*')
    if path.suffix in forbidden_suffixes or any(part in forbidden_dirs for part in path.parts)
]
assert not history_files, f'Package chứa checkpoint/output cũ: {history_files[:20]}'

from collections import Counter
for split in ['train', 'test']:
    rows = json.loads(Path(f'dataset/lap/{split}.multiple.json').read_text(encoding='utf-8'))
    aspects = [a for row in rows for a in row.get('aspects', []) if a.get('polarity') in {'negative','neutral','positive'}]
    print(split, 'sentences=', len(rows), 'aspect_samples=', len(aspects), 'labels=', dict(Counter(a['polarity'] for a in aspects)))

subprocess.run([sys.executable, 'tune.py', '--help'], check=False)

train sentences= 1466 aspect_samples= 2328 labels= {'neutral': 464, 'positive': 994, 'negative': 870}
test sentences= 411 aspect_samples= 638 labels= {'positive': 341, 'negative': 128, 'neutral': 169}
usage: tune.py [-h] [--dataset {lap,rest,twi}] [--model MODEL]
               [--epochs EPOCHS] [--final-epochs FINAL_EPOCHS]
               [--patience PATIENCE] [--batch-size BATCH_SIZE]
               [--gradient-accumulation-steps GRADIENT_ACCUMULATION_STEPS]
               [--weight-decay WEIGHT_DECAY] [--valid-ratio VALID_RATIO]
               [--split-seed SPLIT_SEED] [--tuning-seeds TUNING_SEEDS]
               [--validation-seed-pairs VALIDATION_SEED_PAIRS]
               [--final-seeds FINAL_SEEDS] [--output-dir OUTPUT_DIR]
               [--final-output-dir FINAL_OUTPUT_DIR] [--amp]
               [--gradient-checkpointing] [--run-final]
               [--keep-trial-checkpoints] [--resume]
               [--search-space {ablation_all,ablation_core,ablation_desc,initial,refined}]
               [--trials TRIALS]

Select ABSA hyperparameters using validation Macro-F1

options:
  -h, --help            show this help message and exit
  --dataset {lap,rest,twi}
  --model MODEL
  --epochs EPOCHS
  --final-epochs FINAL_EPOCHS
  --patience PATIENCE
  --batch-size BATCH_SIZE
  --gradient-accumulation-steps GRADIENT_ACCUMULATION_STEPS
  --weight-decay WEIGHT_DECAY
  --valid-ratio VALID_RATIO
  --split-seed SPLIT_SEED
  --tuning-seeds TUNING_SEEDS
  --validation-seed-pairs VALIDATION_SEED_PAIRS
                        Comma-separated split_seed:model_seed pairs.
  --final-seeds FINAL_SEEDS
  --output-dir OUTPUT_DIR
  --final-output-dir FINAL_OUTPUT_DIR
  --amp
  --gradient-checkpointing
  --run-final
  --keep-trial-checkpoints
  --resume
  --search-space {ablation_all,ablation_core,ablation_desc,initial,refined}
  --trials TRIALS       Comma-separated trial names or 'all'.

CompletedProcess(args=['/usr/bin/python3', 'tune.py', '--help'], returncode=0)

## 4. Chạy core ablation trên Laptop

Giữ nguyên sáu trial và hyperparameter như thực nghiệm Restaurant. Tổng cộng có 18 validation run và 3 final run.

Nếu GPU hết bộ nhớ, đặt `BATCH_SIZE = 4` và `GRAD_ACCUM = 4`.

In [5]:
os.chdir(PROJECT)

VALID_RATIO = 0.15
BATCH_SIZE = 8
GRAD_ACCUM = 2
EPOCHS = 12
FINAL_EPOCHS = 15
SEED_PAIRS = '2024:2024,42:42,3407:3407'
FINAL_SEEDS = '2024,42,3407'

cmd = [
    sys.executable, 'tune.py',
    '--dataset', 'lap',
    '--search-space', 'ablation_core',
    '--validation-seed-pairs', SEED_PAIRS,
    '--valid-ratio', str(VALID_RATIO),
    '--final-seeds', FINAL_SEEDS,
    '--epochs', str(EPOCHS),
    '--final-epochs', str(FINAL_EPOCHS),
    '--patience', '3',
    '--batch-size', str(BATCH_SIZE),
    '--gradient-accumulation-steps', str(GRAD_ACCUM),
    '--amp',
    '--gradient-checkpointing',
    '--run-final',
    '--output-dir', str(CORE_TUNING),
    '--final-output-dir', str(CORE_FINAL),
]
print(' '.join(cmd))
subprocess.run(cmd, check=True)

/usr/bin/python3 tune.py --dataset lap --search-space ablation_core --validation-seed-pairs 2024:2024,42:42,3407:3407 --valid-ratio 0.15 --final-seeds 2024,42,3407 --epochs 12 --final-epochs 15 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --amp --gradient-checkpointing --run-final --output-dir /kaggle/working/tuning_laptop_ablation_core --final-output-dir /kaggle/working/outputs_laptop_ablation_core
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_baseline_cls_split2024_seed2024 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 15:06:09.550930: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782054369.947191      63 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782054370.052579      63 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782054371.019159      63 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782054371.019196      63 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782054371.019200      63 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782054371.019202      63 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1978,
      "labels": {
        "negative": 743,
        "neutral": 393,
        "positive": 842
      },
      "unique_aspects": 844
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 349,
      "labels": {
        "negative": 127,
        "neutral": 70,
        "positive": 152
      },
      "unique_aspects": 212,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3209
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 283,
      "unseen_aspect_ratio": 0.4436
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.1048 valid_loss=0.9039 valid_acc=0.6705 valid_f1=0.4958 lr=6.55e-06 time=50.5s eta=9.3m
saved best checkpoint: epoch=1 valid_f1=0.4958
epoch=2/12 train_loss=0.7255 valid_loss=0.5550 valid_acc=0.8109 valid_f1=0.7352 lr=7.42e-06 time=47.4s eta=7.9m
saved best checkpoint: epoch=2 valid_f1=0.7352
epoch=3/12 train_loss=0.5562 valid_loss=0.5806 valid_acc=0.7966 valid_f1=0.6964 lr=6.68e-06 time=47.2s eta=7.1m
no improvement: 1/3
epoch=4/12 train_loss=0.4241 valid_loss=0.5331 valid_acc=0.7794 valid_f1=0.7270 lr=5.94e-06 time=46.6s eta=6.2m
no improvement: 2/3
epoch=5/12 train_loss=0.3374 valid_loss=0.5910 valid_acc=0.8109 valid_f1=0.7541 lr=5.20e-06 time=46.9s eta=5.5m
saved best checkpoint: epoch=5 valid_f1=0.7541
epoch=6/12 train_loss=0.2851 valid_loss=0.6503 valid_acc=0.8109 valid_f1=0.7562 lr=4.46e-06 time=47.0s eta=4.7m
saved best checkpoint: epoch=6 valid_f1=0.7562
epoch=7/12 train_loss=0.2452 valid_loss=0.7168 valid_acc=0.8109 valid_f1=0.7533 lr=3.72e-06 time=46.8s eta=3.9m
no improvement: 1/3
epoch=8/12 train_loss=0.2055 valid_loss=0.7345 valid_acc=0.7851 valid_f1=0.7374 lr=2.98e-06 time=46.5s eta=3.1m
no improvement: 2/3
epoch=9/12 train_loss=0.1860 valid_loss=0.7467 valid_acc=0.7966 valid_f1=0.7454 lr=2.23e-06 time=47.1s eta=2.4m
no improvement: 3/3
early stopping at epoch 9; best epoch was 6
calibration_temperature=1.737548
{
  "validation": {
    "accuracy": 0.8109,
    "precision_macro": 0.7693,
    "recall_macro": 0.752,
    "macro_f1": 0.7562,
    "weighted_f1": 0.802,
    "roc_auc_macro": 0.9149,
    "average_confidence": 0.8229,
    "expected_calibration_error": 0.0435,
    "temperature": 1.737548,
    "uncalibrated_confidence": 0.9129,
    "seen": {
      "samples": 237,
      "accuracy": 0.8312,
      "macro_f1": 0.7839
    },
    "unseen": {
      "samples": 112,
      "accuracy": 0.7679,
      "macro_f1": 0.6867
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_baseline_cls_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_baseline_cls_split42_seed42 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 15:15:51.417708: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782054951.437312     108 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782054951.443846     108 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782054951.460470     108 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782054951.460492     108 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782054951.460495     108 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782054951.460497     108 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1976,
      "labels": {
        "negative": 739,
        "neutral": 392,
        "positive": 845
      },
      "unique_aspects": 845
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 105,
      "unseen_aspect_ratio": 0.0451
    },
    "valid": {
      "samples": 351,
      "labels": {
        "negative": 131,
        "neutral": 71,
        "positive": 149
      },
      "unique_aspects": 220,
      "unseen_aspect_samples": 105,
      "unseen_aspect_ratio": 0.2991
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 278,
      "unseen_aspect_ratio": 0.4357
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.1121 valid_loss=0.8505 valid_acc=0.7322 valid_f1=0.5432 lr=6.55e-06 time=48.4s eta=8.9m
saved best checkpoint: epoch=1 valid_f1=0.5432
epoch=2/12 train_loss=0.6598 valid_loss=0.5830 valid_acc=0.7607 valid_f1=0.7138 lr=7.43e-06 time=47.2s eta=7.9m
saved best checkpoint: epoch=2 valid_f1=0.7138
epoch=3/12 train_loss=0.4980 valid_loss=0.5653 valid_acc=0.7692 valid_f1=0.7267 lr=6.69e-06 time=46.9s eta=7.0m
saved best checkpoint: epoch=3 valid_f1=0.7267
epoch=4/12 train_loss=0.3942 valid_loss=0.5969 valid_acc=0.7521 valid_f1=0.7186 lr=5.94e-06 time=46.9s eta=6.3m
no improvement: 1/3
epoch=5/12 train_loss=0.3369 valid_loss=0.6117 valid_acc=0.8006 valid_f1=0.7416 lr=5.20e-06 time=46.6s eta=5.4m
saved best checkpoint: epoch=5 valid_f1=0.7416
epoch=6/12 train_loss=0.2794 valid_loss=0.6376 valid_acc=0.7778 valid_f1=0.7316 lr=4.46e-06 time=46.8s eta=4.7m
no improvement: 1/3
epoch=7/12 train_loss=0.2571 valid_loss=0.7247 valid_acc=0.7749 valid_f1=0.7443 lr=3.72e-06 time=46.4s eta=3.9m
saved best checkpoint: epoch=7 valid_f1=0.7443
epoch=8/12 train_loss=0.2146 valid_loss=0.7264 valid_acc=0.7835 valid_f1=0.7494 lr=2.98e-06 time=46.8s eta=3.1m
saved best checkpoint: epoch=8 valid_f1=0.7494
epoch=9/12 train_loss=0.1880 valid_loss=0.7838 valid_acc=0.8091 valid_f1=0.7661 lr=2.24e-06 time=46.4s eta=2.3m
saved best checkpoint: epoch=9 valid_f1=0.7661
epoch=10/12 train_loss=0.1807 valid_loss=0.7697 valid_acc=0.7949 valid_f1=0.7555 lr=1.50e-06 time=46.4s eta=1.5m
no improvement: 1/3
epoch=11/12 train_loss=0.1693 valid_loss=0.7919 valid_acc=0.7778 valid_f1=0.7414 lr=7.59e-07 time=46.2s eta=0.8m
no improvement: 2/3
epoch=12/12 train_loss=0.1629 valid_loss=0.7871 valid_acc=0.8006 valid_f1=0.7640 lr=1.79e-08 time=46.2s eta=0.0m
no improvement: 3/3
early stopping at epoch 12; best epoch was 9
calibration_temperature=2.076596
{
  "validation": {
    "accuracy": 0.8091,
    "precision_macro": 0.7787,
    "recall_macro": 0.7638,
    "macro_f1": 0.7661,
    "weighted_f1": 0.8048,
    "roc_auc_macro": 0.9145,
    "average_confidence": 0.8216,
    "expected_calibration_error": 0.0315,
    "temperature": 2.076596,
    "uncalibrated_confidence": 0.9422,
    "seen": {
      "samples": 246,
      "accuracy": 0.8211,
      "macro_f1": 0.7747
    },
    "unseen": {
      "samples": 105,
      "accuracy": 0.781,
      "macro_f1": 0.742
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_baseline_cls_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_baseline_cls_split3407_seed3407 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 15:27:28.516599: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782055648.534690     135 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782055648.541008     135 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782055648.556857     135 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782055648.556878     135 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782055648.556880     135 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782055648.556882     135 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1976,
      "labels": {
        "negative": 738,
        "neutral": 393,
        "positive": 845
      },
      "unique_aspects": 843
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 351,
      "labels": {
        "negative": 132,
        "neutral": 70,
        "positive": 149
      },
      "unique_aspects": 221,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3191
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 276,
      "unseen_aspect_ratio": 0.4326
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.1152 valid_loss=0.9522 valid_acc=0.5556 valid_f1=0.3880 lr=6.60e-06 time=46.2s eta=8.5m
saved best checkpoint: epoch=1 valid_f1=0.3880
epoch=2/12 train_loss=0.6765 valid_loss=0.5545 valid_acc=0.7863 valid_f1=0.7097 lr=7.42e-06 time=45.3s eta=7.5m
saved best checkpoint: epoch=2 valid_f1=0.7097
epoch=3/12 train_loss=0.4980 valid_loss=0.5302 valid_acc=0.8205 valid_f1=0.7619 lr=6.69e-06 time=45.3s eta=6.8m
saved best checkpoint: epoch=3 valid_f1=0.7619
epoch=4/12 train_loss=0.3986 valid_loss=0.5322 valid_acc=0.8177 valid_f1=0.7834 lr=5.94e-06 time=45.4s eta=6.1m
saved best checkpoint: epoch=4 valid_f1=0.7834
epoch=5/12 train_loss=0.3435 valid_loss=0.5281 valid_acc=0.8291 valid_f1=0.7945 lr=5.20e-06 time=45.4s eta=5.3m
saved best checkpoint: epoch=5 valid_f1=0.7945
epoch=6/12 train_loss=0.2722 valid_loss=0.5736 valid_acc=0.8063 valid_f1=0.7802 lr=4.46e-06 time=45.2s eta=4.5m
no improvement: 1/3
epoch=7/12 train_loss=0.2488 valid_loss=0.5790 valid_acc=0.8205 valid_f1=0.7941 lr=3.72e-06 time=45.3s eta=3.8m
no improvement: 2/3
epoch=8/12 train_loss=0.2174 valid_loss=0.6104 valid_acc=0.8262 valid_f1=0.7987 lr=2.98e-06 time=45.3s eta=3.0m
saved best checkpoint: epoch=8 valid_f1=0.7987
epoch=9/12 train_loss=0.1814 valid_loss=0.6546 valid_acc=0.8319 valid_f1=0.8080 lr=2.24e-06 time=45.5s eta=2.3m
saved best checkpoint: epoch=9 valid_f1=0.8080
epoch=10/12 train_loss=0.1718 valid_loss=0.6370 valid_acc=0.8234 valid_f1=0.7904 lr=1.50e-06 time=45.6s eta=1.5m
no improvement: 1/3
epoch=11/12 train_loss=0.1552 valid_loss=0.6486 valid_acc=0.8376 valid_f1=0.8102 lr=7.59e-07 time=45.2s eta=0.8m
saved best checkpoint: epoch=11 valid_f1=0.8102
epoch=12/12 train_loss=0.1588 valid_loss=0.6538 valid_acc=0.8291 valid_f1=0.7988 lr=1.79e-08 time=45.5s eta=0.0m
no improvement: 1/3
calibration_temperature=1.846934
{
  "validation": {
    "accuracy": 0.8376,
    "precision_macro": 0.8084,
    "recall_macro": 0.8128,
    "macro_f1": 0.8102,
    "weighted_f1": 0.8387,
    "roc_auc_macro": 0.9436,
    "average_confidence": 0.8474,
    "expected_calibration_error": 0.0624,
    "temperature": 1.846934,
    "uncalibrated_confidence": 0.9432,
    "seen": {
      "samples": 239,
      "accuracy": 0.8661,
      "macro_f1": 0.8318
    },
    "unseen": {
      "samples": 112,
      "accuracy": 0.7768,
      "macro_f1": 0.7658
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_baseline_cls_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_aspect_attention_term_split2024_seed2024 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 15:38:52.481553: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782056332.500099     162 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782056332.506123     162 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782056332.521962     162 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782056332.521982     162 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782056332.521989     162 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782056332.521992     162 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1978,
      "labels": {
        "negative": 743,
        "neutral": 393,
        "positive": 842
      },
      "unique_aspects": 844
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 349,
      "labels": {
        "negative": 127,
        "neutral": 70,
        "positive": 152
      },
      "unique_aspects": 212,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3209
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 283,
      "unseen_aspect_ratio": 0.4436
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.1225 valid_loss=0.8583 valid_acc=0.6418 valid_f1=0.4698 lr=6.55e-06 time=48.9s eta=9.0m
saved best checkpoint: epoch=1 valid_f1=0.4698
epoch=2/12 train_loss=0.7026 valid_loss=0.4804 valid_acc=0.8281 valid_f1=0.7836 lr=7.43e-06 time=47.9s eta=8.0m
saved best checkpoint: epoch=2 valid_f1=0.7836
epoch=3/12 train_loss=0.4634 valid_loss=0.5222 valid_acc=0.7937 valid_f1=0.7429 lr=6.69e-06 time=47.5s eta=7.1m
no improvement: 1/3
epoch=4/12 train_loss=0.3377 valid_loss=0.5556 valid_acc=0.7937 valid_f1=0.7557 lr=5.94e-06 time=47.2s eta=6.3m
no improvement: 2/3
epoch=5/12 train_loss=0.2656 valid_loss=0.5591 valid_acc=0.8080 valid_f1=0.7787 lr=5.20e-06 time=47.1s eta=5.5m
no improvement: 3/3
early stopping at epoch 5; best epoch was 2
calibration_temperature=0.946423
{
  "validation": {
    "accuracy": 0.8281,
    "precision_macro": 0.7969,
    "recall_macro": 0.778,
    "macro_f1": 0.7836,
    "weighted_f1": 0.8217,
    "roc_auc_macro": 0.9357,
    "average_confidence": 0.8209,
    "expected_calibration_error": 0.0465,
    "temperature": 0.946423,
    "uncalibrated_confidence": 0.8113,
    "seen": {
      "samples": 237,
      "accuracy": 0.8481,
      "macro_f1": 0.8067
    },
    "unseen": {
      "samples": 112,
      "accuracy": 0.7857,
      "macro_f1": 0.7311
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_aspect_attention_term_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_aspect_attention_term_split42_seed42 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 15:44:57.881047: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782056697.899253     189 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782056697.905258     189 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782056697.922241     189 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782056697.922284     189 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782056697.922287     189 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782056697.922290     189 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1976,
      "labels": {
        "negative": 739,
        "neutral": 392,
        "positive": 845
      },
      "unique_aspects": 845
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 105,
      "unseen_aspect_ratio": 0.0451
    },
    "valid": {
      "samples": 351,
      "labels": {
        "negative": 131,
        "neutral": 71,
        "positive": 149
      },
      "unique_aspects": 220,
      "unseen_aspect_samples": 105,
      "unseen_aspect_ratio": 0.2991
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 278,
      "unseen_aspect_ratio": 0.4357
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.1077 valid_loss=0.8590 valid_acc=0.6581 valid_f1=0.4881 lr=6.55e-06 time=48.0s eta=8.8m
saved best checkpoint: epoch=1 valid_f1=0.4881
epoch=2/12 train_loss=0.6934 valid_loss=0.5702 valid_acc=0.7977 valid_f1=0.7586 lr=7.42e-06 time=47.4s eta=7.9m
saved best checkpoint: epoch=2 valid_f1=0.7586
epoch=3/12 train_loss=0.4629 valid_loss=0.5782 valid_acc=0.8034 valid_f1=0.7724 lr=6.68e-06 time=47.2s eta=7.1m
saved best checkpoint: epoch=3 valid_f1=0.7724
epoch=4/12 train_loss=0.3592 valid_loss=0.6245 valid_acc=0.8063 valid_f1=0.7612 lr=5.94e-06 time=46.7s eta=6.2m
no improvement: 1/3
epoch=5/12 train_loss=0.2864 valid_loss=0.6796 valid_acc=0.7749 valid_f1=0.7522 lr=5.20e-06 time=46.4s eta=5.4m
no improvement: 2/3
epoch=6/12 train_loss=0.2322 valid_loss=0.6874 valid_acc=0.7949 valid_f1=0.7507 lr=4.46e-06 time=45.6s eta=4.6m
no improvement: 3/3
early stopping at epoch 6; best epoch was 3
calibration_temperature=1.235577
{
  "validation": {
    "accuracy": 0.8034,
    "precision_macro": 0.7741,
    "recall_macro": 0.775,
    "macro_f1": 0.7724,
    "weighted_f1": 0.8047,
    "roc_auc_macro": 0.9151,
    "average_confidence": 0.7908,
    "expected_calibration_error": 0.0571,
    "temperature": 1.235577,
    "uncalibrated_confidence": 0.8308,
    "seen": {
      "samples": 246,
      "accuracy": 0.8211,
      "macro_f1": 0.7782
    },
    "unseen": {
      "samples": 105,
      "accuracy": 0.7619,
      "macro_f1": 0.743
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_aspect_attention_term_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_aspect_attention_term_split3407_seed3407 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 15:51:48.253277: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782057108.271350     216 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782057108.277197     216 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782057108.292624     216 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782057108.292645     216 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782057108.292648     216 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782057108.292650     216 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1976,
      "labels": {
        "negative": 738,
        "neutral": 393,
        "positive": 845
      },
      "unique_aspects": 843
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 351,
      "labels": {
        "negative": 132,
        "neutral": 70,
        "positive": 149
      },
      "unique_aspects": 221,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3191
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 276,
      "unseen_aspect_ratio": 0.4326
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.1056 valid_loss=0.8138 valid_acc=0.6353 valid_f1=0.5593 lr=6.55e-06 time=46.3s eta=8.5m
saved best checkpoint: epoch=1 valid_f1=0.5593
epoch=2/12 train_loss=0.6650 valid_loss=0.5208 valid_acc=0.7835 valid_f1=0.7033 lr=7.42e-06 time=45.4s eta=7.6m
saved best checkpoint: epoch=2 valid_f1=0.7033
epoch=3/12 train_loss=0.4506 valid_loss=0.5086 valid_acc=0.8177 valid_f1=0.7648 lr=6.68e-06 time=45.5s eta=6.8m
saved best checkpoint: epoch=3 valid_f1=0.7648
epoch=4/12 train_loss=0.3307 valid_loss=0.6253 valid_acc=0.8006 valid_f1=0.7251 lr=5.94e-06 time=45.6s eta=6.1m
no improvement: 1/3
epoch=5/12 train_loss=0.2591 valid_loss=0.5790 valid_acc=0.8177 valid_f1=0.7857 lr=5.20e-06 time=45.4s eta=5.3m
saved best checkpoint: epoch=5 valid_f1=0.7857
epoch=6/12 train_loss=0.2094 valid_loss=0.6353 valid_acc=0.7977 valid_f1=0.7717 lr=4.46e-06 time=45.7s eta=4.6m
no improvement: 1/3
epoch=7/12 train_loss=0.1804 valid_loss=0.6108 valid_acc=0.8205 valid_f1=0.7738 lr=3.72e-06 time=45.4s eta=3.8m
no improvement: 2/3
epoch=8/12 train_loss=0.1528 valid_loss=0.6464 valid_acc=0.8205 valid_f1=0.7751 lr=2.98e-06 time=45.7s eta=3.0m
no improvement: 3/3
early stopping at epoch 8; best epoch was 5
calibration_temperature=1.605054
{
  "validation": {
    "accuracy": 0.8177,
    "precision_macro": 0.7839,
    "recall_macro": 0.7902,
    "macro_f1": 0.7857,
    "weighted_f1": 0.8218,
    "roc_auc_macro": 0.9343,
    "average_confidence": 0.8281,
    "expected_calibration_error": 0.0525,
    "temperature": 1.605054,
    "uncalibrated_confidence": 0.9004,
    "seen": {
      "samples": 239,
      "accuracy": 0.8536,
      "macro_f1": 0.8168
    },
    "unseen": {
      "samples": 112,
      "accuracy": 0.7411,
      "macro_f1": 0.7235
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_aspect_attention_term_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_hybrid_term_split2024_seed2024 --evaluation-split validation --pooling-strategy hybrid --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 16:00:04.569349: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782057604.588861     243 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782057604.595426     243 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782057604.612823     243 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782057604.612845     243 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782057604.612848     243 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782057604.612850     243 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1978,
      "labels": {
        "negative": 743,
        "neutral": 393,
        "positive": 842
      },
      "unique_aspects": 844
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 349,
      "labels": {
        "negative": 127,
        "neutral": 70,
        "positive": 152
      },
      "unique_aspects": 212,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3209
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 283,
      "unseen_aspect_ratio": 0.4436
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.0912 valid_loss=0.8529 valid_acc=0.6418 valid_f1=0.5562 lr=6.60e-06 time=47.7s eta=8.7m
saved best checkpoint: epoch=1 valid_f1=0.5562
epoch=2/12 train_loss=0.6989 valid_loss=0.5357 valid_acc=0.7765 valid_f1=0.6664 lr=7.42e-06 time=46.8s eta=7.8m
saved best checkpoint: epoch=2 valid_f1=0.6664
epoch=3/12 train_loss=0.4811 valid_loss=0.5192 valid_acc=0.7822 valid_f1=0.7516 lr=6.68e-06 time=46.9s eta=7.0m
saved best checkpoint: epoch=3 valid_f1=0.7516
epoch=4/12 train_loss=0.3363 valid_loss=0.5676 valid_acc=0.7908 valid_f1=0.7410 lr=5.94e-06 time=47.1s eta=6.3m
no improvement: 1/3
epoch=5/12 train_loss=0.2493 valid_loss=0.6434 valid_acc=0.7822 valid_f1=0.7308 lr=5.20e-06 time=46.8s eta=5.5m
no improvement: 2/3
epoch=6/12 train_loss=0.1943 valid_loss=0.6471 valid_acc=0.8052 valid_f1=0.7595 lr=4.46e-06 time=46.2s eta=4.6m
saved best checkpoint: epoch=6 valid_f1=0.7595
epoch=7/12 train_loss=0.1659 valid_loss=0.6858 valid_acc=0.7994 valid_f1=0.7485 lr=3.72e-06 time=47.1s eta=3.9m
no improvement: 1/3
epoch=8/12 train_loss=0.1455 valid_loss=0.7448 valid_acc=0.8080 valid_f1=0.7446 lr=2.98e-06 time=46.7s eta=3.1m
no improvement: 2/3
epoch=9/12 train_loss=0.1310 valid_loss=0.7119 valid_acc=0.8109 valid_f1=0.7633 lr=2.23e-06 time=46.5s eta=2.3m
saved best checkpoint: epoch=9 valid_f1=0.7633
epoch=10/12 train_loss=0.1195 valid_loss=0.7002 valid_acc=0.8080 valid_f1=0.7555 lr=1.49e-06 time=46.9s eta=1.6m
no improvement: 1/3
epoch=11/12 train_loss=0.1260 valid_loss=0.7158 valid_acc=0.8080 valid_f1=0.7493 lr=7.53e-07 time=46.6s eta=0.8m
no improvement: 2/3
epoch=12/12 train_loss=0.1213 valid_loss=0.7125 valid_acc=0.8109 valid_f1=0.7563 lr=1.19e-08 time=46.5s eta=0.0m
no improvement: 3/3
early stopping at epoch 12; best epoch was 9
calibration_temperature=1.930182
{
  "validation": {
    "accuracy": 0.8109,
    "precision_macro": 0.7676,
    "recall_macro": 0.761,
    "macro_f1": 0.7633,
    "weighted_f1": 0.8068,
    "roc_auc_macro": 0.9185,
    "average_confidence": 0.8291,
    "expected_calibration_error": 0.0479,
    "temperature": 1.930182,
    "uncalibrated_confidence": 0.937,
    "seen": {
      "samples": 237,
      "accuracy": 0.8481,
      "macro_f1": 0.8085
    },
    "unseen": {
      "samples": 112,
      "accuracy": 0.7321,
      "macro_f1": 0.6694
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_hybrid_term_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_hybrid_term_split42_seed42 --evaluation-split validation --pooling-strategy hybrid --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 16:11:39.627965: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782058299.646597     270 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782058299.652570     270 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782058299.668307     270 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782058299.668327     270 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782058299.668330     270 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782058299.668332     270 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1976,
      "labels": {
        "negative": 739,
        "neutral": 392,
        "positive": 845
      },
      "unique_aspects": 845
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 105,
      "unseen_aspect_ratio": 0.0451
    },
    "valid": {
      "samples": 351,
      "labels": {
        "negative": 131,
        "neutral": 71,
        "positive": 149
      },
      "unique_aspects": 220,
      "unseen_aspect_samples": 105,
      "unseen_aspect_ratio": 0.2991
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 278,
      "unseen_aspect_ratio": 0.4357
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.0960 valid_loss=0.8244 valid_acc=0.6353 valid_f1=0.4915 lr=6.55e-06 time=47.3s eta=8.7m
saved best checkpoint: epoch=1 valid_f1=0.4915
epoch=2/12 train_loss=0.6802 valid_loss=0.5451 valid_acc=0.7977 valid_f1=0.7557 lr=7.42e-06 time=46.6s eta=7.8m
saved best checkpoint: epoch=2 valid_f1=0.7557
epoch=3/12 train_loss=0.4502 valid_loss=0.5671 valid_acc=0.7721 valid_f1=0.7435 lr=6.68e-06 time=46.4s eta=7.0m
no improvement: 1/3
epoch=4/12 train_loss=0.3375 valid_loss=0.5912 valid_acc=0.8034 valid_f1=0.7559 lr=5.94e-06 time=46.4s eta=6.2m
no improvement: 2/3
epoch=5/12 train_loss=0.2569 valid_loss=0.6263 valid_acc=0.7977 valid_f1=0.7605 lr=5.20e-06 time=46.8s eta=5.5m
saved best checkpoint: epoch=5 valid_f1=0.7605
epoch=6/12 train_loss=0.2146 valid_loss=0.6994 valid_acc=0.7977 valid_f1=0.7625 lr=4.46e-06 time=46.5s eta=4.6m
no improvement: 1/3
epoch=7/12 train_loss=0.1802 valid_loss=0.7516 valid_acc=0.8006 valid_f1=0.7619 lr=3.72e-06 time=46.2s eta=3.8m
no improvement: 2/3
epoch=8/12 train_loss=0.1562 valid_loss=0.7566 valid_acc=0.8006 valid_f1=0.7580 lr=2.98e-06 time=46.5s eta=3.1m
no improvement: 3/3
early stopping at epoch 8; best epoch was 5
calibration_temperature=1.687654
{
  "validation": {
    "accuracy": 0.7977,
    "precision_macro": 0.7602,
    "recall_macro": 0.7613,
    "macro_f1": 0.7605,
    "weighted_f1": 0.7985,
    "roc_auc_macro": 0.9267,
    "average_confidence": 0.8266,
    "expected_calibration_error": 0.0592,
    "temperature": 1.687654,
    "uncalibrated_confidence": 0.9144,
    "seen": {
      "samples": 246,
      "accuracy": 0.8293,
      "macro_f1": 0.7873
    },
    "unseen": {
      "samples": 105,
      "accuracy": 0.7238,
      "macro_f1": 0.6975
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_hybrid_term_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_hybrid_term_split3407_seed3407 --evaluation-split validation --pooling-strategy hybrid --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 16:20:03.040442: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782058803.058673     297 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782058803.064633     297 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782058803.080681     297 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782058803.080703     297 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782058803.080705     297 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782058803.080708     297 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1976,
      "labels": {
        "negative": 738,
        "neutral": 393,
        "positive": 845
      },
      "unique_aspects": 843
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 351,
      "labels": {
        "negative": 132,
        "neutral": 70,
        "positive": 149
      },
      "unique_aspects": 221,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3191
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 276,
      "unseen_aspect_ratio": 0.4326
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/12 train_loss=1.0929 valid_loss=0.7806 valid_acc=0.6866 valid_f1=0.5291 lr=6.60e-06 time=48.0s eta=8.8m
saved best checkpoint: epoch=1 valid_f1=0.5291
epoch=2/12 train_loss=0.6369 valid_loss=0.5238 valid_acc=0.8034 valid_f1=0.7130 lr=7.42e-06 time=48.5s eta=8.1m
saved best checkpoint: epoch=2 valid_f1=0.7130
epoch=3/12 train_loss=0.4475 valid_loss=0.4686 valid_acc=0.8291 valid_f1=0.7986 lr=6.69e-06 time=47.4s eta=7.1m
saved best checkpoint: epoch=3 valid_f1=0.7986
epoch=4/12 train_loss=0.3389 valid_loss=0.5237 valid_acc=0.8205 valid_f1=0.7581 lr=5.94e-06 time=47.1s eta=6.3m
no improvement: 1/3
epoch=5/12 train_loss=0.2717 valid_loss=0.5138 valid_acc=0.8433 valid_f1=0.8019 lr=5.20e-06 time=47.2s eta=5.5m
saved best checkpoint: epoch=5 valid_f1=0.8019
epoch=6/12 train_loss=0.2201 valid_loss=0.5366 valid_acc=0.8348 valid_f1=0.7909 lr=4.46e-06 time=46.8s eta=4.7m
no improvement: 1/3
epoch=7/12 train_loss=0.1888 valid_loss=0.5886 valid_acc=0.8291 valid_f1=0.7745 lr=3.72e-06 time=46.9s eta=3.9m
no improvement: 2/3
epoch=8/12 train_loss=0.1480 valid_loss=0.5847 valid_acc=0.8262 valid_f1=0.7919 lr=2.98e-06 time=47.0s eta=3.1m
no improvement: 3/3
early stopping at epoch 8; best epoch was 5
calibration_temperature=1.484749
{
  "validation": {
    "accuracy": 0.8433,
    "precision_macro": 0.8203,
    "recall_macro": 0.7935,
    "macro_f1": 0.8019,
    "weighted_f1": 0.8367,
    "roc_auc_macro": 0.9474,
    "average_confidence": 0.8469,
    "expected_calibration_error": 0.0355,
    "temperature": 1.484749,
    "uncalibrated_confidence": 0.9046,
    "seen": {
      "samples": 239,
      "accuracy": 0.8703,
      "macro_f1": 0.8185
    },
    "unseen": {
      "samples": 112,
      "accuracy": 0.7857,
      "macro_f1": 0.7649
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_hybrid_term_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_cls_neutral125_split2024_seed2024 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 16:28:35.375814: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782059315.394339     324 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782059315.400420     324 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782059315.417116     324 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782059315.417167     324 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782059315.417174     324 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782059315.417178     324 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1978,
      "labels": {
        "negative": 743,
        "neutral": 393,
        "positive": 842
      },
      "unique_aspects": 844
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 349,
      "labels": {
        "negative": 127,
        "neutral": 70,
        "positive": 152
      },
      "unique_aspects": 212,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3209
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 283,
      "unseen_aspect_ratio": 0.4436
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=1.0792 valid_loss=0.8919 valid_acc=0.6819 valid_f1=0.5046 lr=6.55e-06 time=46.8s eta=8.6m
saved best checkpoint: epoch=1 valid_f1=0.5046
epoch=2/12 train_loss=0.7490 valid_loss=0.5503 valid_acc=0.8223 valid_f1=0.7491 lr=7.42e-06 time=46.3s eta=7.7m
saved best checkpoint: epoch=2 valid_f1=0.7491
epoch=3/12 train_loss=0.5721 valid_loss=0.5763 valid_acc=0.8052 valid_f1=0.7199 lr=6.68e-06 time=45.9s eta=6.9m
no improvement: 1/3
epoch=4/12 train_loss=0.4338 valid_loss=0.5635 valid_acc=0.7650 valid_f1=0.7236 lr=5.94e-06 time=45.8s eta=6.1m
no improvement: 2/3
epoch=5/12 train_loss=0.3420 valid_loss=0.6632 valid_acc=0.7880 valid_f1=0.7312 lr=5.20e-06 time=45.8s eta=5.3m
no improvement: 3/3
early stopping at epoch 5; best epoch was 2
calibration_temperature=0.817285
{
  "validation": {
    "accuracy": 0.8223,
    "precision_macro": 0.8106,
    "recall_macro": 0.7458,
    "macro_f1": 0.7491,
    "weighted_f1": 0.8014,
    "roc_auc_macro": 0.9206,
    "average_confidence": 0.7916,
    "expected_calibration_error": 0.067,
    "temperature": 0.817285,
    "uncalibrated_confidence": 0.7545,
    "seen": {
      "samples": 237,
      "accuracy": 0.8228,
      "macro_f1": 0.7358
    },
    "unseen": {
      "samples": 112,
      "accuracy": 0.8214,
      "macro_f1": 0.7663
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_cls_neutral125_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_cls_neutral125_split42_seed42 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 16:34:32.970127: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782059672.990167     351 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782059672.996364     351 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782059673.013334     351 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782059673.013378     351 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782059673.013384     351 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782059673.013388     351 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1976,
      "labels": {
        "negative": 739,
        "neutral": 392,
        "positive": 845
      },
      "unique_aspects": 845
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 105,
      "unseen_aspect_ratio": 0.0451
    },
    "valid": {
      "samples": 351,
      "labels": {
        "negative": 131,
        "neutral": 71,
        "positive": 149
      },
      "unique_aspects": 220,
      "unseen_aspect_samples": 105,
      "unseen_aspect_ratio": 0.2991
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 278,
      "unseen_aspect_ratio": 0.4357
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=1.0852 valid_loss=0.8772 valid_acc=0.7265 valid_f1=0.5386 lr=6.60e-06 time=47.7s eta=8.7m
saved best checkpoint: epoch=1 valid_f1=0.5386
epoch=2/12 train_loss=0.6648 valid_loss=0.6137 valid_acc=0.7407 valid_f1=0.7069 lr=7.42e-06 time=46.3s eta=7.7m
saved best checkpoint: epoch=2 valid_f1=0.7069
epoch=3/12 train_loss=0.5019 valid_loss=0.5674 valid_acc=0.7550 valid_f1=0.7186 lr=6.68e-06 time=46.6s eta=7.0m
saved best checkpoint: epoch=3 valid_f1=0.7186
epoch=4/12 train_loss=0.3980 valid_loss=0.6229 valid_acc=0.7407 valid_f1=0.7102 lr=5.94e-06 time=47.2s eta=6.3m
no improvement: 1/3
epoch=5/12 train_loss=0.3401 valid_loss=0.6465 valid_acc=0.7977 valid_f1=0.7394 lr=5.20e-06 time=46.5s eta=5.4m
saved best checkpoint: epoch=5 valid_f1=0.7394
epoch=6/12 train_loss=0.2790 valid_loss=0.6929 valid_acc=0.7806 valid_f1=0.7325 lr=4.46e-06 time=46.8s eta=4.7m
no improvement: 1/3
epoch=7/12 train_loss=0.2554 valid_loss=0.7658 valid_acc=0.7749 valid_f1=0.7431 lr=3.72e-06 time=46.8s eta=3.9m
saved best checkpoint: epoch=7 valid_f1=0.7431
epoch=8/12 train_loss=0.2165 valid_loss=0.7549 valid_acc=0.7863 valid_f1=0.7476 lr=2.98e-06 time=47.1s eta=3.1m
saved best checkpoint: epoch=8 valid_f1=0.7476
epoch=9/12 train_loss=0.1902 valid_loss=0.7992 valid_acc=0.7892 valid_f1=0.7420 lr=2.23e-06 time=46.8s eta=2.3m
no improvement: 1/3
epoch=10/12 train_loss=0.1798 valid_loss=0.8030 valid_acc=0.7920 valid_f1=0.7468 lr=1.49e-06 time=46.7s eta=1.6m
no improvement: 2/3
epoch=11/12 train_loss=0.1675 valid_loss=0.8149 valid_acc=0.7892 valid_f1=0.7558 lr=7.59e-07 time=46.4s eta=0.8m
saved best checkpoint: epoch=11 valid_f1=0.7558
epoch=12/12 train_loss=0.1618 valid_loss=0.8151 valid_acc=0.7949 valid_f1=0.7575 lr=1.79e-08 time=46.9s eta=0.0m
no improvement: 1/3
calibration_temperature=2.082053
{
  "validation": {
    "accuracy": 0.7892,
    "precision_macro": 0.7546,
    "recall_macro": 0.7586,
    "macro_f1": 0.7558,
    "weighted_f1": 0.7924,
    "roc_auc_macro": 0.9171,
    "average_confidence": 0.8138,
    "expected_calibration_error": 0.0266,
    "temperature": 2.082053,
    "uncalibrated_confidence": 0.9397,
    "seen": {
      "samples": 246,
      "accuracy": 0.8089,
      "macro_f1": 0.7681
    },
    "unseen": {
      "samples": 105,
      "accuracy": 0.7429,
      "macro_f1": 0.7232
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_cls_neutral125_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_cls_neutral125_split3407_seed3407 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 16:46:09.892014: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782060369.910385     378 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782060369.916626     378 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782060369.932474     378 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782060369.932520     378 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782060369.932526     378 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782060369.932531     378 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1976,
      "labels": {
        "negative": 738,
        "neutral": 393,
        "positive": 845
      },
      "unique_aspects": 843
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 351,
      "labels": {
        "negative": 132,
        "neutral": 70,
        "positive": 149
      },
      "unique_aspects": 221,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3191
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 276,
      "unseen_aspect_ratio": 0.4326
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=1.1022 valid_loss=0.9429 valid_acc=0.5499 valid_f1=0.3815 lr=6.60e-06 time=48.1s eta=8.8m
saved best checkpoint: epoch=1 valid_f1=0.3815
epoch=2/12 train_loss=0.6794 valid_loss=0.5692 valid_acc=0.7778 valid_f1=0.7190 lr=7.42e-06 time=46.9s eta=7.8m
saved best checkpoint: epoch=2 valid_f1=0.7190
epoch=3/12 train_loss=0.5104 valid_loss=0.5376 valid_acc=0.8120 valid_f1=0.7593 lr=6.69e-06 time=46.9s eta=7.0m
saved best checkpoint: epoch=3 valid_f1=0.7593
epoch=4/12 train_loss=0.4038 valid_loss=0.5302 valid_acc=0.8234 valid_f1=0.7908 lr=5.94e-06 time=47.1s eta=6.3m
saved best checkpoint: epoch=4 valid_f1=0.7908
epoch=5/12 train_loss=0.3429 valid_loss=0.5267 valid_acc=0.8319 valid_f1=0.7984 lr=5.20e-06 time=47.1s eta=5.5m
saved best checkpoint: epoch=5 valid_f1=0.7984
epoch=6/12 train_loss=0.2736 valid_loss=0.5957 valid_acc=0.8091 valid_f1=0.7856 lr=4.46e-06 time=47.0s eta=4.7m
no improvement: 1/3
epoch=7/12 train_loss=0.2513 valid_loss=0.5813 valid_acc=0.8205 valid_f1=0.7928 lr=3.72e-06 time=47.0s eta=3.9m
no improvement: 2/3
epoch=8/12 train_loss=0.2224 valid_loss=0.6033 valid_acc=0.8120 valid_f1=0.7813 lr=2.98e-06 time=46.9s eta=3.1m
no improvement: 3/3
early stopping at epoch 8; best epoch was 5
calibration_temperature=1.328504
{
  "validation": {
    "accuracy": 0.8319,
    "precision_macro": 0.7978,
    "recall_macro": 0.8027,
    "macro_f1": 0.7984,
    "weighted_f1": 0.8353,
    "roc_auc_macro": 0.9401,
    "average_confidence": 0.8303,
    "expected_calibration_error": 0.0599,
    "temperature": 1.328504,
    "uncalibrated_confidence": 0.8806,
    "seen": {
      "samples": 239,
      "accuracy": 0.8577,
      "macro_f1": 0.8132
    },
    "unseen": {
      "samples": 112,
      "accuracy": 0.7768,
      "macro_f1": 0.7662
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_cls_neutral125_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_cls_neutral150_split2024_seed2024 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.5 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 16:54:40.320789: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782060880.339306     405 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782060880.345433     405 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782060880.361557     405 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782060880.361577     405 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782060880.361580     405 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782060880.361582     405 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1978,
      "labels": {
        "negative": 743,
        "neutral": 393,
        "positive": 842
      },
      "unique_aspects": 844
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 349,
      "labels": {
        "negative": 127,
        "neutral": 70,
        "positive": 152
      },
      "unique_aspects": 212,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3209
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 283,
      "unseen_aspect_ratio": 0.4436
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.857143,
    "neutral": 1.285714,
    "positive": 0.857143
  }
}
epoch=1/12 train_loss=1.0595 valid_loss=0.8979 valid_acc=0.6819 valid_f1=0.5030 lr=6.55e-06 time=48.6s eta=8.9m
saved best checkpoint: epoch=1 valid_f1=0.5030
epoch=2/12 train_loss=0.7415 valid_loss=0.5497 valid_acc=0.7937 valid_f1=0.7486 lr=7.42e-06 time=47.8s eta=8.0m
saved best checkpoint: epoch=2 valid_f1=0.7486
epoch=3/12 train_loss=0.5586 valid_loss=0.5597 valid_acc=0.8080 valid_f1=0.7395 lr=6.68e-06 time=48.0s eta=7.2m
no improvement: 1/3
epoch=4/12 train_loss=0.4208 valid_loss=0.5519 valid_acc=0.7650 valid_f1=0.7283 lr=5.94e-06 time=47.2s eta=6.3m
no improvement: 2/3
epoch=5/12 train_loss=0.3327 valid_loss=0.6976 valid_acc=0.7994 valid_f1=0.7375 lr=5.20e-06 time=47.5s eta=5.5m
no improvement: 3/3
early stopping at epoch 5; best epoch was 2
calibration_temperature=0.922899
{
  "validation": {
    "accuracy": 0.7937,
    "precision_macro": 0.7502,
    "recall_macro": 0.7496,
    "macro_f1": 0.7486,
    "weighted_f1": 0.7913,
    "roc_auc_macro": 0.9183,
    "average_confidence": 0.7922,
    "expected_calibration_error": 0.0334,
    "temperature": 0.922899,
    "uncalibrated_confidence": 0.7769,
    "seen": {
      "samples": 237,
      "accuracy": 0.8017,
      "macro_f1": 0.7528
    },
    "unseen": {
      "samples": 112,
      "accuracy": 0.7768,
      "macro_f1": 0.7307
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_cls_neutral150_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_cls_neutral150_split42_seed42 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.5 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 17:00:47.000128: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782061247.020675     432 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782061247.027528     432 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782061247.044567     432 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782061247.044617     432 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782061247.044623     432 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782061247.044627     432 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1976,
      "labels": {
        "negative": 739,
        "neutral": 392,
        "positive": 845
      },
      "unique_aspects": 845
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 105,
      "unseen_aspect_ratio": 0.0451
    },
    "valid": {
      "samples": 351,
      "labels": {
        "negative": 131,
        "neutral": 71,
        "positive": 149
      },
      "unique_aspects": 220,
      "unseen_aspect_samples": 105,
      "unseen_aspect_ratio": 0.2991
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 278,
      "unseen_aspect_ratio": 0.4357
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.857143,
    "neutral": 1.285714,
    "positive": 0.857143
  }
}
epoch=1/12 train_loss=1.0603 valid_loss=0.9165 valid_acc=0.6838 valid_f1=0.5062 lr=6.60e-06 time=46.8s eta=8.6m
saved best checkpoint: epoch=1 valid_f1=0.5062
epoch=2/12 train_loss=0.6684 valid_loss=0.6234 valid_acc=0.7379 valid_f1=0.7025 lr=7.42e-06 time=46.1s eta=7.7m
saved best checkpoint: epoch=2 valid_f1=0.7025
epoch=3/12 train_loss=0.5022 valid_loss=0.5662 valid_acc=0.7521 valid_f1=0.7204 lr=6.68e-06 time=45.9s eta=6.9m
saved best checkpoint: epoch=3 valid_f1=0.7204
epoch=4/12 train_loss=0.3906 valid_loss=0.6173 valid_acc=0.7578 valid_f1=0.7269 lr=5.94e-06 time=46.2s eta=6.2m
saved best checkpoint: epoch=4 valid_f1=0.7269
epoch=5/12 train_loss=0.3343 valid_loss=0.6683 valid_acc=0.7977 valid_f1=0.7418 lr=5.20e-06 time=46.3s eta=5.4m
saved best checkpoint: epoch=5 valid_f1=0.7418
epoch=6/12 train_loss=0.2745 valid_loss=0.7005 valid_acc=0.7892 valid_f1=0.7506 lr=4.46e-06 time=45.9s eta=4.6m
saved best checkpoint: epoch=6 valid_f1=0.7506
epoch=7/12 train_loss=0.2516 valid_loss=0.7556 valid_acc=0.7749 valid_f1=0.7477 lr=3.72e-06 time=46.1s eta=3.8m
no improvement: 1/3
epoch=8/12 train_loss=0.2131 valid_loss=0.7596 valid_acc=0.7806 valid_f1=0.7451 lr=2.98e-06 time=45.7s eta=3.0m
no improvement: 2/3
epoch=9/12 train_loss=0.1841 valid_loss=0.7933 valid_acc=0.8034 valid_f1=0.7636 lr=2.23e-06 time=45.4s eta=2.3m
saved best checkpoint: epoch=9 valid_f1=0.7636
epoch=10/12 train_loss=0.1750 valid_loss=0.7985 valid_acc=0.7949 valid_f1=0.7535 lr=1.49e-06 time=45.7s eta=1.5m
no improvement: 1/3
epoch=11/12 train_loss=0.1640 valid_loss=0.8002 valid_acc=0.7949 valid_f1=0.7621 lr=7.53e-07 time=45.2s eta=0.8m
no improvement: 2/3
epoch=12/12 train_loss=0.1594 valid_loss=0.8048 valid_acc=0.7949 valid_f1=0.7607 lr=1.19e-08 time=45.5s eta=0.0m
no improvement: 3/3
early stopping at epoch 12; best epoch was 9
calibration_temperature=1.987383
{
  "validation": {
    "accuracy": 0.8034,
    "precision_macro": 0.768,
    "recall_macro": 0.7621,
    "macro_f1": 0.7636,
    "weighted_f1": 0.8013,
    "roc_auc_macro": 0.9199,
    "average_confidence": 0.8243,
    "expected_calibration_error": 0.0447,
    "temperature": 1.987383,
    "uncalibrated_confidence": 0.9389,
    "seen": {
      "samples": 246,
      "accuracy": 0.8252,
      "macro_f1": 0.7802
    },
    "unseen": {
      "samples": 105,
      "accuracy": 0.7524,
      "macro_f1": 0.7231
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_cls_neutral150_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_cls_neutral150_split3407_seed3407 --evaluation-split validation --pooling-strategy cls --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.5 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 17:12:12.639825: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782061932.658698     459 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782061932.664946     459 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782061932.681581     459 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782061932.681604     459 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782061932.681607     459 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782061932.681609     459 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1976,
      "labels": {
        "negative": 738,
        "neutral": 393,
        "positive": 845
      },
      "unique_aspects": 843
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 351,
      "labels": {
        "negative": 132,
        "neutral": 70,
        "positive": 149
      },
      "unique_aspects": 221,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3191
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 276,
      "unseen_aspect_ratio": 0.4326
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.857143,
    "neutral": 1.285714,
    "positive": 0.857143
  }
}
epoch=1/12 train_loss=1.0888 valid_loss=0.9400 valid_acc=0.5014 valid_f1=0.3220 lr=6.55e-06 time=46.8s eta=8.6m
saved best checkpoint: epoch=1 valid_f1=0.3220
epoch=2/12 train_loss=0.6802 valid_loss=0.5630 valid_acc=0.7806 valid_f1=0.7339 lr=7.42e-06 time=46.1s eta=7.7m
saved best checkpoint: epoch=2 valid_f1=0.7339
epoch=3/12 train_loss=0.5072 valid_loss=0.5414 valid_acc=0.8091 valid_f1=0.7601 lr=6.69e-06 time=46.0s eta=6.9m
saved best checkpoint: epoch=3 valid_f1=0.7601
epoch=4/12 train_loss=0.4033 valid_loss=0.5285 valid_acc=0.8148 valid_f1=0.7821 lr=5.94e-06 time=46.0s eta=6.1m
saved best checkpoint: epoch=4 valid_f1=0.7821
epoch=5/12 train_loss=0.3479 valid_loss=0.5207 valid_acc=0.8234 valid_f1=0.7890 lr=5.20e-06 time=45.4s eta=5.3m
saved best checkpoint: epoch=5 valid_f1=0.7890
epoch=6/12 train_loss=0.2740 valid_loss=0.5678 valid_acc=0.8120 valid_f1=0.7876 lr=4.46e-06 time=45.2s eta=4.5m
no improvement: 1/3
epoch=7/12 train_loss=0.2513 valid_loss=0.5706 valid_acc=0.8177 valid_f1=0.7891 lr=3.72e-06 time=45.6s eta=3.8m
no improvement: 2/3
epoch=8/12 train_loss=0.2251 valid_loss=0.5881 valid_acc=0.8205 valid_f1=0.7921 lr=2.98e-06 time=45.4s eta=3.0m
saved best checkpoint: epoch=8 valid_f1=0.7921
epoch=9/12 train_loss=0.1879 valid_loss=0.6187 valid_acc=0.8291 valid_f1=0.8039 lr=2.24e-06 time=44.9s eta=2.2m
saved best checkpoint: epoch=9 valid_f1=0.8039
epoch=10/12 train_loss=0.1773 valid_loss=0.6195 valid_acc=0.8205 valid_f1=0.7866 lr=1.50e-06 time=45.4s eta=1.5m
no improvement: 1/3
epoch=11/12 train_loss=0.1620 valid_loss=0.6353 valid_acc=0.8262 valid_f1=0.7936 lr=7.59e-07 time=45.2s eta=0.8m
no improvement: 2/3
epoch=12/12 train_loss=0.1641 valid_loss=0.6358 valid_acc=0.8234 valid_f1=0.7909 lr=1.79e-08 time=45.1s eta=0.0m
no improvement: 3/3
early stopping at epoch 12; best epoch was 9
calibration_temperature=1.773848
{
  "validation": {
    "accuracy": 0.8291,
    "precision_macro": 0.8006,
    "recall_macro": 0.8112,
    "macro_f1": 0.8039,
    "weighted_f1": 0.833,
    "roc_auc_macro": 0.9418,
    "average_confidence": 0.8339,
    "expected_calibration_error": 0.0324,
    "temperature": 1.773848,
    "uncalibrated_confidence": 0.9275,
    "seen": {
      "samples": 239,
      "accuracy": 0.8661,
      "macro_f1": 0.8352
    },
    "unseen": {
      "samples": 112,
      "accuracy": 0.75,
      "macro_f1": 0.7413
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_cls_neutral150_split3407_seed3407_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_aspect_attention_neutral125_split2024_seed2024 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 17:23:34.492539: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782062614.511060     486 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782062614.517154     486 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782062614.532922     486 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782062614.532969     486 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782062614.532976     486 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782062614.532980     486 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1978,
      "labels": {
        "negative": 743,
        "neutral": 393,
        "positive": 842
      },
      "unique_aspects": 844
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 349,
      "labels": {
        "negative": 127,
        "neutral": 70,
        "positive": 152
      },
      "unique_aspects": 212,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3209
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 283,
      "unseen_aspect_ratio": 0.4436
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=1.1101 valid_loss=0.8651 valid_acc=0.6332 valid_f1=0.4713 lr=6.55e-06 time=47.3s eta=8.7m
saved best checkpoint: epoch=1 valid_f1=0.4713
epoch=2/12 train_loss=0.7144 valid_loss=0.4906 valid_acc=0.8023 valid_f1=0.7607 lr=7.42e-06 time=46.9s eta=7.8m
saved best checkpoint: epoch=2 valid_f1=0.7607
epoch=3/12 train_loss=0.4716 valid_loss=0.5310 valid_acc=0.7880 valid_f1=0.7422 lr=6.68e-06 time=46.9s eta=7.0m
no improvement: 1/3
epoch=4/12 train_loss=0.3405 valid_loss=0.5623 valid_acc=0.7994 valid_f1=0.7675 lr=5.94e-06 time=46.5s eta=6.2m
saved best checkpoint: epoch=4 valid_f1=0.7675
epoch=5/12 train_loss=0.2634 valid_loss=0.5816 valid_acc=0.8109 valid_f1=0.7878 lr=5.20e-06 time=46.7s eta=5.4m
saved best checkpoint: epoch=5 valid_f1=0.7878
epoch=6/12 train_loss=0.2071 valid_loss=0.6545 valid_acc=0.8023 valid_f1=0.7387 lr=4.46e-06 time=46.5s eta=4.7m
no improvement: 1/3
epoch=7/12 train_loss=0.1729 valid_loss=0.6670 valid_acc=0.7994 valid_f1=0.7584 lr=3.72e-06 time=46.8s eta=3.9m
no improvement: 2/3
epoch=8/12 train_loss=0.1501 valid_loss=0.7205 valid_acc=0.8138 valid_f1=0.7826 lr=2.98e-06 time=46.9s eta=3.1m
no improvement: 3/3
early stopping at epoch 8; best epoch was 5
calibration_temperature=1.640257
{
  "validation": {
    "accuracy": 0.8109,
    "precision_macro": 0.7927,
    "recall_macro": 0.8025,
    "macro_f1": 0.7878,
    "weighted_f1": 0.8189,
    "roc_auc_macro": 0.9402,
    "average_confidence": 0.8382,
    "expected_calibration_error": 0.0486,
    "temperature": 1.640257,
    "uncalibrated_confidence": 0.9203,
    "seen": {
      "samples": 237,
      "accuracy": 0.8354,
      "macro_f1": 0.8114
    },
    "unseen": {
      "samples": 112,
      "accuracy": 0.7589,
      "macro_f1": 0.7403
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_aspect_attention_neutral125_split2024_seed2024_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 42 --seed 42 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_aspect_attention_neutral125_split42_seed42 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 17:32:01.343097: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782063121.361474     513 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782063121.367765     513 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782063121.383546     513 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782063121.383592     513 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782063121.383598     513 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782063121.383602     513 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1976,
      "labels": {
        "negative": 739,
        "neutral": 392,
        "positive": 845
      },
      "unique_aspects": 845
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 105,
      "unseen_aspect_ratio": 0.0451
    },
    "valid": {
      "samples": 351,
      "labels": {
        "negative": 131,
        "neutral": 71,
        "positive": 149
      },
      "unique_aspects": 220,
      "unseen_aspect_samples": 105,
      "unseen_aspect_ratio": 0.2991
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 278,
      "unseen_aspect_ratio": 0.4357
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=1.0965 valid_loss=0.8711 valid_acc=0.6610 valid_f1=0.5154 lr=6.55e-06 time=48.3s eta=8.9m
saved best checkpoint: epoch=1 valid_f1=0.5154
epoch=2/12 train_loss=0.7080 valid_loss=0.5740 valid_acc=0.7863 valid_f1=0.7523 lr=7.42e-06 time=47.8s eta=8.0m
saved best checkpoint: epoch=2 valid_f1=0.7523
epoch=3/12 train_loss=0.4721 valid_loss=0.5869 valid_acc=0.7949 valid_f1=0.7668 lr=6.68e-06 time=47.7s eta=7.2m
saved best checkpoint: epoch=3 valid_f1=0.7668
epoch=4/12 train_loss=0.3684 valid_loss=0.6318 valid_acc=0.8063 valid_f1=0.7668 lr=5.94e-06 time=47.9s eta=6.4m
no improvement: 1/3
epoch=5/12 train_loss=0.2902 valid_loss=0.6756 valid_acc=0.7806 valid_f1=0.7621 lr=5.20e-06 time=47.5s eta=5.5m
no improvement: 2/3
epoch=6/12 train_loss=0.2351 valid_loss=0.7272 valid_acc=0.7949 valid_f1=0.7566 lr=4.46e-06 time=47.1s eta=4.7m
no improvement: 3/3
early stopping at epoch 6; best epoch was 3
calibration_temperature=1.255569
{
  "validation": {
    "accuracy": 0.7949,
    "precision_macro": 0.767,
    "recall_macro": 0.772,
    "macro_f1": 0.7668,
    "weighted_f1": 0.7987,
    "roc_auc_macro": 0.9149,
    "average_confidence": 0.7861,
    "expected_calibration_error": 0.0493,
    "temperature": 1.255569,
    "uncalibrated_confidence": 0.8302,
    "seen": {
      "samples": 246,
      "accuracy": 0.8089,
      "macro_f1": 0.7702
    },
    "unseen": {
      "samples": 105,
      "accuracy": 0.7619,
      "macro_f1": 0.743
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_aspect_attention_neutral125_split42_seed42_artifacts.zip"
}
RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 12 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 3407 --seed 3407 --output-dir /kaggle/working/tuning_laptop_ablation_core --run-name tune_aspect_attention_neutral125_split3407_seed3407 --evaluation-split validation --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.25 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 17:38:57.292752: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782063537.311284     540 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782063537.317205     540 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782063537.332958     540 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782063537.332978     540 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782063537.332981     540 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782063537.332983     540 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1976,
      "labels": {
        "negative": 738,
        "neutral": 393,
        "positive": 845
      },
      "unique_aspects": 843
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 351,
      "labels": {
        "negative": 132,
        "neutral": 70,
        "positive": 149
      },
      "unique_aspects": 221,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3191
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 276,
      "unseen_aspect_ratio": 0.4326
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 0.923077,
    "neutral": 1.153846,
    "positive": 0.923077
  }
}
epoch=1/12 train_loss=1.0909 valid_loss=0.8207 valid_acc=0.6382 valid_f1=0.5956 lr=6.55e-06 time=47.0s eta=8.6m
saved best checkpoint: epoch=1 valid_f1=0.5956
epoch=2/12 train_loss=0.6789 valid_loss=0.5307 valid_acc=0.7778 valid_f1=0.7011 lr=7.42e-06 time=46.4s eta=7.7m
saved best checkpoint: epoch=2 valid_f1=0.7011
epoch=3/12 train_loss=0.4566 valid_loss=0.5253 valid_acc=0.8091 valid_f1=0.7558 lr=6.68e-06 time=46.5s eta=7.0m
saved best checkpoint: epoch=3 valid_f1=0.7558
epoch=4/12 train_loss=0.3383 valid_loss=0.6292 valid_acc=0.7977 valid_f1=0.7362 lr=5.94e-06 time=46.3s eta=6.2m
no improvement: 1/3
epoch=5/12 train_loss=0.2650 valid_loss=0.5885 valid_acc=0.8205 valid_f1=0.7870 lr=5.20e-06 time=46.1s eta=5.4m
saved best checkpoint: epoch=5 valid_f1=0.7870
epoch=6/12 train_loss=0.2112 valid_loss=0.6379 valid_acc=0.8034 valid_f1=0.7785 lr=4.46e-06 time=46.0s eta=4.6m
no improvement: 1/3
epoch=7/12 train_loss=0.1824 valid_loss=0.6184 valid_acc=0.8262 valid_f1=0.7898 lr=3.72e-06 time=46.4s eta=3.9m
saved best checkpoint: epoch=7 valid_f1=0.7898
epoch=8/12 train_loss=0.1534 valid_loss=0.6536 valid_acc=0.8234 valid_f1=0.7787 lr=2.98e-06 time=46.4s eta=3.1m
no improvement: 1/3
epoch=9/12 train_loss=0.1402 valid_loss=0.6789 valid_acc=0.8120 valid_f1=0.7842 lr=2.23e-06 time=45.7s eta=2.3m
no improvement: 2/3
epoch=10/12 train_loss=0.1370 valid_loss=0.6441 valid_acc=0.8205 valid_f1=0.7741 lr=1.49e-06 time=45.5s eta=1.5m
no improvement: 3/3
early stopping at epoch 10; best epoch was 7
calibration_temperature=1.687845
{
  "validation": {
    "accuracy": 0.8262,
    "precision_macro": 0.79,
    "recall_macro": 0.7899,
    "macro_f1": 0.7898,
    "weighted_f1": 0.8265,
    "roc_auc_macro": 0.9345,
    "average_confidence": 0.8386,
    "expected_calibration_error": 0.0715,
    "temperature": 1.687845,
    "uncalibrated_confidence": 0.9211,
    "seen": {
      "samples": 239,
      "accuracy": 0.8619,
      "macro_f1": 0.8215
    },
    "unseen": {
      "samples": 112,
      "accuracy": 0.75,
      "macro_f1": 0.7275
    }
  },
  "zip": "/kaggle/working/tuning_laptop_ablation_core/tune_aspect_attention_neutral125_split3407_seed3407_artifacts.zip"
}
{
  "selection_metric": "mean Macro-F1 minus one standard deviation",
  "search_space": "ablation_core",
  "final_split_seed": 2024,
  "validation_seed_pairs": [
    [
      2024,
      2024
    ],
    [
      42,
      42
    ],
    [
      3407,
      3407
    ]
  ],
  "best_configuration": {
    "name": "aspect_attention_term",
    "pooling_strategy": "aspect_attention",
    "input_format": "term",
    "encoder_layer_pooling": "last",
    "encoder_learning_rate": 8e-06,
    "head_learning_rate": 2e-05,
    "dropout": 0.3,
    "class_weighting": "none",
    "neutral_weight_multiplier": 1.0,
    "label_smoothing": 0.02,
    "loss_type": "cross_entropy",
    "scheduler": "linear",
    "warmup_ratio": 0.1,
    "max_length": 128
  },
  "best_validation_summary": {
    "trial": "aspect_attention_term",
    "mean_macro_f1": 0.780567,
    "std_macro_f1": 0.005838,
    "robust_macro_f1": 0.774729,
    "mean_accuracy": 0.8164,
    "mean_loss": 0.545867,
    "mean_log_loss": 0.4764,
    "mean_ece": 0.052033,
    "validation_seed_pairs": "2024:2024,42:42,3407:3407",
    "pooling_strategy": "aspect_attention",
    "input_format": "term",
    "encoder_layer_pooling": "last",
    "encoder_learning_rate": 8e-06,
    "head_learning_rate": 2e-05,
    "dropout": 0.3,
    "class_weighting": "none",
    "neutral_weight_multiplier": 1.0,
    "label_smoothing": 0.02,
    "loss_type": "cross_entropy",
    "scheduler": "linear",
    "warmup_ratio": 0.1,
    "max_length": 128
  },
  "ranking": [
    {
      "trial": "aspect_attention_term",
      "mean_macro_f1": 0.780567,
      "std_macro_f1": 0.005838,
      "robust_macro_f1": 0.774729,
      "mean_accuracy": 0.8164,
      "mean_loss": 0.545867,
      "mean_log_loss": 0.4764,
      "mean_ece": 0.052033,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "aspect_attention",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.0,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "aspect_attention_neutral125",
      "mean_macro_f1": 0.781467,
      "std_macro_f1": 0.010403,
      "robust_macro_f1": 0.771064,
      "mean_accuracy": 0.810667,
      "mean_loss": 0.595633,
      "mean_log_loss": 0.4874,
      "mean_ece": 0.056467,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "aspect_attention",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.25,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "hybrid_term",
      "mean_macro_f1": 0.775233,
      "std_macro_f1": 0.018891,
      "robust_macro_f1": 0.756343,
      "mean_accuracy": 0.8173,
      "mean_loss": 0.617333,
      "mean_log_loss": 0.467833,
      "mean_ece": 0.047533,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "hybrid",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.0,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "baseline_cls",
      "mean_macro_f1": 0.7775,
      "std_macro_f1": 0.023473,
      "robust_macro_f1": 0.754027,
      "mean_accuracy": 0.8192,
      "mean_loss": 0.694233,
      "mean_log_loss": 0.4945,
      "mean_ece": 0.0458,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "cls",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.0,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "cls_neutral150",
      "mean_macro_f1": 0.772033,
      "std_macro_f1": 0.02335,
      "robust_macro_f1": 0.748683,
      "mean_accuracy": 0.808733,
      "mean_loss": 0.6539,
      "mean_log_loss": 0.500933,
      "mean_ece": 0.036833,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "cls",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.5,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    },
    {
      "trial": "cls_neutral125",
      "mean_macro_f1": 0.767767,
      "std_macro_f1": 0.021833,
      "robust_macro_f1": 0.745934,
      "mean_accuracy": 0.814467,
      "mean_loss": 0.630633,
      "mean_log_loss": 0.501167,
      "mean_ece": 0.051167,
      "validation_seed_pairs": "2024:2024,42:42,3407:3407",
      "pooling_strategy": "cls",
      "input_format": "term",
      "encoder_layer_pooling": "last",
      "encoder_learning_rate": 8e-06,
      "head_learning_rate": 2e-05,
      "dropout": 0.3,
      "class_weighting": "none",
      "neutral_weight_multiplier": 1.25,
      "label_smoothing": 0.02,
      "loss_type": "cross_entropy",
      "scheduler": "linear",
      "warmup_ratio": 0.1,
      "max_length": 128
    }
  ]
}
FINAL RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 15 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 2024 --output-dir /kaggle/working/outputs_laptop_ablation_core --run-name lap_aspect_attention_term_seed2024 --evaluation-split test --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing --refit-full-train

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 17:48:51.501073: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782064131.519192     567 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782064131.525250     567 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782064131.540828     567 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782064131.540870     567 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782064131.540876     567 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782064131.540880     567 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1978,
      "labels": {
        "negative": 743,
        "neutral": 393,
        "positive": 842
      },
      "unique_aspects": 844
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 349,
      "labels": {
        "negative": 127,
        "neutral": 70,
        "positive": 152
      },
      "unique_aspects": 212,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3209
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 283,
      "unseen_aspect_ratio": 0.4436
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/15 train_loss=1.1364 valid_loss=0.8972 valid_acc=0.6275 valid_f1=0.4612 lr=5.25e-06 time=49.0s eta=11.4m
saved best checkpoint: epoch=1 valid_f1=0.4612
epoch=2/15 train_loss=0.7550 valid_loss=0.4883 valid_acc=0.8223 valid_f1=0.7755 lr=7.71e-06 time=48.5s eta=10.5m
saved best checkpoint: epoch=2 valid_f1=0.7755
epoch=3/15 train_loss=0.4830 valid_loss=0.5115 valid_acc=0.7822 valid_f1=0.7272 lr=7.12e-06 time=47.8s eta=9.6m
no improvement: 1/3
epoch=4/15 train_loss=0.3507 valid_loss=0.5456 valid_acc=0.7908 valid_f1=0.7546 lr=6.53e-06 time=47.7s eta=8.7m
no improvement: 2/3
epoch=5/15 train_loss=0.2696 valid_loss=0.5786 valid_acc=0.8109 valid_f1=0.7854 lr=5.94e-06 time=47.6s eta=7.9m
saved best checkpoint: epoch=5 valid_f1=0.7854
epoch=6/15 train_loss=0.2107 valid_loss=0.6685 valid_acc=0.7966 valid_f1=0.7158 lr=5.34e-06 time=47.8s eta=7.2m
no improvement: 1/3
epoch=7/15 train_loss=0.1725 valid_loss=0.6755 valid_acc=0.7937 valid_f1=0.7438 lr=4.75e-06 time=47.7s eta=6.4m
no improvement: 2/3
epoch=8/15 train_loss=0.1476 valid_loss=0.7544 valid_acc=0.7937 valid_f1=0.7552 lr=4.16e-06 time=48.1s eta=5.6m
no improvement: 3/3
early stopping at epoch 8; best epoch was 5
calibration_temperature=1.614072
refit_epoch=1/5 train_loss=1.1065 lr=5.26e-06 time=54.2s
refit_epoch=2/5 train_loss=0.6891 lr=7.71e-06 time=54.3s
refit_epoch=3/5 train_loss=0.4645 lr=7.12e-06 time=53.8s
refit_epoch=4/5 train_loss=0.3321 lr=6.53e-06 time=54.3s
refit_epoch=5/5 train_loss=0.2710 lr=5.94e-06 time=54.0s
{
  "test": {
    "accuracy": 0.7837,
    "precision_macro": 0.7592,
    "recall_macro": 0.7476,
    "macro_f1": 0.7224,
    "weighted_f1": 0.763,
    "roc_auc_macro": 0.9132,
    "average_confidence": 0.8592,
    "expected_calibration_error": 0.0785,
    "temperature": 1.614072,
    "uncalibrated_confidence": 0.9273,
    "seen": {
      "samples": 370,
      "accuracy": 0.8297,
      "macro_f1": 0.7451
    },
    "unseen": {
      "samples": 268,
      "accuracy": 0.7201,
      "macro_f1": 0.6934
    }
  },
  "zip": "/kaggle/working/outputs_laptop_ablation_core/lap_aspect_attention_term_seed2024_artifacts.zip"
}
FINAL RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 15 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 42 --output-dir /kaggle/working/outputs_laptop_ablation_core --run-name lap_aspect_attention_term_seed42 --evaluation-split test --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing --refit-full-train

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 18:02:03.615531: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782064923.634758     595 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782064923.641196     595 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782064923.658115     595 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782064923.658138     595 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782064923.658141     595 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782064923.658144     595 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1978,
      "labels": {
        "negative": 743,
        "neutral": 393,
        "positive": 842
      },
      "unique_aspects": 844
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 349,
      "labels": {
        "negative": 127,
        "neutral": 70,
        "positive": 152
      },
      "unique_aspects": 212,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3209
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 283,
      "unseen_aspect_ratio": 0.4436
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/15 train_loss=1.1518 valid_loss=0.8929 valid_acc=0.6218 valid_f1=0.4965 lr=5.29e-06 time=48.4s eta=11.3m
saved best checkpoint: epoch=1 valid_f1=0.4965
epoch=2/15 train_loss=0.7445 valid_loss=0.4917 valid_acc=0.8023 valid_f1=0.7293 lr=7.71e-06 time=48.2s eta=10.4m
saved best checkpoint: epoch=2 valid_f1=0.7293
epoch=3/15 train_loss=0.5121 valid_loss=0.5071 valid_acc=0.7851 valid_f1=0.6982 lr=7.12e-06 time=47.8s eta=9.6m
no improvement: 1/3
epoch=4/15 train_loss=0.3662 valid_loss=0.5397 valid_acc=0.8080 valid_f1=0.7093 lr=6.53e-06 time=47.7s eta=8.7m
no improvement: 2/3
epoch=5/15 train_loss=0.2632 valid_loss=0.5709 valid_acc=0.8166 valid_f1=0.7440 lr=5.94e-06 time=47.5s eta=7.9m
saved best checkpoint: epoch=5 valid_f1=0.7440
epoch=6/15 train_loss=0.2160 valid_loss=0.6750 valid_acc=0.8109 valid_f1=0.7161 lr=5.35e-06 time=47.9s eta=7.2m
no improvement: 1/3
epoch=7/15 train_loss=0.1854 valid_loss=0.5865 valid_acc=0.8281 valid_f1=0.7815 lr=4.76e-06 time=47.8s eta=6.4m
saved best checkpoint: epoch=7 valid_f1=0.7815
epoch=8/15 train_loss=0.1516 valid_loss=0.6821 valid_acc=0.8052 valid_f1=0.7589 lr=4.16e-06 time=48.0s eta=5.6m
no improvement: 1/3
epoch=9/15 train_loss=0.1386 valid_loss=0.7062 valid_acc=0.8195 valid_f1=0.7669 lr=3.57e-06 time=47.7s eta=4.8m
no improvement: 2/3
epoch=10/15 train_loss=0.1284 valid_loss=0.6676 valid_acc=0.8309 valid_f1=0.7840 lr=2.98e-06 time=47.6s eta=4.0m
saved best checkpoint: epoch=10 valid_f1=0.7840
epoch=11/15 train_loss=0.1191 valid_loss=0.6902 valid_acc=0.8166 valid_f1=0.7637 lr=2.38e-06 time=47.9s eta=3.2m
no improvement: 1/3
epoch=12/15 train_loss=0.1141 valid_loss=0.7240 valid_acc=0.8138 valid_f1=0.7542 lr=1.79e-06 time=47.8s eta=2.4m
no improvement: 2/3
epoch=13/15 train_loss=0.1094 valid_loss=0.7003 valid_acc=0.8195 valid_f1=0.7777 lr=1.20e-06 time=48.1s eta=1.6m
no improvement: 3/3
early stopping at epoch 13; best epoch was 10
calibration_temperature=1.861002
refit_epoch=1/10 train_loss=1.1269 lr=5.26e-06 time=54.4s
refit_epoch=2/10 train_loss=0.6809 lr=7.71e-06 time=54.3s
refit_epoch=3/10 train_loss=0.4709 lr=7.12e-06 time=54.2s
refit_epoch=4/10 train_loss=0.3456 lr=6.53e-06 time=54.3s
refit_epoch=5/10 train_loss=0.2629 lr=5.93e-06 time=54.5s
refit_epoch=6/10 train_loss=0.2018 lr=5.34e-06 time=55.1s
refit_epoch=7/10 train_loss=0.1847 lr=4.75e-06 time=54.7s
refit_epoch=8/10 train_loss=0.1597 lr=4.16e-06 time=54.3s
refit_epoch=9/10 train_loss=0.1310 lr=3.56e-06 time=54.7s
refit_epoch=10/10 train_loss=0.1227 lr=2.97e-06 time=55.0s
{
  "test": {
    "accuracy": 0.815,
    "precision_macro": 0.7778,
    "recall_macro": 0.7909,
    "macro_f1": 0.7754,
    "weighted_f1": 0.8111,
    "roc_auc_macro": 0.9171,
    "average_confidence": 0.8628,
    "expected_calibration_error": 0.0496,
    "temperature": 1.861002,
    "uncalibrated_confidence": 0.9625,
    "seen": {
      "samples": 370,
      "accuracy": 0.8405,
      "macro_f1": 0.7777
    },
    "unseen": {
      "samples": 268,
      "accuracy": 0.7799,
      "macro_f1": 0.769
    }
  },
  "zip": "/kaggle/working/outputs_laptop_ablation_core/lap_aspect_attention_term_seed42_artifacts.zip"
}
FINAL RUN: /usr/bin/python3 train.py --dataset lap --model microsoft/deberta-v3-base --epochs 15 --patience 3 --batch-size 8 --gradient-accumulation-steps 2 --weight-decay 0.01 --valid-ratio 0.15 --split-seed 2024 --seed 3407 --output-dir /kaggle/working/outputs_laptop_ablation_core --run-name lap_aspect_attention_term_seed3407 --evaluation-split test --pooling-strategy aspect_attention --input-format term --encoder-layer-pooling last --encoder-learning-rate 8e-06 --head-learning-rate 2e-05 --dropout 0.3 --class-weighting none --neutral-weight-multiplier 1.0 --label-smoothing 0.02 --loss-type cross_entropy --scheduler linear --warmup-ratio 0.1 --max-length 128 --amp --gradient-checkpointing --refit-full-train

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
2026-06-21 18:23:50.962998: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1782066230.982545     623 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1782066230.988728     623 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1782066231.005430     623 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782066231.005452     623 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782066231.005455     623 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1782066231.005458     623 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:566: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
You're using a DebertaV2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

pipeline_version=absa-training-v4-clean-ablation
{
  "device": "cuda",
  "data": {
    "train": {
      "samples": 1978,
      "labels": {
        "negative": 743,
        "neutral": 393,
        "positive": 842
      },
      "unique_aspects": 844
    },
    "train_all": {
      "samples": 2327,
      "labels": {
        "negative": 870,
        "neutral": 463,
        "positive": 994
      },
      "unique_aspects": 949,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.0481
    },
    "valid": {
      "samples": 349,
      "labels": {
        "negative": 127,
        "neutral": 70,
        "positive": 152
      },
      "unique_aspects": 212,
      "unseen_aspect_samples": 112,
      "unseen_aspect_ratio": 0.3209
    },
    "test": {
      "samples": 638,
      "labels": {
        "negative": 128,
        "neutral": 169,
        "positive": 341
      },
      "unique_aspects": 389,
      "unseen_aspect_samples": 283,
      "unseen_aspect_ratio": 0.4436
    },
    "excluded_train_test_overlap": {
      "samples": 1,
      "labels": {
        "neutral": 1
      },
      "unique_aspects": 1,
      "unseen_aspect_samples": 0,
      "unseen_aspect_ratio": 0.0
    }
  }
}
{
  "class_weights": {
    "negative": 1.0,
    "neutral": 1.0,
    "positive": 1.0
  }
}
epoch=1/15 train_loss=1.1679 valid_loss=0.8614 valid_acc=0.6103 valid_f1=0.4441 lr=5.25e-06 time=47.5s eta=11.1m
saved best checkpoint: epoch=1 valid_f1=0.4441
epoch=2/15 train_loss=0.7311 valid_loss=0.4568 valid_acc=0.8281 valid_f1=0.7697 lr=7.71e-06 time=46.7s eta=10.1m
saved best checkpoint: epoch=2 valid_f1=0.7697
epoch=3/15 train_loss=0.4851 valid_loss=0.4919 valid_acc=0.8223 valid_f1=0.7708 lr=7.12e-06 time=47.1s eta=9.4m
no improvement: 1/3
epoch=4/15 train_loss=0.3785 valid_loss=0.5635 valid_acc=0.8023 valid_f1=0.7314 lr=6.53e-06 time=46.4s eta=8.5m
no improvement: 2/3
epoch=5/15 train_loss=0.2711 valid_loss=0.6208 valid_acc=0.8138 valid_f1=0.7907 lr=5.94e-06 time=47.1s eta=7.8m
saved best checkpoint: epoch=5 valid_f1=0.7907
epoch=6/15 train_loss=0.2186 valid_loss=0.6509 valid_acc=0.7765 valid_f1=0.7263 lr=5.35e-06 time=46.8s eta=7.0m
no improvement: 1/3
epoch=7/15 train_loss=0.1933 valid_loss=0.7531 valid_acc=0.7880 valid_f1=0.7180 lr=4.76e-06 time=46.3s eta=6.2m
no improvement: 2/3
epoch=8/15 train_loss=0.1623 valid_loss=0.7458 valid_acc=0.7994 valid_f1=0.7565 lr=4.16e-06 time=46.3s eta=5.4m
no improvement: 3/3
early stopping at epoch 8; best epoch was 5
calibration_temperature=1.646387
refit_epoch=1/5 train_loss=1.1400 lr=5.26e-06 time=52.8s
refit_epoch=2/5 train_loss=0.6681 lr=7.71e-06 time=53.0s
refit_epoch=3/5 train_loss=0.4420 lr=7.12e-06 time=53.4s
refit_epoch=4/5 train_loss=0.3447 lr=6.53e-06 time=52.7s
refit_epoch=5/5 train_loss=0.2552 lr=5.94e-06 time=52.6s
{
  "test": {
    "accuracy": 0.8072,
    "precision_macro": 0.7869,
    "recall_macro": 0.7693,
    "macro_f1": 0.7475,
    "weighted_f1": 0.79,
    "roc_auc_macro": 0.9175,
    "average_confidence": 0.8731,
    "expected_calibration_error": 0.0694,
    "temperature": 1.646387,
    "uncalibrated_confidence": 0.9418,
    "seen": {
      "samples": 370,
      "accuracy": 0.8486,
      "macro_f1": 0.7663
    },
    "unseen": {
      "samples": 268,
      "accuracy": 0.75,
      "macro_f1": 0.7251
    }
  },
  "zip": "/kaggle/working/outputs_laptop_ablation_core/lap_aspect_attention_term_seed3407_artifacts.zip"
}

CompletedProcess(args=['/usr/bin/python3', 'tune.py', '--dataset', 'lap', '--search-space', 'ablation_core', '--validation-seed-pairs', '2024:2024,42:42,3407:3407', '--valid-ratio', '0.15', '--final-seeds', '2024,42,3407', '--epochs', '12', '--final-epochs', '15', '--patience', '3', '--batch-size', '8', '--gradient-accumulation-steps', '2', '--amp', '--gradient-checkpointing', '--run-final', '--output-dir', '/kaggle/working/tuning_laptop_ablation_core', '--final-output-dir', '/kaggle/working/outputs_laptop_ablation_core'], returncode=0)

## 5. Tổng hợp kết quả core

In [6]:
import pandas as pd

summary_path = CORE_TUNING / 'tuning_summary.csv'
final_path = CORE_FINAL / 'final_runs_summary.csv'
meanstd_path = CORE_FINAL / 'final_metrics_mean_std.json'

summary = pd.read_csv(summary_path)
cols = [c for c in ['trial','mean_macro_f1','std_macro_f1','robust_macro_f1','mean_accuracy','mean_ece','pooling_strategy','input_format','neutral_weight_multiplier'] if c in summary.columns]
display(summary[cols])

if final_path.exists():
    display(pd.read_csv(final_path))
if meanstd_path.exists():
    print(json.dumps(json.loads(meanstd_path.read_text()), indent=2))

,trial,mean_macro_f1,std_macro_f1,robust_macro_f1,mean_accuracy,mean_ece,pooling_strategy,input_format,neutral_weight_multiplier
0,aspect_attention_term,0.780567,0.005838,0.774729,0.816400,0.052033,aspect_attention,term,1.00
1,aspect_attention_neutral125,0.781467,0.010403,0.771064,0.810667,0.056467,aspect_attention,term,1.25
2,hybrid_term,0.775233,0.018891,0.756343,0.817300,0.047533,hybrid,term,1.00
3,baseline_cls,0.777500,0.023473,0.754027,0.819200,0.045800,cls,term,1.00
4,cls_neutral150,0.772033,0.023350,0.748683,0.808733,0.036833,cls,term,1.50
5,cls_neutral125,0.767767,0.021833,0.745934,0.814467,0.051167,cls,term,1.25

,seed,best_epoch,accuracy,precision_macro,recall_macro,macro_f1,weighted_f1,roc_auc_macro,log_loss,expected_calibration_error,temperature
0,2024,5,0.7837,0.7592,0.7476,0.7224,0.7630,0.9132,0.5753,0.0785,1.614072
1,42,10,0.8150,0.7778,0.7909,0.7754,0.8111,0.9171,0.5389,0.0496,1.861002
2,3407,5,0.8072,0.7869,0.7693,0.7475,0.7900,0.9175,0.5677,0.0694,1.646387

{
  "accuracy": {
    "mean": 0.801967,
    "std": 0.013303
  },
  "precision_macro": {
    "mean": 0.774633,
    "std": 0.011528
  },
  "recall_macro": {
    "mean": 0.769267,
    "std": 0.017677
  },
  "macro_f1": {
    "mean": 0.748433,
    "std": 0.021647
  },
  "weighted_f1": {
    "mean": 0.788033,
    "std": 0.019686
  },
  "roc_auc_macro": {
    "mean": 0.915933,
    "std": 0.00194
  },
  "log_loss": {
    "mean": 0.560633,
    "std": 0.015678
  },
  "expected_calibration_error": {
    "mean": 0.065833,
    "std": 0.012065
  }
}

## 6. Tùy chọn: chạy aspect-description ablation

Mặc định tắt để không trộn kết quả core với tác động của `aspects.json`.

In [7]:
RUN_DESC_ABLATION = False

if RUN_DESC_ABLATION:
    desc_cmd = [
        sys.executable, 'tune.py',
        '--dataset', 'lap',
        '--search-space', 'ablation_desc',
        '--validation-seed-pairs', SEED_PAIRS,
        '--valid-ratio', str(VALID_RATIO),
        '--final-seeds', FINAL_SEEDS,
        '--epochs', str(EPOCHS),
        '--final-epochs', str(FINAL_EPOCHS),
        '--patience', '3',
        '--batch-size', str(BATCH_SIZE),
        '--gradient-accumulation-steps', str(GRAD_ACCUM),
        '--amp', '--gradient-checkpointing', '--run-final',
        '--output-dir', str(DESC_TUNING),
        '--final-output-dir', str(DESC_FINAL),
    ]
    print(' '.join(desc_cmd))
    subprocess.run(desc_cmd, check=True)
else:
    print('Description ablation is disabled.')

Description ablation is disabled.

## 7. Đóng gói kết quả để tải về

Checkpoint và các ZIP artifact lồng nhau được bỏ qua mặc định để tránh file kết quả tăng lên hàng GB. Các JSON, CSV, prediction và biểu đồ vẫn được giữ.

In [8]:
INCLUDE_CHECKPOINTS = False
folders = [CORE_TUNING, CORE_FINAL, DESC_TUNING, DESC_FINAL]

with zipfile.ZipFile(RESULT_ZIP, 'w', compression=zipfile.ZIP_DEFLATED) as zf:
    for folder in folders:
        if not folder.exists():
            continue
        for path in folder.rglob('*'):
            if not path.is_file():
                continue
            if not INCLUDE_CHECKPOINTS and path.suffix in {'.pt', '.pth', '.bin', '.safetensors'}:
                continue
            if path.name.endswith('_artifacts.zip'):
                continue
            zf.write(path, path.relative_to(WORK))

print('Created:', RESULT_ZIP)
print('Size MB:', round(RESULT_ZIP.stat().st_size / 1024 / 1024, 2))

Created: /kaggle/working/absa_laptop_results_fresh.zip
Size MB: 8.94